#!/usr/bin/env python3
"""
Mass create categories on shinto.miraheze.org with standard template.
Each category gets [[Category:Categories mass created after the Engishiki wikidata generation]]
"""

import sys
import io
import time
import mwclient

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Wiki credentials
WIKI_URL = 'shinto.miraheze.org'
WIKI_PATH = '/w/'
USERNAME = 'Immanuelle'
PASSWORD = '[REDACTED_SECRET_2]'

# Categories to create - exact names from user's list
CATEGORIES = [
    "QID redirects",
    "Shinto shrine",
    "Engishiki seat",
    "Kokuhei Shosha (Engishiki)",
    "Pages using infobox mapframe with no geometry",
    "Shikinai Ronsha",
    "Shikinai Hiteisha",
    "Former redirect categories falsely tagged",
    "Autogenerated pages with jawiki interwikis, possibly accidentally overwritten",
    "Disputed Shikinaisha or Shikigeisha",
    "Junior Fifth Rank",
    "Has wikidata",
    "Pages with unclosed square brackets",
    "Kanpei Shosha (Engishiki)",
    "Year categories to be fixed",
    "Pages with unclosed curly braces",
    "Shikinai Subshrine",
    "Pages with unclosed parentheses",
    "Pages using infobox deity with unrecognised type",
    "Categories in Categories missing wikidata but actually having wikidata but with jawiki",
    "Pages linked to everybodywiki",
    "Senior Fifth Rank",
    "Gōshi",
    "Kanpei Taisha (Engishiki)",
    "Junior Fourth Rank",
    "Kokuhei Taisha (Engishiki)",
    "Kokuhei Myojin Taisha",
    "Shrine receiving Tsukinami-sai and Niiname-sai offerings",
    "Shikinai Supershrine",
    "Unranked",
    "Kanpei Shikinai Taisha",
    "Hachiman shrine",
    "Senior Sixth Rank",
    "Pages likely having an accidental overwite in their history that shrank them",
    "Pages with recovered content",
    "Shrines receiving Hoe and Quiver",
    "Keidai-sha",
    "Kanpei Myojin Taisha",
    "Tenmangū (worship)",
    "Senior Fourth Rank",
    "Autogenerated pages with simplewiki or enwiki interwikis, possibly accidentally overwritten",
    "Massha",
    "Shikinai Successor",
    "Keidai-Sessha",
    "Shikinaisha Former Site",
    "Merged Shikinaisha autogenerations with enwiki",
    "Shrine receiving Tsukinami-sai and Niiname-sai and Ainame-sai offerings",
    "Junior Third Rank",
    "Sessha",
    "Keigai-Sessha",
    "Lunisolar 10 Month",
    "Lunisolar 11 Month",
    "Lunisolar 12 Month",
    "Lunisolar 1 Month",
    "Lunisolar 2 Month",
    "Lunisolar 3 Month",
    "Lunisolar 4 Month",
    "Lunisolar 5 Month",
    "Lunisolar 6 Month",
    "Lunisolar 7 Month",
    "Lunisolar 8 Month",
    "Lunisolar 9 Month",
    "San-no-Miya",
    "Shrines receiving hoe offering",
    "Kasuga shrine (worship)",
    "Beppyo Shrine",
    "Ni-no-Miya",
    "Senior Third Rank",
    "Shinmei shrine",
    "Junior Second Rank",
    "Hakusan shrine",
    "Hyōzu shrine",
    "Kamo Shrine (worship)",
    "Kashima Shrine (worship)",
    "Inari shrine",
    "Sumiyoshi shrine",
    "Kumano shrine",
    "Sannō shrine",
    "Lost Shikinaisha or Shikigeisha",
    "Shizuri Shrine (worship)",
    "Suwa Shrine",
    "Betsu-gū",
    "Gion shrine",
    "Kamigamo Shrine",
    "Kokuhei Shikinai Taisha",
    "Senior Second Rank",
    "Atago shrine (worship)",
    "Dyad",
    "Raiden Shrine (worship)",
    "Sengen shrine",
    "Shi-no-Miya",
    "Keigai-sha",
    "Mishima shrine",
    "Okumiya",
    "Senior Eighth Rank",
    "Group of structures or buildings",
    "Junior First Rank",
    "Pages with files linked by ill",
    "Buddhist temple",
    "Category wikidata stuff",
    "Hibayamakume Shrine",
    "Hikawa shrine",
    "Kasuga Redirects",
    "Onsen shrine",
    "Regional Sōja",
    "Second attempt at refreshing on January 27 2024",
    "Shrines receiving Quiver offering",
    "Ōmushi Shrine (Echizen)",
]

def main():
    """Main execution."""
    print("="*70)
    print("MASS CREATE CATEGORIES")
    print("="*70)
    print()

    try:
        # Login to wiki
        print(f"Connecting to {WIKI_URL}...")
        site = mwclient.Site(WIKI_URL, path=WIKI_PATH)
        site.login(USERNAME, PASSWORD)

        # Retrieve username
        try:
            ui = site.api('query', meta='userinfo')
            logged_user = ui['query']['userinfo'].get('name', USERNAME)
            print(f"Logged in as {logged_user}\n")
        except Exception:
            print("Logged in (could not fetch username via API, but login succeeded).\n")

        created = []
        failed = []

        print(f"Creating {len(CATEGORIES)} categories...\n")

        for i, cat_name in enumerate(CATEGORIES, 1):
            page_title = f"Category:{cat_name}"
            print(f"{i}/{len(CATEGORIES)}: Creating '{cat_name}'...", end=" ")

            try:
                page = site.pages[page_title]

                # Check if category page exists
                try:
                    existing = page.text()
                    if existing.strip():
                        print("[SKIP - already exists]")
                        continue
                except:
                    pass

                # Create page with standard template
                content = "[[Category:Categories mass created after the Engishiki wikidata generation]]\n"

                page.edit(content, summary="Mass create category after Engishiki wikidata generation")
                print("[OK]")
                created.append(cat_name)

                # Rate limit
                time.sleep(1.5)

            except Exception as e:
                print(f"[FAILED] {e}")
                failed.append((cat_name, str(e)))

        # Summary
        print("\n" + "="*70)
        print(f"CREATION SUMMARY")
        print("="*70)
        print(f"Created: {len(created)}")
        print(f"Failed: {len(failed)}")
        print(f"Total: {len(CATEGORIES)}")
        print()

        if failed:
            print("FAILED CATEGORIES:")
            for cat, reason in failed:
                print(f"  {cat}: {reason}")
            print()

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    main()
