#!/usr/bin/env python3
"""
merge_duplicate_qid_pages.py
============================
For duplicate QIDs with pattern [[TITLE]] and [[TITLE (QID)]]:
1. Copy content from [[TITLE (QID)]] to bottom of [[TITLE]]
2. Add ==AUTOGENERATED CONTENT FROM WIKIDATA== heading
3. Blank [[TITLE (QID)]] and redirect to [[TITLE]]
"""

import csv
import mwclient
import re
import sys
import time

# Fix Unicode encoding issues on Windows
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL  = 'shinto.miraheze.org'
WIKI_PATH = '/w/'
USERNAME  = 'Immanuelle'
PASSWORD  = '[REDACTED_SECRET_2]'

site = mwclient.Site(WIKI_URL, path=WIKI_PATH)
site.login(USERNAME, PASSWORD)

print("Logged in\n")

# Read duplicate QIDs CSV
duplicates = []
with open('duplicate_qids.csv', 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        duplicates.append(row)

print(f"Read {len(duplicates)} duplicate QID sets\n")

# Find duplicates that match the pattern [[TITLE]] and [[TITLE (QID)]]
pattern_matches = []
non_pattern = []

for duplicate in duplicates:
    qid = duplicate['QID']
    count = int(duplicate['Count'])

    # Get all pages for this QID
    pages = []
    for key in duplicate:
        if key.startswith('Page'):
            page = duplicate[key]
            if page:
                page = page.strip() if isinstance(page, str) else page
                if page:
                    pages.append(page)

    # Check if this matches the pattern: exactly 2 pages, one is base and one is base (QID)
    if count == 2 and len(pages) == 2:
        # Sort to check pattern
        base_page = None
        qid_page = None

        for page in pages:
            if f"({qid})" in page:
                qid_page = page
                base_page = page[:-len(f" ({qid})")].strip()
            else:
                if not base_page or page == base_page:
                    base_page = page

        # Verify the pattern matches
        if base_page and qid_page and qid_page == f"{base_page} ({qid})":
            if base_page in pages and qid_page in pages:
                pattern_matches.append({
                    'qid': qid,
                    'base_page': base_page,
                    'qid_page': qid_page
                })
            else:
                non_pattern.append({'qid': qid, 'pages': pages})
        else:
            non_pattern.append({'qid': qid, 'pages': pages})
    else:
        non_pattern.append({'qid': qid, 'pages': pages})

print(f"Pattern matches (TITLE + TITLE (QID)): {len(pattern_matches)}")
print(f"Non-pattern duplicates: {len(non_pattern)}\n")

# Process pattern matches
successful = 0
failed = 0

for i, match in enumerate(pattern_matches, 1):
    base_page = match['base_page']
    qid_page = match['qid_page']
    qid = match['qid']

    print(f"{i}. Processing [[{base_page}]] + [[{qid_page}]]...")

    try:
        # Get content from QID page
        qid_page_obj = site.Pages[qid_page]
        qid_content = qid_page_obj.text()

        # Get content from base page
        base_page_obj = site.Pages[base_page]
        base_content = base_page_obj.text()

        # Add QID content to base page under new heading
        new_content = base_content + "\n\n== AUTOGENERATED CONTENT FROM WIKIDATA ==\n\n" + qid_content

        # Edit base page
        base_page_obj.edit(new_content, f"Merge content from [[{qid_page}]]")
        print(f"   ✓ Added content to [[{base_page}]]")

        # Blank QID page and add redirect
        redirect_content = f"#REDIRECT [[{base_page}]]"
        qid_page_obj.edit(redirect_content, f"Redirect to [[{base_page}]]")
        print(f"   ✓ Redirected [[{qid_page}]] to [[{base_page}]]\n")

        successful += 1

    except Exception as e:
        print(f"   ✗ Error: {e}\n")
        failed += 1

    time.sleep(1.5)

print(f"\n=== Summary ===")
print(f"Successfully merged: {successful}/{len(pattern_matches)}")
print(f"Failed: {failed}/{len(pattern_matches)}")
print(f"Non-pattern duplicates (skipped): {len(non_pattern)}")
