#!/usr/bin/env python3
"""
add_category_content.py
=======================
Adds [[Category:Categories created from Wanted Categories on Nov 16, 2025]]
to all blank categories.
"""
# >>> credentials / endpoint >>>
API_URL  = "https://shinto.miraheze.org/w/api.php"
USERNAME = "Immanuelle"
PASSWORD = "[REDACTED_SECRET_1]"
# <<< credentials <<<

import os, sys, time, urllib.parse, mwclient
from mwclient.errors import APIError

THROTTLE = 0.5

# ─── site login ───────────────────────────────────────────────────

def site():
    p = urllib.parse.urlparse(API_URL)
    s = mwclient.Site(p.netloc, path=p.path.rsplit("/api.php",1)[0]+"/")
    s.login(USERNAME,PASSWORD)
    return s

# List of categories to update
categories = [
    "Categories missing wikidata",
    "Categories made on November 5, 2025",
    "Templates missing wikidata",
    "Matching pagename on wikidata",
    "Wikidata linked Islamic Dates",
    "Automatic wikipedia redirects starting with J",
    "Everybody linked",
    "Non matching pagename on wikidata",
    "Automatic wikipedia redirects starting with C",
    "Automatic wikipedia redirects starting with 2",
    "Automatic wikipedia redirects starting with 1",
    "Automatic wikipedia redirects starting with F",
    "Special:LonelyPages November 4 2025",
    "Automatic wikipedia redirects starting with L",
    "Automatic wikipedia redirects starting with A",
    "Automatic wikipedia redirects starting with S",
    "Automatic wikipedia redirects starting with G",
    "Automatic wikipedia redirects starting with O",
    "Automatic wikipedia redirects starting with V",
    "Blank Shikinaisha with no wikidata",
    "Candidates for speedy deletion",
    "Candidates for technical speedy deletion",
    "Automatic wikipedia redirects starting with B",
    "Jingus without interwikis",
    "CS1 errors",
    "Templates without wikidata",
    "CS1 maintenance",
    "Automatic wikipedia redirects starting with R",
    "Automatic wikipedia redirects starting with =",
    "Automatic wikipedia redirects starting with T",
    "Philosophers by field",
    "Unchecked Islamic Dates",
    "Automatic wikipedia redirects starting with M",
    "CS1 properties",
    "CS1 uses foreign language script",
    "Clean-up categories from April 2021",
    "Monthly clean-up category (Articles with dead external links) counter",
    "Automatic wikipedia redirects starting with 6",
    "Automatic wikipedia redirects starting with 8",
    "Automatic wikipedia redirects starting with 9",
    "Automatic wikipedia redirects starting with D",
    "Automatic wikipedia redirects starting with K",
    "Automatic wikipedia redirects starting with N",
    "Clean-up categories from May 2018",
    "Clean-up categories from October 2021",
    "Computing infobox templates",
    "Epistemology",
    "Linux",
    "Monthly clean-up category (Articles with specifically marked weasel-worded phrases) counter",
    "Philosophy of social science",
    "Plan 9 commands",
    "Standard Unix programs",
    "Systems science",
    "Wikipedia templates by topic",
    "特別史跡",
    "1st-century establishments",
    "20世紀アジアの女性王族",
    "20世紀アジアの王族",
    "20世紀日本の女性 (職業別)",
    "216 births",
    "21st-century American people by occupation",
    "21st-century philosophers by nationality",
    "21世紀アジアの女性王族",
    "21世紀アジアの王族",
    "21世紀日本の女性 (職業別)",
    "274 deaths",
    "3rd-century Iranian people",
    "3rd-century religious leaders",
    "3rd-century theologians",
    "3rd-century writers",
    "6世紀アジアの女性王族",
    "6世紀アジアの王族",
    "6世紀日本の女性 (職業別)",
    "7世紀アジアの女性王族",
    "7世紀アジアの王族",
    "7世紀日本の女性 (職業別)",
    "8世紀アジアの女性王族",
    "8世紀アジアの王族",
    "8世紀日本の女性 (職業別)",
    "9世紀アジアの王族",
    "Academic discipline interactions",
    "Active citizenship",
    "Alchemy",
    "American philosophers by century",
    "Ancient occultists",
    "Anti-natalists",
    "Applied mathematics",
    "Articles incorporating text from the 1913 Catholic Encyclopedia",
    "Articles needing attention",
    "Articles to be expanded from October 2018",
    "Articles with bare URLs for citations",
    "Articles with disputed statements from August 2021",
    "Articles with failed verification",
    "Articles with non-HTML file bare URLs for citations",
    "Articles with specifically marked weasel-worded phrases from June 2015",
    "Articles with specifically marked weasel-worded phrases from October 2018",
    "Articles with unsourced statements from June 2015",
    "Articles with unsourced statements from November 2025",
    "Automatic wikipedia redirects starting with 3",
    "Automatic wikipedia redirects starting with 4",
    "Automatic wikipedia redirects starting with E",
    "Automatic wikipedia redirects starting with H",
    "Automatic wikipedia redirects starting with I",
    "Automatic wikipedia redirects starting with P",
    "Automatic wikipedia redirects starting with Ā",
    "Bacteria phyla",
    "Bible navigational boxes",
    "Biological anthropology",
    "Bodies of water of Yamanashi Prefecture",
    "British scholars of Buddhism",
    "Buddhism and atheism",
    "Buddhist music",
    "Buddhist writers",
    "Buildings and structures in Kasama, Ibaraki",
    "CatAutoTOC tracking categories",
    "Characters in Greek mythology",
    "Children of Asclepius",
    "Christianity",
    "Clean-up categories from April 2015",
    "Clean-up categories from April 2016",
    "Clean-up categories from December 2017",
    "Clean-up categories from December 2020",
    "Clean-up categories from January 2016",
    "Clean-up categories from January 2017",
    "Clean-up categories from July 2008",
    "Clean-up categories from July 2017",
    "Clean-up categories from July 2020",
    "Clean-up categories from June 2018",
    "Clean-up categories from June 2019",
    "Clean-up categories from June 2022",
    "Clean-up categories from March 2021",
    "Clean-up categories from March 2022",
    "Clean-up categories from May 2008",
    "Clean-up categories from November 2014",
    "Clean-up categories from November 2018",
    "Clean-up categories from October 2018",
    "Clean-up categories from October 2020",
    "Clean-up categories from September 2022",
    "Cognitive psychology",
    "Communication",
    "Communication circuits",
    "Community development",
    "Computational science",
    "Computer networking",
    "Computing and society",
    "Computing templates",
    "Computing terminology",
    "Concurrency control",
    "Conversion to Buddhism",
    "Converts to Buddhism from atheism or agnosticism",
    "Creators of writing systems",
    "Crimea templates",
    "Cross-cultural studies",
    "Ctesiphon",
    "Data",
    "Databases",
    "Electronic design automation",
    "Epistle to the Galatians",
    "Ethicists",
    "Europe country and territory topics templates",
    "Europe language templates",
    "Evolution",
    "Evolution of primates",
    "Evolution templates",
    "Evolutionarily significant biological phenomena",
    "Evolutionary psychology",
    "Featured content",
    "Flagicon tracking categories",
    "Former village shrines in Ibaraki Prefecture",
    "Free file comparison tools",
    "French Buddhists",
    "French atheists",
    "Gaiad characters",
    "Geography of Takamatsu",
    "German writer navigational boxes",
    "Gnostics",
    "Greek goddesses",
    "Hardware acceleration",
    "Health goddesses",
    "Heresy in ancient Christianity",
    "Hermeticism",
    "History of Kasama, Ibaraki",
    "Indo-European culture",
    "Infobox templates with updated parameter",
    "Information Age",
    "Information retrieval",
    "Information technology management",
    "Integrated circuits",
    "Interdisciplinary branches of psychology",
    "Iranian painters",
    "Iranian prophets",
    "Iranian religious leaders",
    "Isaac Newton",
    "Latter Day Saint concepts",
    "Librettists",
    "MGS model",
    "Mathematical physics",
    "Mathematics source templates",
    "Mechanics",
    "Modularity",
    "Monthly clean-up category (Articles lacking reliable references) counter",
    "Monthly clean-up category (Articles needing additional references) counter",
    "Monthly clean-up category (Articles with failed verification) counter",
    "Monthly clean-up category (BLP articles lacking sources) counter",
    "Monthly clean-up category (Use British English) counter",
    "Mountains of Kagawa Prefecture",
    "Network on a chip",
    "Network theory",
    "New Testament templates",
    "Nine Saints",
    "Online organizations",
    "Organizational theory",
    "Pages using infobox artifact with unknown parameters",
    "Pages with a usurping enwiki page",
    "Parallel computing",
    "People executed by crucifixion",
    "People executed by flaying",
    "People executed by the Sasanian Empire",
    "Philosopher navigational boxes",
    "Philosophers by tradition",
    "Philosophy and thinking templates",
    "Pleistocene",
    "Pliocene",
    "Politics and race",
    "Portal Wiki Conflicting Categories",
    "Pre-Outage Pages",
    "Programming language templates",
    "Psychology information templates",
    "Psychology navigational boxes",
    "Religion Wikipedia administration",
    "Religion articles needing attention",
    "Religious converts",
    "Religious organizations established in 1954",
    "Science and technology studies scholars",
    "Scientific theories",
    "Scottish Buddhists",
    "Scottish atheists",
    "Self-organization",
    "Soba",
    "Social dynamics",
    "Social information processing",
    "Social media",
    "Social networking services",
    "Social sciences terminology",
    "Society Wikipedia administration",
    "Spanish language",
    "Stephen Batchelor",
    "Students of S. N. Goenka",
    "System on a chip",
    "TOC tracking on category pages where PAGESINCATEGORY returns zero",
    "Technical mathematics",
    "Template Category TOC tracking categories",
    "Templates to be translated",
    "The Church of Jesus Christ of Latter-day Saints",
    "Three Prophets",
    "Treatment of mental disorders",
    "Unix text processing utilities",
    "Use American English from October 2018",
    "Use dmy dates from October 2018",
    "Use mdy dates from November 2025",
    "Utility software by type",
    "Vertebrate developmental biology",
    "WikiProject Featured articles",
    "WikiProject Good articles",
    "WikiProject Medicine articles",
    "WikiProject Mesoamerica templates",
    "Wikipedia articles needing clarification from October 2018",
    "Wikipedia categories that track Wikisource references",
    "Wikipedia editorial validation",
    "Wikipedia featured articles",
    "Writers from Dundee",
    "Writers of lost works",
    "ニューレフトの思想・文化",
    "世界遺産 は行",
    "台湾の土木史",
    "台湾の文化史",
    "台湾の科学技術史",
    "台湾美術史",
    "和歌山県にある国指定の史跡",
    "哲学史研究者",
    "戦前日本の右翼団体",
    "日本のFMラジオ放送",
    "日本の国際交流",
    "日本の地政学",
    "日本の芸術家別のトピックス",
    "歴史のカテゴリ目次",
    "都市計画関連法規",
]

# Content to add
new_content = "[[Category:Categories created from Wanted Categories on Nov 16, 2025]]"

# ─── main loop ────────────────────────────────────────────────────

def main():
    s = site()
    print("Logged in")

    count = 0
    for cat_name in categories:
        try:
            print(f"Processing: {cat_name}")
            pg = s.pages[f"Category:{cat_name}"]

            if pg.exists:
                current_text = pg.text()
                # Check if category already has content
                if current_text.strip():
                    print("  [SKIP] already has content")
                    continue

            # Add the category content (create if doesn't exist, or overwrite if empty)
            try:
                pg.save(new_content, summary="Bot: Add category content from Wanted Categories on Nov 16, 2025")
                count += 1
                print("  [DONE] added category content")
            except APIError as e:
                print(f"  [FAILED] save failed: {e.code}")

            time.sleep(THROTTLE)

        except Exception as e:
            print(f"  [ERROR] {str(e)}")

    print(f"\nTotal categories updated: {count}")

if __name__=='__main__':
    main()
