#!/usr/bin/env python3
"""
add_ancient_pages_category.py
=============================
Adds [[Category:Ancient pages]] to specific pages on evolutionism.miraheze.org.
"""

import mwclient
import sys
import time

# Fix Unicode encoding issues on Windows
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Configuration
WIKI_URL = 'evolutionism.miraheze.org'
WIKI_PATH = '/w/'
USERNAME = 'Immanuelle'
PASSWORD = '[REDACTED_SECRET_2]'
SLEEP = 1.5

CATEGORY_TO_ADD = "[[Category:Ancient pages]]"
EDIT_SUMMARY = "Bot: Adding [[Category:Ancient pages]]"

PAGES = [
    "Theory of religious economy",
    "Cohesion (computer science)",
    "Initiation order",
    "Evolutionary origin of religions",
    "Proto Indo European Myth",
    "E-democracy",
    "Barabási–Albert model",
    "Erdős number",
    "Atomization",
    "Unfirmlaw",
    "Classes",
    "Extravagance",
    "Three pilgrimages",
    "Omega Pilgrimage",
    "Lambda Pilgrimage",
    "Modules",
    "Spiritual fitness",
    "Nobility test",
    "Great Filter",
    "Aswerving",
    "Asexual reproduction",
    "Critical Theory",
    "Marx's theory of domicide",
    "Evil eye",
    "Dunbar's number",
    "Volunteering",
    "Pre-axial religions",
    "Way of the future",
    "Urfa Pilgrimage",
    "Socrates",
    "Database Normalization",
    "Veneration of the dead",
    "Syntheism",
    "Non-binary gender",
    "Process Church of the Final Judgment",
    "Years",
    "Anthropic principle",
    "Laws of logic",
    "AD 10",
    "AD 1",
    "Collective evil",
    "Theodemocracy",
    "Anarchism",
    "Authoritarianism",
    "Sangha Democracy",
    "Dark Enlightenment",
    "Deradicalization",
    "Totalitarianism",
    "Hello Immortals",
    "Fermi paradox",
    "Aestivation hypothesis",
    "Filters",
    "Unlife",
    "Wantonness",
    "Analysis Paralysis",
    "Antifragility",
    "Laying on of hands",
    "Historical reading",
    "Jerusalem Pilgrimage",
    "Theories about religions",
    "Universal resurrection",
    "The Resurrection",
    "Contraception",
    "Fertility",
    "Repeal of roe v wade",
    "Proto Indo Europeans",
    "Malta Pilgrimage",
    "Life",
    "Domperidone",
    "Mark Fisher",
    "Vladimir Putin",
    "Volatile memory",
    "Models of a computer",
    "Chinese surname coats of arms",
    "Decline of Christianity in the Western world",
    "Influencarchy",
    "Client Side Development",
    "Limbo",
    "Climate movement",
    "Fascism",
    "Dyson sphere",
    "Monastery",
    "History of religion",
    "EED Diagram",
    "Channel to do list",
    "Sacred–profane dichotomy",
    "Profanum",
    "Atomicity (database systems)",
    "Consistency (database systems)",
    "Isolation (database systems)",
    "Durability (database systems)",
    "JavaScript",
    "Aslan",
    "Ibbaduelle",
    "Project Management",
    "Intro to C",
    "M4",
    "What is an operating system",
    "Process",
    "Interprocess Communication",
    "SPARC",
    "Philosophy of religion",
    "Parable of the Prodigal Son",
    "Nassim Nicholas Taleb",
    "Threads",
    "Two's complement",
    "GNU Debugger",
    "Binary Arithmetic",
    "Deadlocks",
    "Multiplication",
    "Bitwise",
    "Scheduling algorithms",
    "Memory (Operating Systems)",
    "Virtual memory",
    "Working Set",
    "Floating Point Numbers",
    "List of rivers by age",
    "Asteroids Epic Catalogue",
    "Constellations Epic Catalogue",
    "Basin Guardians",
    "Dragon Boat Festival",
    "Formation of the Solar System",
    "Yasaka Accord",
    "Skyfire Mining",
    "Medicine Wheel",
    "HealthyGamerGG",
    "Catgirl Nyanifesto",
    "Cosmogony",
    "Imperial Regalia",
    "Nomos",
    "Widget:Tweet",
    "InfoboxBook",
    "Infobox",
    "Learned helplessness",
    "Three causes of death",
    "Umwelt",
    "Environment of Evolutionary Adaptation",
    "Adaptive Valley",
    "Fitness landscape",
    "Gene drive",
    "Automatic theocracy",
    "Dead continent theory",
    "Dakinimakura",
    "Audio",
    "Catgirls from Space",
    "Enneagram of Imbalance",
    "Video path",
    "Eric Weinstein",
    "Artificial intelligence",
    "A secular age",
    "Imagine no religion",
    "The Physics of Wall Street",
    "Ontogeny of Information",
    "Gauge Theory of Economics",
    "YouTube",
    "Toaru clone",
    "Metal symbolism",
    "Salvage anthropology",
    "Four character idiom",
    "Bacterian Empire",
    "SASS notes",
    "Why the seas will turn into lemonade",
    "The Old System",
    "Random sentences",
    "Rhizaria",
    "Cercozoa",
    "COSC 322",
    "Ancient Egyptian Day",
    "Informational interviews",
    "Reflections on Democracy",
    "Mitra-Varuna (Indo-European)",
    "H₂weh₁-yú",
    "Indo-European smith god",
    "List of Proto-Indo-European deities",
    "Plato's Lion",
    "Behavioral sink",
    "Julie Lindahl",
    "API Access to this Wiki",
    "Chiang Mai pilgrimage",
    "The Portal Wiki",
    "The Portal Podcast",
    "Confucianism",
    "Immanuel Kant",
    "Supernatural",
    "Secular humanism",
    "Theravada",
    "Miraheze crisis",
    "Minor December Outage",
    "Social democracy",
    "Routledge",
    "Terasem Movement",
    "Assisted reproductive technology",
    "Missionary Church of Kopimism",
    "Amelia Watson",
    "Fundamentalism",
    "Vulcanization",
    "Elon Musk",
    "Anthropology of religion",
    "Shinto",
    "Climate as complex networks",
    "Dual-phase evolution",
    "Earthseed",
    "Erdős–Rényi model",
    "Euclidean algorithm",
    "Existentialism",
    "First normal form",
    "Marxism",
    "Yuval Harari",
    "Ukraine Pilgrimage",
    "Third normal form",
    "Terragen civilization",
    "Surrogate Key",
    "Shell Scripting",
    "Second normal form",
    "Proto Indo European Religion",
    "Percolation theory",
    "Childrearing",
    "Gobekli Tepe",
    "Pascal",
    "Women in the Economy",
    "Tenemu",
    "Game Locations",
    "Callisto",
    "Cythera",
    "Sohaemus of Emesa",
    "Iotapa (spouse of Sampsiceramus II)",
    "Tigranes VI of Armenia",
    "Anti-Alpha (new)",
    "Anathema",
    "Trito",
    "Anti-Lambda",
    "Slave morality",
    "Gaiad correction policy",
    "Gaiad family tree 1",
    "Gaiad family tree 2",
    "Y-DNA haplogroups by ethnic group",
    "Veritanism",
    "Bingo Province",
    "Extraterrestrial life",
    "2023 pilgrimage",
    "2024 pilgrimage",
    "Hours",
    "Shorts",
    "College notes",
    "Metameme",
    "100 subscriber special",
    "2022 Russian invasion of Ukraine",
    "200 subscriber special",
    "2014 Gamer Intro",
    "2023 Tarot reading by a vtuber",
    "2021 revelation",
    "A brief treatise of the soul",
    "2022 pilgrimage",
    "Archai",
    "Abiogenesis",
    "Archon",
    "Arctura, Queen of the Arctic Ocean",
    "Are anime girls real?",
    "Abiogenote",
    "A Systems-Oriented Theory of Everything",
    "Ark of the Covenant",
    "Absurdity (video)",
    "Abraham",
    "Abyssal Manta",
    "Ascension path",
    "Ascension",
    "Acheron",
    "Aspirational rationality",
    "Asynthesizers",
    "Atlanticus, Lord of the Atlantic Ocean",
    "Active Omega",
    "Augustine of Hippo",
    "Awakeningfromthemeaningcrisis.com",
    "Active Alpha",
    "Adapter pattern",
    "Activities",
    "Awakening from the Meaning Crisis",
    "Adolescent faustery",
    "Actually whatifalthist science is good",
    "Adolescent tripping",
    "Adolescent ascension",
    "Astrobiology",
    "Adam and Steve Short",
    "Aegir",
    "Agape",
    "Agent-Arena relationship",
    "Ahumgar",
    "Baltia",
    "Alo (mantra)",
    "Azova, the Guardian of Syvash",
    "Allele",
    "Baikalia, the Sacred Lake Goddess",
    "Alo (initiation order)",
    "Banchō Sarayashiki",
    "Alienation (video)",
    "Bardo Thodol",
    "Bayana",
    "Babastella",
    "Beneficial memeplexes",
    "Bilateria",
    "Belomara, the Arctic Enchantress",
    "Amazonia: Yara, the Water Queen",
    "Being mode",
    "Amu Darya: Amara, the Mother of Oasis",
    "Alo table",
    "Amur: Amuria, the Dragon Empress",
    "Alpha of Alphas",
    "Biological fitness",
    "Alolalia (video)",
    "Brahmaputra River",
    "Aldanus, the Guardian of the Aldan River",
    "Alearners",
    "Black Crime and anti MRA video",
    "Bleeding",
    "Books",
    "Alienation",
    "Anagogical reading",
    "Alpha Pilgrimage",
    "Alpha-Omega",
    "Bloomer short",
    "Brahmani: Brahmanis, the Divine Mother",
    "Angarina, the Siberian Nymph",
    "Bugros and Dniestra, the Twin River Deities",
    "Byzantium to Istanbul: Maintaining an ethos in Turkey",
    "Agnes Callard",
    "Angels",
    "Angst (video)",
    "Angst",
    "Antarctia, Goddess of the Southern Ocean",
    "Animal",
    "Anti-Alo (video)",
    "Anti-Alo",
    "Antisociality and Prosociality",
    "Apotheosize",
    "Cat",
    "Antisthenes",
    "Capstone",
    "Negative theology",
    "Caspia, Goddess of the Caspian Sea",
    "Catgirl",
    "Catboy",
    "Catgirl Manifesto",
    "Antibodies",
    "Catgirl Army discord server",
    "Anti-Omega (new)",
    "Catgirl short 1",
    "Anti-organizationalism",
    "Catgirl short 3",
    "Chadia",
    "Catgirl subliminal asmr transformation video",
    "Catgirls in Space",
    "Aralia",
    "Apotheotic tripping",
    "Catgirl short 2",
    "Catgirl Simulator",
    "Celestial Pillars",
    "Chameleon Seraph",
    "Catgirls have nine lives",
    "Catgirls in Space Mission Statement",
    "Chess-Opening Problem",
    "Chesapeakia, the Estuarine Goddess",
    "Charter of Ecumenical Polytheism",
    "Christmas stream",
    "China Chapter",
    "Charon (mythology)",
    "Checksum Theory of Politics",
    "Charon",
    "Church of Evolution",
    "Churchill: Churchilli, the Northern Sentinel",
    "Circling",
    "Class diagram",
    "Classical Internet Period",
    "Classical greek",
    "Climate crisis",
    "Closed practices",
    "Closed practices chapter",
    "Cognitive Fluency",
    "Cohesion",
    "Co-identification",
    "Columbina, the Pacific Ocean Guardian",
    "Collective desire synthesis",
    "Colorado: Coloadoth, the Canyon Guardian",
    "Command pattern",
    "Commandment Alpha Lambda",
    "Commandment Alpha Alpha",
    "Commandment Alpha Omega",
    "Commandment Lambda Alpha",
    "Commandment Lambda Omega",
    "Commandment Lambda Lambda",
    "Commandment Omega Lambda",
    "Commandment Omega Alpha",
    "Commodity fetishism",
    "Commandment Omega Omega",
    "Communication diagram",
    "Competence performance distinction",
    "Communicating in a crowd",
    "Confirmation bias",
    "Conjunction bias",
    "Conspirituality",
    "Congo: Mboma, the River Guardian",
    "Contemplative Practices",
    "Continuing our Climb up Mount Celeste",
    "Contrast of Rome and Asia",
    "Continuing Celeste: Unifying with Ibbaduelle",
    "Coronation",
    "Shasvant, King of Kosala",
    "Pascal Cycle",
    "Triple temple",
    "Abu",
    "Test",
    "Ddddd",
    "Ns120:Q16251",
    "Qq",
    "Trajective",
    "Trans lactation",
    "Transapients",
    "Transhumanism",
    "Transitive",
    "Triangula",
    "Transparency opacity shift",
    "Transjective",
    "Truesight",
    "Tripping",
    "Tsu, Mie",
    "Tumblr",
    "Turings",
    "Twin Nuclei Problem",
    "Ukraine War Kraut reaction",
    "Twistwood Jungles",
    "Umbrius, the River God of Ubangi",
    "UML",
    "Underseeing",
    "Umwelt Hacking",
    "Undertale Stream 2",
    "Undertale Stream 3",
    "Undertale Stream 1",
    "Undoing the Copernican Revolution",
    "Unreal Podcast 1",
    "Uniq",
    "Unix commands",
    "Unreal podcast 2",
    "Uplifting",
    "Unreal Podcast 3",
    "Uralia, the Boundary River Goddess of the Ural River",
    "Valid arguments",
    "Using AI to make vtuber thumbnails and playing Celeste",
    "Vedism",
    "Victim blaming",
    "Vistula",
    "Vision in the Ravine",
    "Videogames",
    "Virtual Engine",
    "Void",
    "Volga: Volgara, the Mother of Waters",
    "Vtubers play cards against humanity together",
    "We need to start teaching ettiquette again",
    "Wave Blade Kelp Forest",
    "Western Dvina",
    "What is ALO?",
    "What is the Ritual Music System",
    "Why debate is pointless",
    "What is an Oni (Archon)",
    "Who's getting hurt from litterboxes",
    "Why did you found a new religion",
    "Why it's good to be Schizo",
    "Why robots will need religion",
    "Why leftists fail at being dogmatic",
    "Why we need to save everyone (Nyanifesto)",
    "Will the world starve this winter we ask whatifalthist",
    "Will chatGPT end capitalism",
    "Winona, the Serene Guardian",
    "Willpower is a trap",
    "Wisdom",
    "Wonder",
    "Xenia",
    "Xenosapients",
    "Yangzi",
    "Yemo",
    "Yenisei: Yenidar, the Frost Lord",
    "Yukon: Yukonis, the Frosty Sovereign",
    "Zeroing in",
    "Zero Two Dakimakura Short",
    "Zombies in Western culture",
    "Zoosapients",
    "Zoroastrianism chapter",
    "Zoroastrianism",
    "Science Since Babylon",
    "Science, The Endless Frontier",
    "阿𠫜",
    "𠫜",
    "Absurdity",
    "Adjacency Matrix",
    "Afterlife",
    "Analysis paralysis inducers",
    "Alienators",
    "Alpha Priesthood",
    "Apotheosis",
    "Antisymmetric",
    "After me, the flood",
    "Axial religions",
]

def main():
    print(f"Total pages to process: {len(PAGES)}\n")

    print(f"Connecting to {WIKI_URL}...")
    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent='ShintoWikiBot/1.0 (immanuelle@shinto.miraheze.org)')
    site.login(USERNAME, PASSWORD)
    print("Logged in successfully\n")

    total = len(PAGES)
    success = 0
    failed = 0
    skipped = 0
    not_found = 0

    for i, page_name in enumerate(PAGES, 1):
        print(f"[{i}/{total}] {page_name}", end=" ... ", flush=True)

        try:
            page = site.pages[page_name]
            if not page.exists:
                print("NOT FOUND")
                not_found += 1
                continue

            content = page.text()

            if "[[Category:Ancient pages]]" in content:
                print("SKIPPED (already has category)")
                skipped += 1
                continue

            new_content = content.rstrip() + "\n" + CATEGORY_TO_ADD
            page.save(new_content, summary=EDIT_SUMMARY)
            print("OK")
            success += 1

        except Exception as e:
            print(f"FAILED: {e}")
            failed += 1

        time.sleep(SLEEP)

    print(f"\n{'='*50}")
    print(f"Summary: {success} edited, {skipped} skipped, {not_found} not found, {failed} failed out of {total}")

if __name__ == "__main__":
    main()
