#!/usr/bin/env python3
"""
delete_categories.py
====================
Delete specified categories from the wiki
"""
# >>> credentials / endpoint >>>
API_URL  = "https://shinto.miraheze.org/w/api.php"
USERNAME = "Immanuelle"
PASSWORD = "[REDACTED_SECRET_2]"
# <<< credentials <<<

import os, sys, time, urllib.parse, mwclient
from mwclient.errors import APIError

THROTTLE = 0.3

# ─── site login ───────────────────────────────────────────────────

def site():
    p = urllib.parse.urlparse(API_URL)
    s = mwclient.Site(p.netloc, path=p.path.rsplit("/api.php",1)[0]+"/")
    s.login(USERNAME,PASSWORD)
    return s

# Categories to delete
categories_to_delete = [
    "1,004 → 1,048 members)",
    "10 members)",
    "11 1",
    "11 4 2",
    "11 7",
    "12th-century Japanese people by occupation",
    "1873 disestablishments in Japan",
    "18th century in international relations",
    "1916 establishments",
    "1934 births",
    "1940s in Southeast Asia",
    "1968 births",
    "1991 establishments",
    "1996 introductions",
    "1996年登録の世界遺産",
    "19th century in international relations",
    "1 member)",
    "1st-millennium establishments",
    "2008 video games",
    "2022",
    "20th-century women by occupation",
    "20th century in Indonesia",
    "21st-century American philosophers",
    "21st-century women by occupation",
    "3rd-century establishments in Japan",
    "3rd-century religious buildings and structures",
    "5th-century BC Indian people by occupation",
    "5th-century BC philosophers",
    "6th-century BC Indian people by occupation",
    "6th-century BC philosophers",
    "6th-century monarchs",
    "6th-century women",
    "708 establishments",
    "7th-century beginnings",
    "8th-century women",
    "9th-century Buddhist monks",
    "AFC drafts using comment template with second parameter",
    "Abraham",
    "Abrahamic religions",
    "Add wikidata",
    "Addiction",
    "AfC submissions by date/10 November 2023",
    "AfC submissions by date/25 April 2023",
    "American Samoa templates",
    "American men centenarians",
    "Ancient Chinese states",
    "Ancient Indian philosophers",
    "Ancient Japan-Korea relations",
    "Animation terminology",
    "Annual events",
    "Archaeological Sites in Japan by Period",
    "Archaeological Sites in Japan by Prefecture",
    "Archaeological sites in japan by period",
    "Archaeological sites in japan by prefecture",
    "Architectural terminology",
    "Archival templates",
    "Articles containing Gothic-language text",
    "Articles containing Hebrew-language text",
    "Articles containing Icelandic-language text",
    "Articles containing Koinē Greek-language text",
    "Articles containing Middle English (1100-1500)-language text",
    "Articles containing Old Spanish-language text",
    "Articles containing Russian-language text",
    "Articles containing Spanish-language text",
    "Articles containing Turkish-language text",
    "Articles containing potentially dated statements from 2016",
    "Articles containing potentially dated statements from 2018",
    "Articles containing potentially dated statements from 2019",
    "Articles containing potentially dated statements from January 2024",
    "Articles containing potentially dated statements from May 2014",
    "Articles containing potentially dated statements from November 2015",
    "Articles having different image on Wikidata and Wikipedia",
    "Articles having same image on Wikidata and Wikipedia",
    "Articles incorporating text from the 1913 Catholic Encyclopedia with Wikisource reference",
    "Articles incorporating text from the 1913 Catholic Encyclopedia without Wikisource reference",
    "Articles lacking in-text citations from March 2013",
    "Articles lacking in-text citations from March 2023",
    "Articles lacking in-text citations from May 27, 2019",
    "Articles lacking reliable references from March 2021",
    "Articles lacking sources from August 2017",
    "Articles lacking sources from January 2010",
    "Articles needing additional references from May 2012",
    "Articles needing additional references from November 2019",
    "Articles needing cleanup",
    "Articles requiring reliable medical sources",
    "Articles with Curlie links",
    "Articles with dead external links from February 2018",
    "Articles with dead external links from May 2019",
    "Articles with dead external links from May 2020",
    "Articles with dead external links from September 2018",
    "Articles with disputed statements from April 2023",
    "Articles with incorrect citation syntax",
    "Articles with unsourced statements from August 4, 2014 (Monday) 15:41 (UTC)",
    "Articles with unsourced statements from January 2013",
    "Articles with unsourced statements from January 2023",
    "Articles with unsourced statements from March 2010",
    "Ascension Island templates",
    "Asian Women by Century",
    "Astronomical coordinate systems",
    "Astronomical sub-disciplines",
    "Automatic wikipedia redirects 1",
    "Bad drafts by Immanuelle",
    "Bambooworking",
    "Bays of Chūgoku Region",
    "Behavioral addiction",
    "Biota of Japan",
    "Bodies of water of Yamanishi Prefecture",
    "Books about religion",
    "Booster shots",
    "Brain disorders",
    "Brewed Alcoholic Beverages",
    "Buddhist enumerations of 4",
    "Buddhist miracles",
    "Buildings and structures by construction material",
    "Buildings and structures completed in 1908",
    "Buildings and structures completed in the 12th century BC",
    "Buildings in Awa City",
    "Buildings in Chigasaki City",
    "Buildings in Fukushima Prefecture by Municipality",
    "Buildings in Hanno City",
    "Buildings in Higashinari-ku, Osaka",
    "Buildings in Higashiyama Ward",
    "Buildings in Itano Town",
    "Buildings in Itoshima City",
    "Buildings in Kamiita Town",
    "Buildings in Kanagawa Ward",
    "Buildings in Kokura-Kita Ward",
    "Buildings in Komatsushima, Tokushima",
    "Buildings in Nishiwaki",
    "Buildings in Suminoe-ku, Osaka",
    "Buildings in Tanba, Hyogo",
    "Buildings in Tanbasasayama",
    "Buildings in Toyooka",
    "Buildings in Yoshinogawa City",
    "Bullet hell video games",
    "Business economics",
    "CS1 Latin-language sources (la)",
    "CS1 Polish-language sources (pl)",
    "CS1 Ukrainian-language sources (uk)",
    "CS1 maint: unflagged free DOI",
    "California templates",
    "Categories by year",
    "Characters in the Odyssey",
    "Chinese-language books",
    "Christian new religious movements",
    "Civil awards and decorations of Poland",
    "Cleanup tagged articles with a reason field",
    "Cognition",
    "Colorado templates",
    "Commercial Facilities in Kinki Region",
    "Commercial Facilities in Tōkai Region",
    "Commons category link from Wikidata",
    "Computational fields of study",
    "Concepts in epistemology",
    "Confucian schools of thought",
    "Country data templates of Albania",
    "Country data templates of Algeria",
    "Country data templates of Andorra",
    "Country data templates of Angola",
    "Country data templates of Antarctica",
    "Country data templates of Antigua and Barbuda",
    "Country data templates of Argentina",
    "Country data templates of Armenia",
    "Country data templates of Australia",
    "Country data templates of Austria",
    "Country data templates of Azerbaijan",
    "Country data templates of Bahrain",
    "Country data templates of Bangladesh",
    "Country data templates of Barbados",
    "Country data templates of Belarus",
    "Country data templates of Belgium",
    "Country data templates of Belize",
    "Country data templates of Benin",
    "Country data templates of Bhutan",
    "Country data templates of Bolivia",
    "Country data templates of Bosnia and Herzegovina",
    "Country data templates of Botswana",
    "Country data templates of Brazil",
    "Country data templates of Brunei",
    "Country data templates of Burkina Faso",
    "Country data templates of Burundi",
    "Country data templates of Cambodia",
    "Country data templates of Cameroon",
    "Country data templates of Canada",
    "Country data templates of Cape Verde",
    "Country data templates of Chad",
    "Country data templates of Chile",
    "Country data templates of Colombia",
    "Country data templates of Costa Rica",
    "Country data templates of Croatia",
    "Country data templates of Cuba",
    "Country data templates of Denmark",
    "Country data templates of Djibouti",
    "Country data templates of Dominica",
    "Country data templates of Ecuador",
    "Country data templates of Egypt",
    "Country data templates of El Salvador",
    "Country data templates of Equatorial Guinea",
    "Country data templates of Eritrea",
    "Country data templates of Estonia",
    "Country data templates of Eswatini",
    "Country data templates of Fiji",
    "Country data templates of Gabon",
    "Country data templates of Georgia",
    "Country data templates of Ghana",
    "Country data templates of Greece",
    "Country data templates of Grenada",
    "Country data templates of Guatemala",
    "Country data templates of Guinea",
    "Country data templates of Guinea-Bissau",
    "Country data templates of Guyana",
    "Country data templates of Haiti",
    "Country data templates of Honduras",
    "Country data templates of Hungary",
    "Country data templates of Iceland",
    "Country data templates of India",
    "Country data templates of Indonesia",
    "Country data templates of Iraq",
    "Country data templates of Ivory Coast",
    "Country data templates of Jamaica",
    "Country data templates of Jordan",
    "Country data templates of Kazakhstan",
    "Country data templates of Kenya",
    "Country data templates of continents",
    "Country data templates of dependent territories of the United Kingdom",
    "Country data templates of governments",
    "Country data templates of international organizations",
    "Country data templates of subdivisions of Canada",
    "Country data templates of subdivisions of Germany",
    "Country data templates of subdivisions of Taiwan",
    "Country data templates of subdivisions of Ukraine",
    "Country data templates of subdivisions of the Kingdom of Denmark",
    "Country data templates of subdivisions of the Netherlands",
    "Country data templates of subdivisions of the Soviet Union",
    "Country data templates of subdivisions of the United Kingdom",
    "Country data templates of subdivisions of the United States",
    "Country data templates of the Bahamas",
    "Country data templates of the Central African Republic",
    "Country data templates of the Comoros",
    "Country data templates of the Czech Republic",
    "Country data templates of the Democratic Republic of the Congo",
    "Country data templates of the Dominican Republic",
    "Country data templates of the Gambia",
    "Country data templates of the Netherlands",
    "Culture of Europe",
    "Cybernetics",
    "Dai-gensui",
    "Date redirects to be deleted",
    "Dates to be revision",
    "Decades in Indonesia",
    "Discrimination",
    "Districts of Kii Province",
    "Domains in Higo Province",
    "Drafts",
    "Dynamical systems",
    "Ecology of Practices",
    "Economics",
    "Eighteen Matsudaira Families",
    "Emperor Kōmei",
    "Encyclopedias by language",
    "English-language books",
    "EngvarB from January 2014",
    "Enumerations of 15",
    "Epistemologists",
    "Erroneous transclusions of Template:JS-Test/doc",
    "Erroneous transclusions of Template:LangSwitch/doc",
    "Ethnic religion",
    "European culture",
    "European gods",
    "Events and Festivals of Gunma Prefecture",
    "Events and Festivals of Kōchi Prefecture",
    "Events and Festivals of Nara Prefecture",
    "Events and Festivals of Tottori Prefecture",
    "Events and Festivals of Yamagata Prefecture",
    "Events in Kagawa prefecture",
    "Events in Niigata prefecture",
    "Events in Okayama prefecture",
    "Evolutionism",
    "Evolutionism Wiki",
    "Evolutionist Online Infrastructure",
    "Falkland Islands templates",
    "Fix the bottom thing",
    "Floating Z headings",
    "Flora of Asia",
    "Flora of Eastern Asia",
    "Foreign language page not connected to wikidata",
    "Foreign relations of the Ming dynasty",
    "Former Higher Education Institutions in Japan",
    "Former Prefectural Shrines in Yamagata Prefecture",
    "Former Prefectural Shrines in Yamanashi Prefecture",
    "Former Unranked Shrines in Tokushima Prefecture",
    "Gaiad",
    "Genetics",
    "Geography books",
    "Geography of Aomori Prefecture by Municipality",
    "Gibraltar templates",
    "Gnosticism",
    "Gospel",
    "Government of Taiwan",
    "Group processes",
    "Gruppe von Gottheiten",
    "Guam templates",
    "Guernsey templates",
    "Has wikidata",
    "Hiroshima Prefecture designated important cultural property",
    "Historic monuments of ancient Nara",
    "Historic monuments of nara",
    "History of Aichi Prefecture by Municipality",
    "History of India by period",
    "History of Komatsushima",
    "History of Setouchi",
    "History of Suminoe-ku, Osaka",
    "History of Tenri City",
    "History of aichi prefecture by municipality",
    "History of the foreign relations of Russia",
    "Holiday categories",
    "Honorary Titles",
    "Horror literature",
    "Hospitals in Miyazaki Prefecture",
    "Hospitals in Miyazaki prefecture",
    "Human evolution",
    "ISO basic Latin letters",
    "Image Requests for Mima City",
    "Image Requests for Miyoshi City",
    "Image Requests for Naruto",
    "Image Requests for Tokushima City",
    "Image Requests for Yoshinogawa City",
    "Image requests in Anan City",
    "Image requests in Awa City",
    "Imperial Consorts by Century",
    "Ina Branch of the Minamoto Clan",
    "Indian philosophers by century",
    "Isle of Man templates",
    "Japanese Timber",
    "Japanese poetry collections",
    "Jersey templates",
    "Jews and Judaism",
    "Judaism",
    "Komatsushima, Tokushima Image Requests",
    "LGBTQ history in Greece",
    "LGBTQ themes in mythology",
    "Latter Day Saint terms",
    "Leisure",
    "Links on Category",
    "Martial Art Styles Founded Since the Meiji Era",
    "Medical Institutions of the National Hospital Organization",
    "Medical condition not in Wikidata",
    "Meta-attention",
    "Metal Products",
    "Military history of China",
    "Military of China",
    "Mindfulness (Buddhism)",
    "Mind–body interventions",
    "Modified Gregorian calendars",
    "Moral philosophers",
    "Morality",
    "Moses",
    "Municipal History of Awa",
    "Municipal History of Itano",
    "Municipal History of Kamiita",
    "Municipal History of Nishiwaki",
    "Municipal History of Yoshinogawa",
    "National Treasures of Japan (paintings)",
    "National capitals",
    "National questions",
    "Nikaya schools",
    "Ninefold vaccine",
    "Nth day holidays",
    "Observances set by the traditional Japanese calendar",
    "Orders of chivalry of Norway",
    "Orders of chivalry of Poland",
    "Paes with no wikidata",
    "Pages including recorded pronunciations",
    "Pages to be overwritten 2",
    "Pages to be overwritten 2 book content",
    "Pages using infobox bridge with empty coordinates parameter",
    "Pages using infobox hospital with unknown parameters",
    "Pages using small with an empty input parameter",
    "Pages using small with unknown parameters",
    "Pages with link uncertainty",
    "Pages with no Wikidata",
    "Pages without english wikidata name",
    "Pali words and phrases",
    "People by city",
    "People from Christian Schools",
    "People related to Jōdo Shinshū",
    "Philosophers of ethics and morality",
    "Philosophers of science",
    "Plum Village Tradition",
    "Political charters",
    "Politics of the Russian Empire",
    "Populated places established in 2010",
    "Prefectural Traditional Craft Items",
    "Private law",
    "Professional ethics",
    "Psychotherapy",
    "Qq-Disambiguation pages with given-name-holder lists-qq",
    "Qq-Disambiguation pages with surname-holder lists-qq",
    "Qq-category-qq",
    "Qq 1",
    "Qq 4",
    "Qq 8",
    "Qqq",
    "Qqqq",
    "Qqqqqqqq",
    "Qqqqqqqqq",
    "Qqqqqqqqqq",
    "Qqqqqqqqqqq",
    "Qqqqqqqqqqqq",
    "Recipients of orders, decorations, and medals of Thailand",
    "Registered Tangible Cultural Property of Japan in Hiroshima prefecture",
    "Religion articles needing expert attention",
    "Religion in ancient Israel and Judah",
    "Remembering",
    "Removed translated page templates",
    "Scallop-shaped kofun",
    "Schools in Kanagawa Prefecture",
    "Serada Clan",
    "Shibuya Clan",
    "Shinnaiden",
    "Shinto Wiki",
    "Shinto organizations",
    "Social critics",
    "Social networks",
    "Sociological terminology",
    "Sociological theories",
    "Son-sha in Fukushima Prefecture",
    "Son-sha in Tokushima Prefecture",
    "South Asia",
    "Southern Hokkaido Region",
    "Spiralling",
    "Sthaviravāda",
    "Streets by city",
    "Sub-shrines of Atsuta Shrine",
    "Substance-related disorders",
    "Sun",
    "Surnames by origin",
    "Tamba Province",
    "Tanba, Hyōgo",
    "Tanba-Sasayama",
    "Taoist philosophy",
    "Templates for the Japanese Calendar Logic Fix Attempt",
    "The Pride",
    "Three Scrolls",
    "Timber Construction",
    "Tourist accommodations in Japan",
    "Tourist attractions in Asia",
    "Transaction processing",
    "Translated page but missing wikidata",
    "Transport in Aichi Prefecture",
    "Transport in Hiroshima",
    "Transport in Japan in the Edo period",
    "Transport in Kanagawa Prefecture",
    "Transport in Kyoto Prefecture",
    "Transport in Shiga Prefecture",
    "Transport in Shizuoka Prefecture",
    "Transportation history of Chubu region",
    "Tributary States",
    "Types of tourism",
    "Undo 2",
    "University of California, Berkeley College of Letters and Science faculty",
    "University of the Sacred Heart, Tokyo",
    "University of the Sacred Heart (Japan) alumni",
    "Unused Categories",
    "Use American English from March 2020",
    "Use dmy dates from January 2014",
    "Use dmy dates from June 2024",
    "Use dmy dates from May 2019",
    "Use mdy dates from August 2013",
    "Use mdy dates from May 2017",
    "Valley of the Kings",
    "Various religions",
    "Video games developed in Japan",
    "Vowel letters",
    "Wajō Sect",
    "War in popular culture",
    "Wars of succession",
    "Wholesome factors in Buddhism",
    "WikiProject Articles for creation",
    "Wikipedia articles in need of updating from January 2023",
    "Wikipedia articles needing clarification from April 2023",
    "Wikipedia articles needing clarification from December 2015",
    "Wikipedia articles needing clarification from September 2021",
    "Wikipedia formatting and function templates",
    "Wikipedia pages needing cleanup",
    "Wooden architecture",
    "Works Featuring Princes",
    "Works by Protagonist Type",
    "World Heritage Sites A row",
    "World Heritage Sites by continent",
    "World Heritage Sites by religion",
    "Year categories to be fixed",
    "Year of Birth and Death unknown",
    "テンプレートを正しく使用していないページ",
    "条件文",
]

# ─── main loop ────────────────────────────────────────────────────

def main():
    s = site()
    print("Logged in\n")

    count = 0
    for cat_name in categories_to_delete:
        try:
            print(f"Deleting: {cat_name}")
            pg = s.pages[f"Category:{cat_name}"]

            if not pg.exists:
                print(f"  [SKIP] category does not exist")
                continue

            try:
                pg.delete(reason="Bot: Delete unused category")
                count += 1
                print(f"  [DELETED]")
            except APIError as e:
                print(f"  [FAILED] {e.code}")

            time.sleep(THROTTLE)

        except Exception as e:
            print(f"  [ERROR] {str(e)}")

    print(f"\nTotal categories deleted: {count}")

if __name__=='__main__':
    main()
