#!/usr/bin/env python3
"""
Process duplicated_content/*.wiki files to remove duplicated sections.

Handles these patterns:
1. Files with "== Japanese Wikipedia content ==" / "==End Japanese==" - strip Japanese section
2. Files with "==merged content==" - two Wikidata-generated copies; keep first
3. Files with "== AUTOGENERATED CONTENT FROM WIKIDATA ==" + "== Accidentally Overwritten Content ==" - restore original content
4. Files with "== AUTOGENERATED CONTENT FROM WIKIDATA ==" only - check if it IS the stub (dedupe categories)
5. Files with "==Merged second translation==" - two English translations (skip - needs manual merge)
"""

import os
import re
import sys

TARGET_DIR = "/home/user/shintowiki-scripts/duplicated_content"
DUP_CATEGORY = "[[Category:Pages with duplicated content]]"

def dedup_categories(text):
    """Remove duplicate category lines, keeping first occurrence."""
    lines = text.split('\n')
    seen_cats = {}
    result = []
    for line in lines:
        stripped = line.strip()
        # Normalize category for dedup check
        cat_match = re.match(r'^\[\[Category:([^\]|]+)', stripped, re.IGNORECASE)
        if cat_match:
            cat_key = cat_match.group(1).strip().lower()
            if cat_key in seen_cats:
                continue  # skip duplicate
            seen_cats[cat_key] = True
        result.append(line)
    return '\n'.join(result)


def process_file(filepath):
    """Process a single .wiki file. Returns (new_text, action) or (None, 'skip')."""
    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()
    
    if DUP_CATEGORY not in text:
        return None, 'already_clean'
    
    original = text
    action = None
    
    # -----------------------------------------------------------------------
    # Pattern 1: "== Japanese Wikipedia content ==" section
    # Strip from "== Japanese Wikipedia content ==" to "==End Japanese==" (inclusive)
    # or to end of file if no End Japanese marker.
    # -----------------------------------------------------------------------
    if '== Japanese Wikipedia content ==' in text:
        # Find the section and strip it
        idx = text.find('== Japanese Wikipedia content ==')
        end_idx = text.find('==End Japanese==', idx)
        if end_idx != -1:
            # Remove from start of this section to end of ==End Japanese==
            # Also strip the newline before/after
            end_idx += len('==End Japanese==')
            text = text[:idx].rstrip() + '\n' + text[end_idx:].lstrip('\n')
        else:
            # Remove to end of file (but keep any categories after it)
            # Look for category lines after the Japanese section
            remaining = text[idx:]
            cat_lines = []
            for line in remaining.split('\n'):
                stripped = line.strip()
                if stripped.startswith('[[Category:') or stripped.startswith('[[JA:'):
                    cat_lines.append(line)
            text = text[:idx].rstrip()
            if cat_lines:
                text += '\n' + '\n'.join(cat_lines) + '\n'
        action = 'removed_japanese_section'
    
    # -----------------------------------------------------------------------
    # Pattern 2: "==merged content==" - two Wikidata-generated copies
    # Keep everything before "==merged content==", remove from there on.
    # But preserve any category lines from the second copy.
    # -----------------------------------------------------------------------
    if '==merged content==' in text:
        idx = text.find('==merged content==')
        before = text[:idx].rstrip()
        after = text[idx + len('==merged content=='):]
        # Extract categories from the merged section to preserve unique ones
        cat_lines = []
        for line in after.split('\n'):
            stripped = line.strip()
            if stripped.startswith('[[Category:') and stripped != DUP_CATEGORY:
                cat_lines.append(line)
        # Reconstruct: keep before, add any new category lines
        text = before + '\n'
        if cat_lines:
            text += '\n'.join(cat_lines) + '\n'
        action = 'removed_merged_content'
    
    # -----------------------------------------------------------------------
    # Pattern 3: "== AUTOGENERATED CONTENT FROM WIKIDATA ==" with
    # "== Accidentally Overwritten Content ==" - restore original article
    # -----------------------------------------------------------------------
    if '== AUTOGENERATED CONTENT FROM WIKIDATA ==' in text and \
       '== Accidentally Overwritten Content ==' in text:
        auto_idx = text.find('== AUTOGENERATED CONTENT FROM WIKIDATA ==')
        overwrite_idx = text.find('== Accidentally Overwritten Content ==')
        
        if overwrite_idx > auto_idx:
            # The original article is BEFORE the autogenerated section
            # The "Accidentally Overwritten Content" is a duplicate
            # Keep: text before autogenerated + any wikidata link + categories
            before_auto = text[:auto_idx].rstrip()
            after_all = text[overwrite_idx + len('== Accidentally Overwritten Content =='):]
            
            # Check if there are multiple "Accidentally Overwritten Content" sections
            while '== Accidentally Overwritten Content ==' in after_all:
                next_idx = after_all.find('== Accidentally Overwritten Content ==')
                after_all = after_all[next_idx + len('== Accidentally Overwritten Content =='):]
            
            # Extract wikidata link from autogenerated section
            auto_section = text[auto_idx:overwrite_idx]
            wikidata_link = None
            for line in auto_section.split('\n'):
                if line.strip().startswith('{{wikidata link|'):
                    wikidata_link = line.strip()
                    break
            
            # Extract categories from the tail (after_all)
            cat_lines = []
            notes_section = []
            in_notes = False
            for line in after_all.split('\n'):
                stripped = line.strip()
                if stripped == '==Notes==' or stripped == '== Notes ==':
                    in_notes = True
                    notes_section.append(line)
                elif in_notes:
                    notes_section.append(line)
                    if stripped.startswith('<references') or stripped == '':
                        in_notes = stripped != ''
                elif stripped.startswith('[[Category:') and stripped != DUP_CATEGORY:
                    cat_lines.append(line)
            
            # Check if wikidata link already in before_auto
            if wikidata_link and wikidata_link not in before_auto:
                before_auto += '\n' + wikidata_link
            
            text = before_auto + '\n'
            if notes_section:
                text += '\n'.join(notes_section) + '\n'
            if cat_lines:
                text += '\n'.join(cat_lines) + '\n'
            action = 'restored_from_overwritten'
    
    # -----------------------------------------------------------------------
    # Pattern 4: "== AUTOGENERATED CONTENT FROM WIKIDATA ==" only
    # (no Accidentally Overwritten Content) - just dedup and remove dup category
    # -----------------------------------------------------------------------
    elif '== AUTOGENERATED CONTENT FROM WIKIDATA ==' in text:
        # The file IS the autogenerated stub. Just dedup categories.
        action = 'dedup_autogenerated'
    
    # -----------------------------------------------------------------------
    # Final: Remove the duplicated content category and dedup categories
    # -----------------------------------------------------------------------
    # Remove DUP_CATEGORY
    text = text.replace(DUP_CATEGORY + '\n', '')
    text = text.replace('\n' + DUP_CATEGORY, '')
    text = text.replace(DUP_CATEGORY, '')
    
    # Dedup remaining categories
    text = dedup_categories(text)
    
    # Clean up excessive blank lines (max 2 consecutive)
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    if DUP_CATEGORY in text:
        return None, f'ERROR: still contains dup category after processing'
    
    if text == original:
        return None, 'no_change'
    
    return text, action or 'cleaned'


def main():
    files = sorted(f for f in os.listdir(TARGET_DIR) if f.endswith('.wiki'))
    
    results = {'already_clean': 0, 'removed_japanese_section': 0, 
               'removed_merged_content': 0, 'restored_from_overwritten': 0,
               'dedup_autogenerated': 0, 'cleaned': 0, 'no_change': 0,
               'skipped_second_translation': 0, 'error': []}
    
    for fname in files:
        fpath = os.path.join(TARGET_DIR, fname)
        
        # Skip files with "==Merged second translation==" - need manual merge
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        if '==Merged second translation==' in content:
            results['skipped_second_translation'] += 1
            continue
        
        new_text, action = process_file(fpath)
        
        if action.startswith('ERROR'):
            results['error'].append(f"{fname}: {action}")
            continue
        
        if action in ('already_clean', 'no_change'):
            results[action] = results.get(action, 0) + 1
            continue
        
        if new_text is not None:
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(new_text)
            results[action] = results.get(action, 0) + 1
            print(f"  [{action}] {fname}")
        else:
            results['no_change'] = results.get('no_change', 0) + 1
    
    print("\n=== Summary ===")
    for k, v in results.items():
        if k != 'error':
            print(f"  {k}: {v}")
    if results['error']:
        print(f"  errors ({len(results['error'])}):")
        for e in results['error']:
            print(f"    {e}")

if __name__ == '__main__':
    main()
