#!/usr/bin/env python3
"""
recreate_categories_wave3.py
============================
Recreates category pages (third wave) after wiki restoration.
Each category page will contain only: [[Category:Third wave of autocreated categories after wiki restoration]]
"""

import mwclient
import sys
import time

# Fix Unicode encoding issues on Windows
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Configuration
WIKI_URL = 'shinto.miraheze.org'
WIKI_PATH = '/w/'
USERNAME = 'Immanuelle'
PASSWORD = '[REDACTED_SECRET_2]'
SLEEP = 1.5  # seconds between edits

# Content for each category page
CATEGORY_CONTENT = "[[Category:Third wave of autocreated categories after wiki restoration]]"

# Categories to recreate
CATEGORIES = [
    "Second wave of autocreated categories after wiki restoration",
    "三島・大山祇信仰",
    "加茂神社",
    "下総国の式内社",
    "Articles with dummy references",
    "Former redirect categories falsely tagged",
    "三宅村の建築物",
    "三宅村の歴史",
    "亀岡市の建築物",
    "亀岡市の歴史",
    "岐阜県内の市町村指定有形文化財",
    "諏訪神社",
    "京都府の旧府社",
    "備前国の式内社",
    "岡山市の神社",
    "御所市の建築物",
    "御所市の歴史",
    "Japanese titles",
    "三輪神社",
    "伊勢市の神社",
    "千葉県の旧県社",
    "千葉県の旧郷社",
    "南相馬市の建築物",
    "南相馬市の歴史",
    "大和郡山市の建築物",
    "大和郡山市の歴史",
    "岡山市北区の建築物",
    "岡山市北区の歴史",
    "愛媛県の旧県社",
    "春日移し",
    "松崎町の歴史",
    "清水区の建築物",
    "清水区の歴史",
    "鈴鹿市の建築物",
    "鈴鹿市の歴史",
    "Articles lacking sources from 2020年5月",
    "丹波湖伝説",
    "大垣市の建築物",
    "大垣市の歴史",
    "天理市の建築物",
    "天理市の歴史",
    "安房国の式内社",
    "官幣小社",
    "富山市の神社",
    "対馬島の式内社",
    "対馬市の建築物",
    "対馬市の歴史",
    "小槻氏",
    "岡山県の旧村社",
    "島根県指定有形文化財",
    "桜井市の建築物",
    "桜井市の歴史",
    "渡来人",
    "物部氏",
    "福井県の旧県社",
    "秦氏",
    "西伊豆町の建築物",
    "西伊豆町の歴史",
    "近江八幡市の建築物",
    "近江八幡市の歴史",
    "長野県の旧村社",
    "香川県の旧郷社",
    "Articles with unsourced statements from December 2025",
    "Category wikidata stuff",
    "上里町の建築物",
    "上里町の歴史",
    "丹後国の式内社",
    "伊勢国",
    "千葉県の旧村社",
    "吉野町の建築物",
    "吉野町の歴史",
    "吹田市の建築物",
    "吹田市の歴史",
    "周防国の式内社",
    "和歌山県の旧県社",
    "坂出市の建築物",
    "坂出市の歴史",
    "堺市南区の建築物",
    "堺市南区の歴史",
    "大田市の建築物",
    "大田市の歴史",
    "守山市の建築物",
    "守山市の歴史",
    "官幣中社",
    "富田林市の建築物",
    "富田林市の歴史",
    "岡山県の旧郷社",
    "川西市の建築物",
    "川西市の歴史",
    "扶桑町の建築物",
    "扶桑町の歴史",
    "日本の食文化",
    "桑名市の建築物",
    "桑名市の歴史",
    "桜川市の建築物",
    "桜川市の歴史",
    "湖南市の建築物",
    "湖南市の歴史",
    "磐城平藩",
    "群馬県の旧村社",
    "群馬県内の市町村指定有形文化財",
    "賀茂朝臣氏",
    "賀茂県主氏",
    "越中国",
    "霧島市の建築物",
    "霧島市の歴史",
    "養老町の建築物",
    "養老町の歴史",
    "香芝市の建築物",
    "香芝市の歴史",
    "高橋氏",
    "鹿児島県の旧県社",
    "Articles lacking in-text citations from August 2020",
    "Articles lacking sources from 2019年12月",
    "Articles lacking sources from 2020年3月",
    "Articles lacking sources from 2024年6月",
    "Articles lacking sources from 2025年1月",
    "えびす神社",
    "さいたま市の神社",
    "ちば遺産100選",
    "オートバイ",
    "下総国",
    "京丹後市の建築物",
    "京丹後市の歴史",
    "京田辺市の建築物",
    "京田辺市の歴史",
    "京都市北区の建築物",
    "京都市北区の歴史",
    "今治市の建築物",
    "今治市の歴史",
    "伊賀国",
    "但馬国",
    "八坂神社",
    "八尾 (八尾市)",
    "千葉市の神社",
    "千葉市中央区の建築物",
    "千葉市中央区の歴史",
    "南国市の建築物",
    "南国市の歴史",
    "南房総市の建築物",
    "南房総市の歴史",
    "吉野・大峯",
    "名古屋市緑区の建築物",
    "名古屋市緑区の歴史",
    "名張市の建築物",
    "名張市の歴史",
    "周防国",
    "城陽市の建築物",
    "城陽市の歴史",
    "埼玉県の氷川神社",
    "埼玉県の重要文化財",
    "多賀神社",
    "大社造",
    "太秦",
    "奈良県内の市町村指定有形文化財",
    "宍粟市の建築物",
    "宍粟市の歴史",
    "宗像市の建築物",
    "宗像市の歴史",
    "宝塚市の建築物",
    "宝塚市の歴史",
    "富加町の建築物",
    "富加町の歴史",
    "富山県の旧村社",
    "富山県の旧郷社",
    "富山県の重要文化財",
    "富谷市の建築物",
    "富谷市の歴史",
    "小松島市の建築物",
    "小松島市の歴史",
    "小松市の建築物",
    "小松市の歴史",
    "小牧市の建築物",
    "小牧市の歴史",
    "小野妹子",
    "尼崎市の建築物",
    "尼崎市の歴史",
    "山口県の旧県社",
    "山口県の重要文化財",
    "山梨市の建築物",
    "山梨市の歴史",
    "岡山市の重要文化財",
    "岸和田市の建築物",
    "岸和田市の歴史",
    "常陸国",
    "常陸太田市の建築物",
    "常陸太田市の歴史",
    "弟橘媛",
    "徳島県の重要文化財",
    "愛媛県指定有形文化財",
    "敦賀市の建築物",
    "敦賀市の歴史",
    "日本の国宝 (考古・歴史資料)",
    "明石市の建築物",
    "明石市の歴史",
    "木津川市の建築物",
    "木津川市の歴史",
    "杉山神社",
    "東京都の旧村社",
    "東京都府中市の建築物",
    "東京都府中市の歴史",
    "松本市の歴史",
    "松阪市の建築物",
    "松阪市の歴史",
    "柏崎市の建築物",
    "柏崎市の歴史",
    "栃木市の建築物",
    "栃木市の歴史",
    "栃木県の重要文化財",
    "栗東市の建築物",
    "栗東市の歴史",
    "横浜市の神社",
    "武内宿禰",
    "水口藩",
    "江南市の建築物",
    "江南市の歴史",
    "河津町の建築物",
    "河津町の歴史",
    "泉北ニュータウン",
    "灘区の建築物",
    "灘区の歴史",
    "熊谷市の建築物",
    "熊谷市の歴史",
    "白鬚神社",
    "益田市の建築物",
    "益田市の歴史",
    "石井町の建築物",
    "石井町の歴史",
    "石川県の重要文化財",
    "神奈川県の旧県社",
    "福岡県指定有形文化財",
    "秋田県の旧郷社",
    "総社",
    "美濃加茂市の建築物",
    "美濃加茂市の歴史",
    "膳氏",
    "船橋市の神社",
    "茨城県の重要文化財",
    "茨城県指定有形文化財",
    "葛城氏",
    "藤原氏",
    "藤沢市の神社",
    "蘇我氏",
    "西ノ島町の建築物",
    "近江八幡市の重要文化財",
    "重要有形民俗文化財",
    "隠岐の島町の建築物",
    "養父市の建築物",
    "養父市の歴史",
    "館山市の建築物",
    "館山市の歴史",
    "香川県の重要文化財",
    "高岡市の神社",
    "鳴海町",
    "鳴門市の建築物",
    "鳴門市の歴史",
    "鹿児島県の重要文化財",
    "100 Scenic Spots of Ibaraki",
    "1873年竣工の建築物",
    "2014年竣工の日本の建築物",
    "2015年竣工の日本の建築物",
    "2016年竣工の日本の建築物",
    "645年の日本",
    "Architecture of Kitaibaraki City",
    "Architecture of Naka City",
    "Architecture of Yurihama Town",
    "Architecture of Ōyama Town",
    "Articles covered by WikiProject Wikify from February 2018",
    "Articles lacking in-text citations from 2018年9月",
    "Articles lacking sources from 2010年12月",
    "Articles lacking sources from 2011年2月",
    "Articles lacking sources from 2014年10月26日 (日) 04:25 (UTC)",
    "Articles lacking sources from 2014年10月26日 (日) 04:27 (UTC)",
    "Articles lacking sources from 2014年10月26日 (日) 11:38 (UTC)",
    "Articles lacking sources from 2014年10月27日 (月) 11:43 (UTC)",
    "Articles lacking sources from 2014年10月27日 (月) 11:44 (UTC)",
    "Articles lacking sources from 2014年10月27日 (月) 12:49 (UTC)",
    "Articles lacking sources from 2014年10月27日 (月) 12:50 (UTC)",
    "Articles lacking sources from 2014年7月",
    "Articles lacking sources from 2014年8月19日 (火) 16:45 (UTC)",
    "Articles lacking sources from 2015年1月11日 (日) 13:17 (UTC)",
    "Articles lacking sources from 2015年3月19日 (木) 14:52 (UTC)",
    "Articles lacking sources from 2015年6月20日 (土) 04:19 (UTC)",
    "Articles lacking sources from 2015年9月13日 (日) 02:25 (UTC)",
    "Articles lacking sources from 2016-10",
    "Articles lacking sources from 2016-12-18",
    "Articles lacking sources from 2016年6月13日 (月) 20:08 (UTC)",
    "Articles lacking sources from 2016年6月14日 (火) 12:41 (UTC)",
    "Articles lacking sources from 2016年6月14日 (火) 12:46 (UTC)",
    "Articles lacking sources from 2016年6月14日 (火) 12:49 (UTC)",
    "Articles lacking sources from 2016年7月16日 (土) 07:40 (UTC)",
    "Articles lacking sources from 2017-12",
    "Articles lacking sources from 2017年3月3日 (金) 23:02 (UTC)",
    "Articles lacking sources from 2018年3月18日 (日) 10:18 (UTC)",
    "Articles lacking sources from 2018年5月16日 (水) 10:15 (UTC)",
    "Articles lacking sources from 2019年10月",
    "Articles lacking sources from 2019年7月10日 (水) 03:29 (UTC)",
    "Articles lacking sources from 2020年2月",
    "Articles lacking sources from 2020年7月",
    "Articles lacking sources from 2022年11月",
    "Articles lacking sources from 2022年1月6日 (木) 13:02 (UTC)",
    "Articles lacking sources from 2022年2月",
    "Articles lacking sources from 2023年10月",
    "Articles lacking sources from 2023年1月1日 (日) 13:23 (UTC)",
    "Articles lacking sources from 2025-06",
    "Articles lacking sources from 2025年10月",
    "Articles lacking sources from 2025年5月",
    "Articles lacking sources from 2025年9月",
    "Articles lacking sources from October 2024",
    "Articles needing additional references from August 14, 2014 (Thu) 15:39 (UTC)",
    "Articles needing additional references from October 26, 2014 (Sun) 04:17 (UTC)",
    "Articles that may contain original research from December 28, 2016 (Wed) 05:25 (UTC)",
    "Articles to be expanded from 2020年8月",
    "Articles to be expanded from September 2019",
    "Articles with empty sections from 2020年8月",
    "Articles with empty sections from September 2019",
    "Articles with unsourced statements from 2019-09-23",
    "Articles with unsourced statements from 2026-01",
    "Articles with unsourced statements from April 2020",
    "Articles with unsourced statements from August 2020",
    "Articles with unsourced statements from December 26, 2022 (Mon) 03:14 (UTC)",
    "Articles with unsourced statements from February 2, 2017 (Thu) 04:57 (UTC)",
    "Articles with unsourced statements from January 2012",
    "Articles with unsourced statements from January 2015",
    "Articles with unsourced statements from January 2026",
    "Articles with unsourced statements from March 15, 2015 (Sun) 08:20 (UTC)",
    "Articles with unsourced statements from October 26, 2014 (Sun) 01:50 (UTC)",
    "Articles with unsourced statements from October 26, 2014 (Sun) 01:53 (UTC)",
    "Articles with unsourced statements from October 26, 2014 (Sun) 11:02 (UTC)~",
    "Articles with unsourced statements from September 2017",
    "Articles with unsourced statements from Tuesday, July 30, 2019, 01:34 (UTC)",
    "Buildings and structures in Murakami, Niigata",
    "Buildings in Ishii, Tokushima",
    "Buildings in Mima, Tokushima",
    "Buildings in Tsurugi Town",
    "Cross symbols",
    "Dashi and Yatai",
    "Emishi",
    "Envoys to Sui China",
    "Figures in Japanese mythology",
    "Former village shrines of Toyama Prefecture",
    "Go-no-Miya",
    "Hinokuma Jingū",
    "Historic sites in Kasama City",
    "History of Ishii, Tokushima",
    "History of Mima, Tokushima",
    "History of Mito City",
    "History of Murakami, Niigata",
    "History of Oyama Town",
    "History of Yurihama Town",
    "Karatsu Domain",
    "Keigai-Massha",
    "Ki clan (Shinbetsu)",
    "Kuni no Miyatsuko",
    "Legendary figures of Japan",
    "Municipal History of Kitaibaraki",
    "Municipal History of Naka",
    "Municipal History of Tsurugi",
    "National Treasures of Tottori Prefecture",
    "Prefectural People's 100 Selected Buildings",
    "Registered Tangible Cultural Property of Japan in Tottori prefecture",
    "Sada Shrine",
    "Sangoku Sōden In'yō Kankatsu Hoki Naiden Kin'u Gyokuto Shū",
    "Shi-no-Miya",
    "Shikinaisha of Etchū Province",
    "Shinto shrines in Toyama City",
    "Sinami Haguro Shrine",
    "Sugiyama-jinja (Musashi Province)",
    "Suwa Shrines",
    "Tagimitonotoya Shrine",
    "Tamura narratives",
    "Unicodeに存在しない文字",
    "Wikipedia references cleanup from February 2018",
    "Years needing redirect replacements",
    "「神宿る島」宗像・沖ノ島と関連遺産群",
    "あま市の建築物",
    "あま市の歴史",
    "さいたま市北区の建築物",
    "さいたま市北区の歴史",
    "さぬき市の建築物",
    "さぬき市の歴史",
    "つくば市の建築物",
    "つくば市の歴史",
    "つくば科学万博",
    "ひたちなか市の建築物",
    "ひたちなか市の歴史",
    "まんのう町の建築物",
    "まんのう町の歴史",
    "アテルイ",
    "七尾市の建築物",
    "七尾市の歴史",
    "三原市の建築物",
    "三原市の歴史",
    "三宮",
    "三木市の建築物",
    "三木市の歴史",
    "三田 (東京都港区)",
    "三田市の建築物",
    "三田市の歴史",
    "三豊市の建築物",
    "三豊市の歴史",
    "三重県の重要文化財",
    "三重県朝日町の歴史",
    "三野郷",
    "上牧町の建築物",
    "上牧町の歴史",
    "上総国",
    "上賀茂・柊野",
    "上越市の建築物",
    "上越市の歴史",
    "上野 (神戸市)",
    "下條村の建築物",
    "下條村の歴史",
    "下県郡",
    "丸岡藩",
    "丹波篠山市の建築物",
    "丹波篠山市の歴史",
    "久御山町の建築物",
    "久御山町の歴史",
    "久留米市の建築物",
    "久留米市の歴史",
    "九十九王子",
    "二宮町の建築物",
    "二宮町の歴史",
    "京北 (京都市)",
    "京都府の旧無格社",
    "京都府の登録有形文化財",
    "京都府内の市町村指定史跡",
    "今池 (名古屋市)",
    "今治藩",
    "仙台市の神社",
    "伊予国",
    "伊勢崎市の建築物",
    "伊勢崎市の歴史",
    "伊豆国",
    "会津美里町の建築物",
    "会津美里町の歴史",
    "会津若松市の建築物",
    "会津若松市の歴史",
    "佐々木氏",
    "佐伯氏",
    "佐那河内村の建築物",
    "佐那河内村の歴史",
    "信太郡",
    "備中国",
    "備前国",
    "元明天皇",
    "光市の建築物",
    "光市の歴史",
    "八丈町の建築物",
    "八丈町の歴史",
    "八幡信仰",
    "八幡市の建築物",
    "八幡市の歴史",
    "八王子市の建築物",
    "八王子市の歴史",
    "八郎潟町の建築物",
    "八郎潟町の歴史",
    "兵庫県内の市町村指定有形文化財",
    "准勅祭社",
    "出水市の建築物",
    "出水市の歴史",
    "出石藩",
    "利府町の建築物",
    "利府町の歴史",
    "利根町の建築物",
    "利根町の歴史",
    "加賀国",
    "加賀市の建築物",
    "加賀市の歴史",
    "加須市の神社",
    "北杜市の建築物",
    "北杜市の歴史",
    "匝瑳市の建築物",
    "匝瑳市の歴史",
    "区市町村指定有形民俗文化財",
    "十市郡",
    "千種区の建築物",
    "千種区の歴史",
    "千葉氏",
    "千葉県の国宝",
    "千葉県の登録有形文化財",
    "千葉県の観光地",
    "千葉県指定有形文化財",
    "南山名",
    "博多区の建築物",
    "博多区の歴史",
    "厚木市の建築物",
    "厚木市の歴史",
    "古殿町の建築物",
    "古殿町の歴史",
    "吉田町の建築物",
    "吉田町の歴史",
    "同名の神社",
    "名取市の建築物",
    "名取市の歴史",
    "名古屋市東区の建築物",
    "名古屋市東区の歴史",
    "名草郡",
    "和歌山県の旧郷社",
    "和歌山県指定史跡",
    "和歌山県指定有形文化財",
    "四国中央市の建築物",
    "四国中央市の歴史",
    "四條畷市の建築物",
    "四條畷市の歴史",
    "囲碁ゆかりの地",
    "国幣大社",
    "国民保養温泉地",
    "園田地区",
    "園部藩",
    "土佐郡",
    "土器",
    "土師氏",
    "坂井市の建築物",
    "坂井市の歴史",
    "坂城町の建築物",
    "坂城町の歴史",
    "坂祝町の建築物",
    "坂祝町の歴史",
    "垂水区の建築物",
    "垂水区の歴史",
    "埼玉県の国宝",
    "埼玉県の寺",
    "埼玉県の登録有形文化財",
    "埼玉県美里町の建築物",
    "埼玉県美里町の歴史",
    "堺市西区の建築物",
    "堺市西区の歴史",
    "塩竈神社",
    "売布 (宝塚市)",
    "多賀城市の建築物",
    "多賀城市の歴史",
    "大分県にある国指定の史跡",
    "大分県の国宝",
    "大分県の画像提供依頼",
    "大分県の重要文化財",
    "大台町の建築物",
    "大台町の歴史",
    "大和町の建築物",
    "大和町の歴史",
    "大垣藩",
    "大峯奥駈道",
    "大庭氏",
    "大東市の建築物",
    "大東市の歴史",
    "大正 (八尾市)",
    "大正時代の建築",
    "大河原町の建築物",
    "大河原町の歴史",
    "大野市の建築物",
    "大野市の歴史",
    "大野町の建築物",
    "大野町の歴史",
    "大阪府の国宝",
    "大阪府の旧無格社",
    "大阪府太子町の建築物",
    "大阪府太子町の歴史",
    "大阪府指定天然記念物",
    "大隅国",
    "天智天皇",
    "天武天皇",
    "太宰府市の建築物",
    "太宰府市の歴史",
    "太白区の建築物",
    "太白区の歴史",
    "奈良市の建築物",
    "奈良市の歴史",
    "奈良県の国宝",
    "奈良県の旧無格社",
    "奈良県川上村の建築物",
    "奈良県川上村の歴史",
    "姫路市の神社",
    "宇佐市の建築物",
    "宇佐市の歴史",
    "宇佐神宮",
    "宇治市の重要文化財",
    "宇治郡",
    "宇都宮氏",
    "宇陀市の建築物",
    "宇陀市の歴史",
    "安房国",
    "安来市の建築物",
    "安来市の歴史",
    "宗像氏",
    "宗像神社",
    "宮勝氏",
    "宮城県指定有形文化財",
    "宿毛市の建築物",
    "宿毛市の歴史",
    "寄居町の建築物",
    "寄居町の歴史",
    "富士塚",
    "富岡市の建築物",
    "富岡市の歴史",
    "対馬国",
    "射水市の建築物",
    "射水市の歴史",
    "小千谷市の建築物",
    "小千谷市の歴史",
    "小林市の建築物",
    "小林市の歴史",
    "小野氏",
    "小野篁",
    "小野道風",
    "尾張国の帳内社",
    "尾張旭市の建築物",
    "尾張旭市の歴史",
    "屋久島町の建築物",
    "屋久島町の歴史",
    "山口地域",
    "山口市の建築物",
    "山口市の歴史",
    "山形県の旧郷社",
    "山梨県の旧県社",
    "山梨県内の市町村指定有形文化財",
    "山梨県指定有形文化財",
    "山田 (吹田市)",
    "山科区の建築物",
    "山科区の歴史",
    "山那",
    "山陰海岸ジオパーク",
    "岐南町の建築物",
    "岐南町の歴史",
    "岐阜市の重要文化財",
    "岐阜県の登録有形文化財",
    "岐阜県池田町の建築物",
    "岐阜県池田町の歴史",
    "岡山市中区の建築物",
    "岡山市中区の歴史",
    "岡山県の国宝",
    "岡田郡",
    "岩屋 (神戸市)",
    "岩手県の旧県社",
    "岸和田藩",
    "島根県の登録有形文化財",
    "島根県の酒",
    "島根県内の市町村指定有形文化財",
    "島田市の建築物",
    "島田市の歴史",
    "嵯峨天皇",
    "川崎市の神社",
    "巽 (大阪市)",
    "市原市の建築物",
    "市原市の歴史",
    "常総市の建築物",
    "常総市の歴史",
    "平塚市の建築物",
    "平塚市の歴史",
    "広島県の旧郷社",
    "広島県内の市町村指定有形文化財",
    "広島県府中市の建築物",
    "広島県府中市の歴史",
    "広陵町の建築物",
    "広陵町の歴史",
    "弓削氏",
    "彦根市の建築物",
    "彦根市の歴史",
    "御嶽神社",
    "御蔵島村の建築物",
    "御蔵島村の歴史",
    "徳島県の旧無格社",
    "徳島県指定史跡",
    "徳川斉昭",
    "性的シンボル",
    "愛媛県松前町の建築物",
    "愛媛県松前町の歴史",
    "成田市の建築物",
    "成田市の歴史",
    "我孫子 (大阪市)",
    "持統天皇",
    "提案があるページ",
    "揖保郡",
    "文化財盗難被害に遭った寺社",
    "斉明天皇",
    "斎藤",
    "新四国曼荼羅霊場",
    "新地町の建築物",
    "新地町の歴史",
    "新居浜市の建築物",
    "新居浜市の歴史",
    "新潟市東区の建築物",
    "新潟市東区の歴史",
    "新潟県の旧村社",
    "新潟県の重要文化財",
    "日向国",
    "日本の木造建築物",
    "日立市の建築物",
    "日立市の歴史",
    "有田市の建築物",
    "有田市の歴史",
    "有馬温泉郷",
    "朝倉市の建築物",
    "朝倉市の歴史",
    "本巣市の建築物",
    "本巣市の歴史",
    "村上市の建築物",
    "村上市の歴史",
    "東かがわ市の建築物",
    "東かがわ市の歴史",
    "東京都内の区市町村指定史跡",
    "東京都内の区市町村指定有形文化財",
    "東京都指定有形文化財",
    "東京都港区の神社",
    "東伊豆町の建築物",
    "東伊豆町の歴史",
    "東吉野村の歴史",
    "東吾妻町の建築物",
    "東吾妻町の歴史",
    "東員町の建築物",
    "東員町の歴史",
    "東漢氏",
    "東白川村の建築物",
    "東白川村の歴史",
    "東近江市の建築物",
    "東近江市の歴史",
    "東近江市の重要文化財",
    "松原市の建築物",
    "松山市の建築物",
    "松山市の歴史",
    "松山市の神社",
    "松江市の重要文化財",
    "松田町の建築物",
    "松田町の歴史",
    "板野町の建築物",
    "板野町の歴史",
    "栃木県指定有形文化財",
    "栗栖氏",
    "桐生市の建築物",
    "桐生市の歴史",
    "桶川市の建築物",
    "桶川市の歴史",
    "武庫郡",
    "毛呂山町の建築物",
    "毛呂山町の歴史",
    "水神",
    "泉大津市の建築物",
    "泉大津市の歴史",
    "津幡町の建築物",
    "津幡町の歴史",
    "流山市の建築物",
    "流山市の歴史",
    "浦和区の建築物",
    "浦和区の歴史",
    "浪江町の建築物",
    "浪江町の歴史",
    "淡路国",
    "淡路市の建築物",
    "淡路市の歴史",
    "深谷市の建築物",
    "深谷市の歴史",
    "港北区の建築物",
    "港北区の歴史",
    "瀬戸内市の建築物",
    "瀬戸内市の歴史",
    "火伏せ",
    "為奈氏",
    "無効なReferencesが含まれている記事 from 2023年10月",
    "焼津市の建築物",
    "焼津市の歴史",
    "熊本県の旧県社",
    "熊野信仰",
    "熊野神社",
    "猪苗代町の建築物",
    "猪苗代町の歴史",
    "玉村町の建築物",
    "玉村町の歴史",
    "珠洲市の建築物",
    "珠洲市の歴史",
    "生野区の建築物",
    "生野区の歴史",
    "由布市の建築物",
    "由布市の歴史",
    "白山国立公園",
    "白山市の建築物",
    "白山市の歴史",
    "白川町の建築物",
    "白川町の歴史",
    "眉山",
    "真岡市の建築物",
    "真岡市の歴史",
    "石川町の建築物",
    "石川町の歴史",
    "石川県の国宝",
    "石川県の旧村社",
    "石川県指定有形文化財",
    "石見国",
    "確認・注意事項があるページ",
    "社寺参詣曼荼羅",
    "祇園信仰",
    "神山町の建築物",
    "神山町の歴史",
    "神戸市の重要文化財",
    "神戸市中央区の建築物",
    "神戸市中央区の歴史",
    "神戸町の建築物",
    "神戸町の歴史",
    "神社の画像提供依頼",
    "神道と性",
    "福井県の国宝",
    "福井県の重要文化財",
    "福井県指定有形文化財",
    "福山市の重要文化財",
    "福岡県にある国指定の史跡",
    "福岡県の国宝",
    "福岡県指定天然記念物",
    "福島県の重要文化財",
    "福島県内の市町村指定有形文化財",
    "秋田六郡三十三観音霊場",
    "秩父市の神社",
    "稗田氏",
    "稗田阿礼",
    "立山町の建築物",
    "立山町の歴史",
    "竜王町の建築物",
    "竜王町の歴史",
    "竹田市の建築物",
    "竹田市の歴史",
    "竹田市の画像提供依頼",
    "筑後国",
    "筒井 (名古屋市)",
    "算額",
    "紀伊山地の霊場と参詣道",
    "紫波町の建築物",
    "紫波町の歴史",
    "継体天皇",
    "網干",
    "総社市の建築物",
    "総社市の歴史",
    "美原区の建築物",
    "美原区の歴史",
    "美浦村の建築物",
    "美浦村の歴史",
    "群馬県指定天然記念物",
    "耳納山地",
    "聖徳太子",
    "能美市の建築物",
    "能美市の歴史",
    "舞鶴市の建築物",
    "舞鶴市の歴史",
    "若桜町の建築物",
    "若桜町の歴史",
    "若江",
    "若江郡",
    "若狭国",
    "若狭国の式内社",
    "若狭町の建築物",
    "若狭町の歴史",
    "茂原市の建築物",
    "茂原市の歴史",
    "茨城県にある国指定の史跡",
    "茨城県の国宝",
    "茨城県内の市町村指定有形文化財",
    "菅原氏",
    "蔵王町の建築物",
    "蔵王町の歴史",
    "薩摩国",
    "藤原時平",
    "藤原鎌足",
    "蘇我馬子",
    "行方郡 (福島県)",
    "行田市の建築物",
    "行田市の歴史",
    "西垂水",
    "西宮市の建築物",
    "西宮市の歴史",
    "西条市の建築物",
    "西条市の歴史",
    "西郷村の建築物",
    "西郷村の歴史",
    "諏訪信仰",
    "議論が行われているページ",
    "讃岐国",
    "讃岐氏",
    "豊前国",
    "豊川市の建築物",
    "豊川市の歴史",
    "豊後国",
    "豊橋市の建築物",
    "豊橋市の歴史",
    "質問があるページ",
    "赤染氏",
    "赤磐市の建築物",
    "赤磐市の歴史",
    "赤穂市の建築物",
    "赤穂市の歴史",
    "越前国",
    "軽井沢町の建築物",
    "軽井沢町の歴史",
    "輪之内町の建築物",
    "輪之内町の歴史",
    "那珂川町の建築物",
    "那珂川町の歴史",
    "都農町の建築物",
    "都農町の歴史",
    "長吉",
    "長居",
    "長崎県の旧無格社",
    "長崎県の旧県社",
    "長崎県の旧郷社",
    "長崎県の重要文化財",
    "長野県の重要文化財",
    "長野県内の市町村指定有形文化財",
    "長野県池田町の建築物",
    "長野県池田町の歴史",
    "門真市の建築物",
    "門真市の歴史",
    "関市の建築物",
    "関市の歴史",
    "関東八十八箇所",
    "防府市の建築物",
    "防府市の歴史",
    "阿蘇市の建築物",
    "阿蘇市の歴史",
    "阿蘇神社",
    "陶芸",
    "陸奥国",
    "静岡市の重要文化財",
    "静岡県の旧無格社",
    "静岡県清水町の建築物",
    "静岡県清水町の歴史",
    "鞆の浦",
    "須坂市の建築物",
    "須坂市の歴史",
    "香南市の建築物",
    "香南市の歴史",
    "香取市の建築物",
    "香取市の歴史",
    "香取神社",
    "香川県の国宝",
    "香川県の旧村社",
    "香川県内の市町村指定有形文化財",
    "香春町の建築物",
    "香春町の歴史",
    "香美市の建築物",
    "香美市の歴史",
    "高岡市の観光地",
    "高崎市の建築物",
    "高崎市の歴史",
    "高田・新吉田",
    "高知県の旧村社",
    "高知県の旧県社",
    "高知県の登録有形文化財",
    "高知県内の市町村指定史跡",
    "高知県内の市町村指定有形文化財",
    "高知県指定有形文化財",
    "高石市の建築物",
    "高石市の歴史",
    "高野山真言宗の寺院",
    "鳥取県の旧村社",
    "鳥取県の温泉",
    "鹿児島県にある国指定の史跡",
    "鹿児島県の国宝",
    "鹿児島県内の市町村指定有形文化財",
    "鹿児島県指定有形文化財",
    "鹿島神宮",
    "鹿嶋市の建築物",
    "鹿嶋市の歴史",
    "黒潮町の建築物",
    "黒潮町の歴史",
    "黒部市の建築物",
    "黒部市の歴史",
    "龍華",
]

def main():
    print(f"Total categories to create: {len(CATEGORIES)}\n")

    print(f"Connecting to {WIKI_URL}...")
    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent='ShintoWikiBot/1.0 (immanuelle@shinto.miraheze.org)')
    site.login(USERNAME, PASSWORD)
    print("Logged in successfully\n")

    total = len(CATEGORIES)
    success = 0
    failed = 0
    skipped = 0

    for i, cat_name in enumerate(CATEGORIES, 1):
        page_title = f"Category:{cat_name}"
        print(f"[{i}/{total}] {page_title}", end=" ... ", flush=True)

        try:
            page = site.pages[page_title]
            if page.exists:
                print("SKIPPED (already exists)")
                skipped += 1
            else:
                page.save(CATEGORY_CONTENT, summary="Bot: Recreate category (third wave) after wiki restoration")
                print("OK")
                success += 1
        except Exception as e:
            print(f"FAILED: {e}")
            failed += 1

        time.sleep(SLEEP)

    print(f"\n{'='*50}")
    print(f"Summary: {success} created, {skipped} skipped, {failed} failed out of {total}")

if __name__ == "__main__":
    main()
