#!/usr/bin/env python3
"""
recreate_categories.py
======================
Recreates category pages that were lost during wiki restoration.
Each category page will contain only: [[Category:Categories mass created after wiki recreation]]
"""

import mwclient
import sys
import time

# Fix Unicode encoding issues on Windows
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Configuration
WIKI_URL = 'shinto.miraheze.org'
WIKI_PATH = '/w/'
USERNAME = 'Immanuelle'
PASSWORD = '[REDACTED_SECRET_2]'
SLEEP = 1.5  # seconds between edits

# Categories to recreate
CATEGORIES = [
    "Commons category link from Wikidata",
    "Kokuhei-sha",
    "Pages with unclosed square brackets",
    "Shikinai Ronsha",
    "No local image but image on Wikidata",
    "Pages with unclosed parentheses",
    "Pages using infobox deity with unrecognised type",
    "Junior Fifth Rank",
    "Pages with unclosed curly braces",
    "Kanpei-sha",
    "Junior Fourth Rank",
    "Senior Fifth Rank",
    "Pages linked to everybodywiki",
    "Articles having different image on Wikidata and Wikipedia",
    "Shrine receiving Tsukinami-sai and Niiname-sai offerings",
    "Shikinai Hiteisha",
    "Disputed Shikinaisha or Shikigesha",
    "Lunisolar 12 Month",
    "Lunisolar 4 Month",
    "Junior Third Rank",
    "Senior Fourth Rank",
    "Articles having same image on Wikidata and Wikipedia",
    "Pages likely having an accidental overwite in their history that shrank them",
    "Pages with recovered content",
    "Junior Second Rank",
    "Senior Third Rank",
    "Senior Second Rank",
    "Shrine receiving Tsukinami-sai and Niiname-sai and Ainame-sai offerings",
    "Lunisolar 8 Month",
    "Junior First Rank",
    "2",
    "Senior First Rank",
    "Bad redireects",
    "Categories in Categories missing wikidata but actually having wikidata but with jawiki",
    "Shrines receiving Hoe and Quiver",
    "Gōshi",
    "Shikinai Subshrine",
    "TemplateStyles stylesheets with errors",
    "Senior Sixth Rank",
    "Broken commons categories",
    "Lunisolar 1 Month",
    "Massha",
    "Pages to be deleted",
    "Stub message templates needing attention",
    "Lunisolar 9 Month",
    "Sessha",
    "Shikinai Supershrine",
    "Akagi Shrine (worship)",
    "All Wikipedia articles in need of updating",
    "Architecture of Kasama City",
    "Articles containing potentially dated statements from 2026",
    "Articles lacking reliable references from October 2021",
    "Articles lacking sources from January 2015",
    "Articles needing additional references from September 2024",
    "Articles that may contain original research from September 2021",
    "Articles with unsourced statements from December 2012",
    "Articles with unsourced statements from November 2012",
    "Autogenerated pages with jawiki interwikis, possibly accidentally overwritten",
    "Automerged Japanese text",
    "Autumn equinox",
    "Autumn in China",
    "Azekura-zukuri",
    "Buildings and structures in Kasama, Ibaraki",
    "Buildings in Akashi",
    "Buildings in Beppu City",
    "Buildings in Komatsu, Ishikawa",
    "Buildings in Shiso, Hyogo",
    "Buildings in Tonami, Toyama",
    "Bump1-19",
    "Categories created en masse on Dec 10 2025",
    "Draft. Categorizing it as such was an error. It is from an archived english",
    "Festivals in Chinese folk religion",
    "Festivals in Hong Kong",
    "Fictional married couples",
    "Folk festivals in China",
    "Folk festivals in Taiwan",
    "Former Gō-sha in Kagoshima Prefecture",
    "Former village shrines in Ibaraki Prefecture",
    "Gion shrine",
    "Hachiman shrine",
    "Here",
    "History of Akashi, Hyogo",
    "History of Beppu City",
    "History of Kasama, Ibaraki",
    "History of Tonami, Toyama",
    "Inari shrine",
    "Lunar observation",
    "Lunisolar 2 Month",
    "Lunisolar 6 Month",
    "Lunisolar 7 Month",
    "Mass Imported Shinto Cult Pages Needing Dummy Edit for Attribution and Review",
    "Mid-Autumn Festival",
    "Mitake shrine",
    "Municipal History of Kasama",
    "Municipal History of Shisō",
    "Mythological pairs",
    "Observances held on the full moon",
    "Observances set by the Chinese calendar",
    "Orphans from wikipedia",
    "Pages from everybodywiki under right title",
    "Pages using infobox bridge with empty coordinates parameter",
    "Pages using infobox building with unknown parameters",
    "Pages using template Zh with sup tags",
    "Pages with files linked by ill",
    "Public holidays in China",
    "Public holidays in Hong Kong",
    "Public holidays in Taiwan",
    "Refreshing categories imported on 2024-01-19",
    "Religious festivals in China",
    "S11",
    "San-no-Miya",
    "Sannō shrine",
    "Shinmei shrine",
    "Shrines in Oita Prefecture",
    "Shrines receiving Hoe offering",
    "Son-sha in Toyama Prefecture",
    "Take Shrine",
    "Temple of Evergreen",
    "Temples in Kaohsiung",
    "Tenmangū (worship)",
    "Unsorted",
    "Use dmy dates from September 2022",
    "Wikipedia articles in need of updating from October 2022",
    "Ōmushi Shrine (Echizen)",
    "伊勢国の式内社",
    "別府市の建築物",
    "別府市の歴史",
    "多気町の建築物",
    "多気町の歴史",
    "摂末社",
    "神宮125社",
]

# Content for each category page
CATEGORY_CONTENT = "[[Category:Categories mass created after wiki recreation]]"

def main():
    print(f"Connecting to {WIKI_URL}...")
    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent='ShintoWikiBot/1.0 (immanuelle@shinto.miraheze.org)')
    site.login(USERNAME, PASSWORD)
    print("Logged in successfully\n")

    total = len(CATEGORIES)
    success = 0
    failed = 0

    for i, cat_name in enumerate(CATEGORIES, 1):
        page_title = f"Category:{cat_name}"
        print(f"[{i}/{total}] {page_title}", end=" ... ", flush=True)

        try:
            page = site.pages[page_title]
            page.save(CATEGORY_CONTENT, summary="Bot: Recreate category after wiki restoration")
            print("OK")
            success += 1
        except Exception as e:
            print(f"FAILED: {e}")
            failed += 1

        time.sleep(SLEEP)

    print(f"\n{'='*50}")
    print(f"Summary: {success} created, {failed} failed out of {total}")

if __name__ == "__main__":
    main()
