#!/usr/bin/env python3
"""
remote_queue.py
================
Builds a queue of agentic-work items for a remote Claude cron to
consume. Each item is a ``(file, instruction)`` pair — the remote
worker reads the file, applies the instruction, and commits.

This is the bridge between the repo's standing backlog (the bulk
LLM-grunge items in ``queue.md``) and an autonomous loop that can
finally let the wiki run without the human in the chain. The goal,
per the queue plan, is for the wiki to reach a "decent state for the
archives" without ongoing manual attention — even if the wiki itself
stops being hosted long-term.

Sources and how they map to instructions:

  duplicated_content/*.wiki
      Reorganize-to-remove-duplication. When the page is done, the
      worker drops [[Category:Pages with duplicated content]] from
      the file — the next sync push+deletes from the repo.
      ~353 items (the big chunk).

  need_translation/*.wiki
      Translate Japanese prose to English. When the page is done,
      the worker drops [[Category:Need translation]] from the file
      — the sync push+deletes from the repo. ~121 items.

  fandom_unique/*.wiki
      Replace miraheze-only templates ({{ill}}, {{wikidata link}},
      {{translated page}}, {{jalink}}) with plain wikilinks and
      fandom-compatible alternatives so the page renders on
      shinto.fandom.com. ~600 items.

Japanese-titled pages are excluded — those moves are intentional
manual work per the queue plan.

Output: ``remote_queue.json`` at the repo root. The remote consumer
reads this; the queue is uncapped (1000+ items expected) — the
consumer paces itself, and the next nightly rebuild reflects the
new repo state regardless.
"""

import argparse
import datetime
import io
import json
import os
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parent
QUEUE_PATH = REPO_ROOT / "remote_queue.json"
SCHEMA_VERSION = 1


# ─── instruction templates ─────────────────────────────────

DUPLICATED_CONTENT_INSTRUCTION = (
    "Reorganize this page so it reads as a single coherent article. "
    "The page was tagged with [[Category:Pages with duplicated content]] "
    "because content was duplicated between the source-of-import boilerplate "
    "(usually an autogenerated wikidata-claim dump or a "
    "`== AUTOGENERATED CONTENT FROM WIKIDATA ==` section) and the article "
    "body. Move paragraphs around, drop boilerplate that restates facts "
    "already in the lede/infobox, dedupe overlapping prose, and end up with "
    "a relatively organized article. Preserve any `== Japanese Wikipedia "
    "content ==` section verbatim (those are tracked separately under "
    "[[Category:Need translation]] and translation is a different job). "
    "When done, remove `[[Category:Pages with duplicated content]]` from the "
    "file — the next CI sync will push the cleaned version to the wiki and "
    "delete the local file."
)

NEED_TRANSLATION_INSTRUCTION = (
    "Translate the Japanese-language content in this page to English. "
    "Many of these are kokuzo (国造) articles or shrine prose imported from "
    "ja.wikipedia. Preserve all `{{ill|...}}`, `{{jalink|...}}`, and "
    "`{{nihongo|...}}` template calls verbatim — those are link wrappers, "
    "not prose to translate. Preserve `<ref>...</ref>` blocks verbatim. "
    "Translate only the prose between templates and refs. When the page no "
    "longer contains CJK characters outside template parameters and refs, "
    "remove `[[Category:Need translation]]` from the file — the next CI sync "
    "will push the translation to the wiki and delete the local file. "
    "WARNING: this sync is destructive — removing the category deletes the "
    "file from the repo, so only drop it when translation is genuinely done."
)

FANDOM_UNIQUE_INSTRUCTION = (
    "Rewrite this page so it renders correctly on shinto.fandom.com. The "
    "miraheze-only templates that don't exist on fandom: `{{ill|...}}`, "
    "`{{wikidata link|...}}`, `{{translated page|...}}`, `{{jalink|...}}`, "
    "and the various `{{...Faith|qq=}}` navboxes that depend on miraheze "
    "modules. Convert `{{ill|TITLE|...lang_codes...|1=DISPLAY}}` and "
    "`{{ill|TITLE|...|lt=DISPLAY|...}}` to plain `[[TITLE|DISPLAY]]` "
    "wikilinks (or `[[TITLE]]` when there's no display-text override). "
    "Drop `{{wikidata link|...}}` and `{{translated page|...}}` entirely — "
    "their content doesn't carry meaning on fandom. Drop "
    "[[Category:Pages with interwikis with duplicate languages]] and any "
    "other miraheze-only maintenance categories. Keep the article body and "
    "standard categories. Don't touch the miraheze_unique/ copy — that's a "
    "separate file under the dual-sync model."
)


# ─── queue builder ─────────────────────────────────────────


def _build_section(
    dir_name: str,
    instruction: str,
    *,
    filter_fn=None,
) -> list[dict]:
    items: list[dict] = []
    directory = REPO_ROOT / dir_name
    if not directory.is_dir():
        return items
    for path in sorted(directory.glob("*.wiki")):
        if filter_fn is not None and not filter_fn(path):
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        items.append(
            {
                "id": rel,
                "file": rel,
                "category": dir_name,
                "instruction": instruction,
            }
        )
    return items


def _is_disambig_or_english_titled(path: Path) -> bool:
    """Filter for fandom_unique/: skip Japanese-titled pages.

    Pages whose stem is pure CJK aren't in scope for the autonomous
    template-fixup pass; the user moves those manually.
    """
    stem = path.stem
    if not stem:
        return False
    cjk_chars = sum(
        1
        for ch in stem
        if "぀" <= ch <= "ゟ"
        or "゠" <= ch <= "ヿ"
        or "㐀" <= ch <= "鿿"
    )
    return cjk_chars <= max(1, len(stem) // 4)


def build_queue() -> list[dict]:
    items: list[dict] = []
    items.extend(_build_section("duplicated_content", DUPLICATED_CONTENT_INSTRUCTION))
    items.extend(_build_section("need_translation", NEED_TRANSLATION_INSTRUCTION))
    items.extend(
        _build_section(
            "fandom_unique",
            FANDOM_UNIQUE_INSTRUCTION,
            filter_fn=_is_disambig_or_english_titled,
        )
    )
    return items


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--output",
        default=str(QUEUE_PATH),
        help="path to write the queue JSON (default: remote_queue.json at repo root)",
    )
    args = ap.parse_args()

    items = build_queue()
    queue = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "item_count": len(items),
        "items": items,
    }

    out_path = Path(args.output)
    out_path.write_text(json.dumps(queue, indent=2, ensure_ascii=False), encoding="utf-8")
    print(
        f"Wrote {out_path.relative_to(REPO_ROOT) if out_path.is_absolute() else out_path} "
        f"with {len(items)} items "
        f"(duplicated_content + need_translation + fandom_unique [non-CJK titles])."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
