#!/usr/bin/env python3
"""
remote_queue.py
================
Builds a queue of agentic-work items for a remote Claude cron to
consume. Each item is a ``(file, instruction)`` pair — the remote
worker reads the file, applies the instruction, and commits.

This is the bridge between the repo's standing backlog (the bulk
LLM-grunge items in ``queue.md``) and an autonomous loop that can
finally let the wiki run without the human in the chain. The goal,
per the queue plan, is for the wiki to reach a "decent state for the
archives" without ongoing manual attention — even if the wiki itself
stops being hosted long-term.

Sources and how they map to instructions:

  duplicated_content/*.wiki
      Reorganize-to-remove-duplication. When the page is done, the
      worker drops [[Category:Pages with duplicated content]] from
      the file — the next sync push+deletes from the repo.
      ~353 items (the big chunk).

  need_translation/*.wiki
      Translate Japanese prose to English. When the page is done,
      the worker drops [[Category:Need translation]] from the file
      — the sync push+deletes from the repo. ~121 items.

  fandom_unique/*.wiki
      Replace miraheze-only templates ({{ill}}, {{wikidata link}},
      {{translated page}}, {{jalink}}) with plain wikilinks and
      fandom-compatible alternatives so the page renders on
      shinto.fandom.com. ~600 items.

  miraheze_unique/*.wiki (shrine-disambig subset)
      Strip the old human-curated lists inherited from the
      source-of-import pages and leave only a generic intro +
      the auto-generated `== Shrines with this name ==` block
      (delimited by the BEGIN/END markers). Detection: pages
      containing the auto-generated-block marker. ~115 items.

  miraheze_unique/*.wiki (shrine-disambig, no auto-gen block yet)
      Split into two sub-buckets by whether the regex kanji extractor
      can recover the kanji form:
        * kanji_known: the kanji is embedded directly in the instruction
          so the worker can SPARQL right away.
        * kanji_unknown: the worker has to read the page to find a
          kanji form (might be in an infobox parameter, an interwiki
          ``[[ja:...]]`` link, a non-standard ``{{nihongo}}`` call,
          etc.) or accept that the page has no recoverable kanji.

Japanese-titled pages are excluded — those moves are intentional
manual work per the queue plan.

Output: ``remote_queue.json`` at the repo root. The remote consumer
reads this; the queue is uncapped (1000+ items expected) — the
consumer paces itself, and the next nightly rebuild reflects the
new repo state regardless.
"""

import argparse
import datetime
import io
import json
import os
import re
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parent
QUEUE_PATH = REPO_ROOT / "remote_queue.json"
SCHEMA_VERSION = 1


# ─── instruction templates ─────────────────────────────────

DUPLICATED_CONTENT_INSTRUCTION = (
    "Reorganize this page so it reads as a single coherent article. "
    "The page was tagged with [[Category:Pages with duplicated content]] "
    "because content was duplicated between the source-of-import boilerplate "
    "(usually an autogenerated wikidata-claim dump or a "
    "`== AUTOGENERATED CONTENT FROM WIKIDATA ==` section) and the article "
    "body. Move paragraphs around, drop boilerplate that restates facts "
    "already in the lede/infobox, dedupe overlapping prose, and end up with "
    "a relatively organized article. Preserve any `== Japanese Wikipedia "
    "content ==` section verbatim (those are tracked separately under "
    "[[Category:Need translation]] and translation is a different job). "
    "When done, remove `[[Category:Pages with duplicated content]]` from the "
    "file — the next CI sync will push the cleaned version to the wiki and "
    "delete the local file."
)

NEED_TRANSLATION_INSTRUCTION = (
    "Translate the Japanese-language content in this page to English. "
    "Many of these are kokuzo (国造) articles or shrine prose imported from "
    "ja.wikipedia. Preserve all `{{ill|...}}`, `{{jalink|...}}`, and "
    "`{{nihongo|...}}` template calls verbatim — those are link wrappers, "
    "not prose to translate. Preserve `<ref>...</ref>` blocks verbatim. "
    "Translate only the prose between templates and refs. When the page no "
    "longer contains CJK characters outside template parameters and refs, "
    "remove `[[Category:Need translation]]` from the file — the next CI sync "
    "will push the translation to the wiki and delete the local file. "
    "WARNING: this sync is destructive — removing the category deletes the "
    "file from the repo, so only drop it when translation is genuinely done."
)

MIRAHEZE_SHRINE_DISAMBIG_NO_AUTOGEN_KANJI_KNOWN_TEMPLATE = (
    "This shrine disambiguation page (tagged [[Category:Shrine "
    "disambiguations]]) doesn't have the auto-generated `== Shrines "
    "with this name ==` block yet, but the kanji form is recoverable "
    "from the page: {kanji_repr}. Most likely the regular "
    "`generate_shrine_disambig_lists.py` sweep just hasn't visited "
    "this page yet (it's incremental and there's a backlog), or its "
    "SPARQL exact-label match returned zero results. Fix it directly: "
    "SPARQL Wikidata for items that are subclass-of Q845945 (Shinto "
    "shrine) carrying that kanji as an `ja` rdfs:label or skos:altLabel "
    "(broaden with prefix match if exact returns nothing), and write "
    "the section in the same format as other shrine-disambig pages. "
    "Wrap it in the standard `<!-- BEGIN: auto-generated Wikidata "
    "shrine list -->` / `<!-- END: auto-generated Wikidata shrine list "
    "-->` markers so the regular script keeps maintaining it on future "
    "sweeps. If SPARQL returns nothing meaningful even with the broader "
    "query, leave the page as-is."
)

MIRAHEZE_SHRINE_DISAMBIG_NO_AUTOGEN_KANJI_UNKNOWN_INSTRUCTION = (
    "This shrine disambiguation page (tagged [[Category:Shrine "
    "disambiguations]]) doesn't have the auto-generated `== Shrines "
    "with this name ==` block, and the regex kanji extractor couldn't "
    "recover a kanji form. Read the page carefully — the kanji might "
    "be in a non-standard place (an infobox parameter, an inline "
    "mention, a comment, a `{{nihongo|...}}` call missing the standard "
    "shape, or an interwiki link like `[[ja:KANJI]]`). If you find it, "
    "either (a) add a `{{Nihongo|EnglishName|KANJI|romaji}}` template "
    "near the top so the regular script can pick it up via its "
    "fallback paths, or (b) write the section directly and wrap it in "
    "the standard `<!-- BEGIN: auto-generated Wikidata shrine list -->` "
    "/ `<!-- END: auto-generated Wikidata shrine list -->` markers. If "
    "the page genuinely has no recoverable kanji (this disambiguation "
    "is purely English-context, or the underlying Japanese form is "
    "ambiguous), leave the page as-is — not every shrine disambig has "
    "a clean kanji equivalent."
)

MIRAHEZE_SHRINE_DISAMBIG_INSTRUCTION = (
    "This is a shrine disambiguation page (it contains the "
    "`<!-- BEGIN: auto-generated Wikidata shrine list -->` marker block). "
    "The old human-curated bullet lists inherited from the source-of-import "
    "page are actively confusing — they double-list shrines that already "
    "appear in the auto-generated `== Shrines with this name ==` block, "
    "and they reference link targets that may not exist on this wiki. "
    "Strip them. Keep: a generic-ish intro sentence (a small amount of "
    "shrine-name-specific content is fine, e.g. the kanji and a one-line "
    "explanation), the `{{disambiguation}}` template, the auto-generated "
    "block between the BEGIN/END markers, the wikidata link, and "
    "categories. Drop: the old `* [[...]]` bullet lists above the "
    "auto-generated block and any `== See Also ==` / `== Main ... ==` "
    "sections that just restate the auto-generated content. Process the "
    "miraheze_unique/ file (the canonical source under the dual-sync "
    "model); the next sync will push the cleanup to both wikis."
)

FANDOM_UNIQUE_INSTRUCTION = (
    "Rewrite this page so it renders correctly on shinto.fandom.com. The "
    "miraheze-only templates that don't exist on fandom: `{{ill|...}}`, "
    "`{{wikidata link|...}}`, `{{translated page|...}}`, `{{jalink|...}}`, "
    "and the various `{{...Faith|qq=}}` navboxes that depend on miraheze "
    "modules. Convert `{{ill|TITLE|...lang_codes...|1=DISPLAY}}` and "
    "`{{ill|TITLE|...|lt=DISPLAY|...}}` to plain `[[TITLE|DISPLAY]]` "
    "wikilinks (or `[[TITLE]]` when there's no display-text override). "
    "Drop `{{wikidata link|...}}` and `{{translated page|...}}` entirely — "
    "their content doesn't carry meaning on fandom. Drop "
    "[[Category:Pages with interwikis with duplicate languages]] and any "
    "other miraheze-only maintenance categories. Keep the article body and "
    "standard categories. Don't touch the miraheze_unique/ copy — that's a "
    "separate file under the dual-sync model."
)


# ─── queue builder ─────────────────────────────────────────


def _build_section(
    dir_name: str,
    instruction: str,
    *,
    filter_fn=None,
) -> list[dict]:
    items: list[dict] = []
    directory = REPO_ROOT / dir_name
    if not directory.is_dir():
        return items
    for path in sorted(directory.glob("*.wiki")):
        if filter_fn is not None and not filter_fn(path):
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        items.append(
            {
                "id": rel,
                "file": rel,
                "category": dir_name,
                "instruction": instruction,
            }
        )
    return items


def _is_disambig_or_english_titled(path: Path) -> bool:
    """Filter for fandom_unique/: skip Japanese-titled pages.

    Pages whose stem is pure CJK aren't in scope for the autonomous
    template-fixup pass; the user moves those manually.
    """
    stem = path.stem
    if not stem:
        return False
    cjk_chars = sum(
        1
        for ch in stem
        if "぀" <= ch <= "ゟ"
        or "゠" <= ch <= "ヿ"
        or "㐀" <= ch <= "鿿"
    )
    return cjk_chars <= max(1, len(stem) // 4)


# Marker that ``generate_shrine_disambig_lists.py`` writes around its
# auto-generated bullet block. Used to identify shrine-disambig pages
# in miraheze_unique/ without resorting to filename heuristics.
_SHRINE_DISAMBIG_MARKER = "<!-- BEGIN: auto-generated Wikidata shrine list -->"
_SHRINE_DISAMBIG_CAT_RE = re.compile(
    r"\[\[\s*Category\s*:\s*[Ss]hrine\s+disambiguations?\s*(?:\|[^\]]*)?\]\]"
)


def _is_shrine_disambig(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    return _SHRINE_DISAMBIG_MARKER in text


def _is_shrine_disambig_no_autogen(path: Path) -> bool:
    """Tagged as a shrine disambiguation but missing the auto-gen block."""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    if _SHRINE_DISAMBIG_MARKER in text:
        return False
    return bool(_SHRINE_DISAMBIG_CAT_RE.search(text))


# Kanji extraction logic — mirrors
# ``shinto_miraheze/generate_shrine_disambig_lists.py``'s
# ``extract_kanji_names``. We inline rather than import because the
# script wraps ``sys.stdout`` at module load and that re-wrap detaches
# our own ``io.TextIOWrapper``, closing stdout for any later prints.
# The regex set is small and has been stable; if the script's
# extractor ever grows substantially, sync this copy.
_LEDE_KANJI_RE = re.compile(
    r"^'''([^']+)'''(?:\s+or\s+'''[^']+''')*\s*[（(]([^)）]+)[)）]",
    re.M,
)
_INLINE_BOLD_KANJI_RE = re.compile(r"'''([一-鿿぀-ゟ゠-ヿ々〆〇]+)'''")
_TRANSLATED_PAGE_JA_RE = re.compile(r"\{\{translated page\|ja\|([^|}]+)")
_WIKIDATA_LINK_JA_RE = re.compile(r"\{\{wikidata link\|[^{}]*?\|ja\|([^|}]+)")
_NIHONGO_RE = re.compile(r"\{\{[Nn]ihongo\|[^|}]+\|([^|}]+)")
_MIN_KANJI_LEN = 3


def _add_candidate(out: list[str], seen: set, s: str, *, min_len: int) -> None:
    s = s.strip()
    s = re.sub(r"\s*\([^)]*\)\s*$", "", s)
    if len(s) < min_len:
        return
    cjk_count = sum(
        1 for c in s if "一" <= c <= "鿿" or "぀" <= c <= "ヿ"
    )
    if cjk_count < min_len:
        return
    kanji_count = sum(1 for c in s if "一" <= c <= "鿿" or c in "々〆〇")
    if kanji_count < min(2, min_len):
        return
    if any(c in s for c in "[]{}|=<>"):
        return
    if s in seen:
        return
    seen.add(s)
    out.append(s)


def _extract_kanji_for_path(path: Path) -> list[str]:
    """Return CJK shrine-name candidates extracted from the page text,
    mirroring ``generate_shrine_disambig_lists.extract_kanji_names``."""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    seen: set[str] = set()
    out: list[str] = []

    m = _LEDE_KANJI_RE.search(text)
    if m:
        for tok in re.split(r"[、,;]|\s+or\s+", m.group(2)):
            _add_candidate(out, seen, tok, min_len=_MIN_KANJI_LEN)

    for m in _INLINE_BOLD_KANJI_RE.finditer(text):
        _add_candidate(out, seen, m.group(1), min_len=_MIN_KANJI_LEN)

    # Fallback paths — same as the script, only run if the primary
    # paths produced nothing.
    if not out:
        for m in _TRANSLATED_PAGE_JA_RE.finditer(text):
            _add_candidate(out, seen, m.group(1), min_len=2)
    if not out:
        for m in _WIKIDATA_LINK_JA_RE.finditer(text):
            _add_candidate(out, seen, m.group(1), min_len=2)
    if not out:
        for m in _NIHONGO_RE.finditer(text):
            _add_candidate(out, seen, m.group(1), min_len=2)

    return out


def _build_no_autogen_disambig_items() -> list[dict]:
    """Walk miraheze_unique/ shrine-disambig pages without the auto-gen
    block and split them into kanji-known vs kanji-unknown sub-items.

    Kanji-known: the kanji is embedded directly in the per-item
    instruction so the remote worker can SPARQL right away without
    re-running the extractor.
    Kanji-unknown: the worker has to read the page and decide whether
    a kanji form exists, or leave it alone.
    """
    items: list[dict] = []
    directory = REPO_ROOT / "miraheze_unique"
    if not directory.is_dir():
        return items
    for path in sorted(directory.glob("*.wiki")):
        if not _is_shrine_disambig_no_autogen(path):
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        kanji = _extract_kanji_for_path(path)
        if kanji:
            kanji_repr = ", ".join(f"`{k}`" for k in kanji)
            instruction = (
                MIRAHEZE_SHRINE_DISAMBIG_NO_AUTOGEN_KANJI_KNOWN_TEMPLATE
                .format(kanji_repr=kanji_repr)
            )
            items.append(
                {
                    "id": rel,
                    "file": rel,
                    "category": "miraheze_unique",
                    "subcategory": "shrine_disambig_no_autogen_kanji_known",
                    "kanji": kanji,
                    "instruction": instruction,
                }
            )
        else:
            items.append(
                {
                    "id": rel,
                    "file": rel,
                    "category": "miraheze_unique",
                    "subcategory": "shrine_disambig_no_autogen_kanji_unknown",
                    "instruction": (
                        MIRAHEZE_SHRINE_DISAMBIG_NO_AUTOGEN_KANJI_UNKNOWN_INSTRUCTION
                    ),
                }
            )
    return items


def build_queue() -> list[dict]:
    items: list[dict] = []
    items.extend(_build_section("duplicated_content", DUPLICATED_CONTENT_INSTRUCTION))
    items.extend(_build_section("need_translation", NEED_TRANSLATION_INSTRUCTION))
    items.extend(
        _build_section(
            "fandom_unique",
            FANDOM_UNIQUE_INSTRUCTION,
            filter_fn=_is_disambig_or_english_titled,
        )
    )
    items.extend(
        _build_section(
            "miraheze_unique",
            MIRAHEZE_SHRINE_DISAMBIG_INSTRUCTION,
            filter_fn=_is_shrine_disambig,
        )
    )
    items.extend(_build_no_autogen_disambig_items())
    return items


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--output",
        default=str(QUEUE_PATH),
        help="path to write the queue JSON (default: remote_queue.json at repo root)",
    )
    args = ap.parse_args()

    items = build_queue()
    queue = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "item_count": len(items),
        "items": items,
    }

    out_path = Path(args.output)
    out_path.write_text(json.dumps(queue, indent=2, ensure_ascii=False), encoding="utf-8")
    print(
        f"Wrote {out_path.relative_to(REPO_ROOT) if out_path.is_absolute() else out_path} "
        f"with {len(items)} items "
        f"(duplicated_content + need_translation + fandom_unique [non-CJK titles])."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
