"""The missing-lead section of remote_queue.py.

The bug this guards: `finish_japanese_content_merge.STUB_LEAD` uses lazy `.+?`
groups. On an already-merged page the stub sentence is appended verbatim to the end
of the imported lead, and those groups span the entire line and match anyway.
Reusing it here reported 892 pages needing a lead instead of 149 — it was matching
the 755 pages that had already been merged.
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import remote_queue  # noqa: E402

FORMERLY = "[[Category:Formerly autogenerated pages]]"

STUB = ("{{nihongo|'''Aguchi Shrine'''|阿刀神社}} is a [[shinto shrine]] in the "
        "[[Engishiki Jinmyōchō]]. It is located in [[Yamashiro Province]].")

# What a MERGED page's lead looks like: imported prose, stub sentence appended.
MERGED = ("{{nihongo|'''Tamatsukuri Shrine'''|玉作神社}} is a {{ill|Shinto shrine"
          "|Q845945|qid=Q845945}} located in Numazu. " + STUB)


def write(tmp_path, body):
    p = tmp_path / "Page.wiki"
    p.write_text(body, encoding="utf-8")
    return p


def test_pure_stub_with_no_imported_lead_is_queued(tmp_path):
    body = "{{Shinto shrine}}\n" + STUB + "\n\n== History ==\ntext\n" + FORMERLY
    assert remote_queue._needs_hand_written_lead(write(tmp_path, body))


def test_a_merged_page_is_not_queued(tmp_path):
    """The 755 already-merged pages must not come back."""
    body = MERGED + "\n\n== History ==\ntext\n" + FORMERLY
    assert not remote_queue._needs_hand_written_lead(write(tmp_path, body))


def test_stub_regex_does_not_span_a_merged_line():
    """Directly pins the lazy-group trap."""
    assert remote_queue._PURE_STUB.match(STUB)
    assert not remote_queue._PURE_STUB.match(MERGED)


def test_page_with_an_imported_lead_is_not_queued(tmp_path):
    body = ("'''Aguchi Shrine''' (あぐちじんじゃ) is a shrine in Kyoto.\n" + STUB
            + "\n\n== History ==\n" + FORMERLY)
    assert not remote_queue._needs_hand_written_lead(write(tmp_path, body))


def test_page_without_the_category_is_not_queued(tmp_path):
    body = "{{Shinto shrine}}\n" + STUB + "\n\n== History ==\ntext\n"
    assert not remote_queue._needs_hand_written_lead(write(tmp_path, body))


def test_stub_without_the_province_sentence_still_matches():
    line = ("{{nihongo|'''X Shrine'''|漢字}} is a [[shinto shrine]] in the "
            "[[Engishiki Jinmyōchō]].")
    assert remote_queue._PURE_STUB.match(line)


def test_a_bolded_sentence_deeper_in_the_article_is_not_a_lead():
    """IMPORTED_LEAD must not fire on a subsection's bolded opening."""
    assert not remote_queue._IMPORTED_LEAD.match(
        "'''Ashiinaba-no-Kami''' (あしいなば) enshrined here since antiquity.")


def test_once_the_lead_is_written_the_item_leaves_the_queue(tmp_path):
    """Statefulness is the file's shape — no cursor, no category to strip."""
    before = "{{Shinto shrine}}\n" + STUB + "\n\n== History ==\n" + FORMERLY
    path = write(tmp_path, before)
    assert remote_queue._needs_hand_written_lead(path)

    after = ("{{Shinto shrine}}\n{{nihongo|'''Aguchi Shrine'''|阿刀神社}} is a shrine "
             "in Kyoto, listed in the [[Engishiki Jinmyōchō]].\n\n== History ==\n"
             + FORMERLY)
    path.write_text(after, encoding="utf-8")
    assert not remote_queue._needs_hand_written_lead(path)


def test_instruction_forbids_removing_the_category_and_inventing_facts():
    text = remote_queue.MISSING_LEAD_INSTRUCTION
    assert "do not remove [[Category:Formerly autogenerated pages]]" in text
    assert "do not invent" in text
