"""The spec for this transform is Emma's own edit.

`fixtures/tamatsukuri_{before,after}.wiki` are revisions 3825479 and 3828659 of
[[Tamatsukuri Shrine (Q134930396)]] on shinto.miraheze.org — the bot's output, and
what Emma hand-corrected it into on 2026-07-09 telling us "look at the history to
see my last two edits that I did that actually changed it to the desired form".

`transform()` must reproduce the "after" byte for byte, modulo the category she
asked for afterwards. If a rule is wrong, this test fails.
"""

import io
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import finish_japanese_content_merge as m  # noqa: E402

FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def _fixture(name):
    return io.open(os.path.join(FIXTURES, name), encoding="utf-8").read()


def test_reproduces_emmas_edit_byte_for_byte():
    before = _fixture("tamatsukuri_before.wiki")
    after = _fixture("tamatsukuri_after.wiki")
    got, outcome = m.transform(before)
    assert outcome == "merged"
    # transform() also adds the category Emma asked for on a later message; her
    # revision predates that, so strip it before comparing.
    got = got.replace(m.NEW_CATEGORY + "\n", "")
    assert got == after


def test_the_new_category_is_added():
    got, _ = m.transform(_fixture("tamatsukuri_before.wiki"))
    assert m.NEW_CATEGORY in got
    # and it sits above the git-synced tag, not after it
    assert got.index(m.NEW_CATEGORY) < got.index(m.GIT_SYNCED_CAT)


def test_category_add_is_idempotent():
    once, _ = m.transform(_fixture("tamatsukuri_before.wiki"))
    assert once.count(m.NEW_CATEGORY) == 1


def test_headings_are_promoted_and_categories_heading_removed():
    got, _ = m.transform(_fixture("tamatsukuri_before.wiki"))
    assert "== Overview ==" in got and "=== Overview ===" not in got
    assert "== Enshrined deities ==" in got and "=== Enshrined deities ===" not in got
    assert "== Categories ==" not in got
    assert "== Japanese content ==" not in got


def test_otheruses_hatnote_is_dropped():
    got, _ = m.transform(_fixture("tamatsukuri_before.wiki"))
    assert "{{Otheruses" not in got


def test_infobox_interwiki_and_categories_survive():
    got, _ = m.transform(_fixture("tamatsukuri_before.wiki"))
    assert "{{Infobox religious building" in got
    assert "[[ja:玉作神社]]" in got
    assert "{{wikidata link|Q134930396|ja|玉作神社|check_date=2026-05-26}}" in got
    assert "[[Category:Shikinaisha in Izu Province]]" in got
    assert "[[Category:History of Numazu]]" in got


def test_lead_is_left_alone_when_there_is_no_imported_lead():
    """Blanking a stub lead with nothing to merge into would destroy the lead.

    151 of the 905 pages open straight into {{Shinto shrine}} with no
    '''Name''' (kana) is ... sentence at all.
    """
    text = (
        "{{nihongo|'''X Shrine'''|X神社}} is a [[shinto shrine]] in the "
        "[[Engishiki Jinmyōchō]]. It is located in [[Ise Province]].\n"
        "\n== Japanese content ==\n{{Shinto shrine\n|Name = X\n}}\n"
        "== Overview ==\nBody.\n"
    )
    got, outcome = m.transform(text)
    assert outcome.startswith("lead-untouched")
    assert "{{nihongo|'''X Shrine'''|X神社}} is a [[shinto shrine]]" in got
    assert "== Japanese content ==" not in got  # heading work still applied


def test_a_bolded_sentence_deeper_in_the_article_is_not_treated_as_the_lead():
    """Real page shapes: '''Ashiinaba-no-Kami''' (...) is enshrined as ... etc.

    Only a lead in LEAD POSITION (before the first subheading) may be rewritten.
    """
    text = (
        "{{nihongo|'''A Shrine'''|A神社}} is a [[shinto shrine]] in the "
        "[[Engishiki Jinmyōchō]]. It is located in [[Ise Province]].\n"
        "\n== Japanese content ==\n{{Shinto shrine\n|Name = A\n}}\n"
        "== Enshrined deities ==\n"
        "'''A-no-Kami''' (あのかみ) is enshrined as the principal deity.\n"
    )
    got, outcome = m.transform(text)
    assert outcome.startswith("lead-untouched")
    assert "'''A-no-Kami''' (あのかみ) is enshrined" in got  # untouched
    assert "{{nihongo|'''A Shrine'''|A神社}}" in got


def test_two_stub_leads_are_refused():
    """Two concatenated autogenerated pages (Mifune Shrine, Oyama Otsu Shrine)."""
    stub = ("{{nihongo|'''M Shrine'''|M神社}} is a [[shinto shrine]] in the "
            "[[Engishiki Jinmyōchō]]. It is located in [[Ise Province]].\n")
    text = stub + "\n" + stub + "\n== Japanese content ==\n" \
        "'''M Shrine''' (えむじんじゃ) is a shrine.\n"
    got, outcome = m.transform(text)
    assert outcome.startswith("lead-untouched")
    assert got.count("{{nihongo|'''M Shrine'''|M神社}}") == 2  # nothing merged away


def test_pages_without_a_japanese_content_heading_are_untouched():
    text = "{{Infobox}}\n\nSome page.\n\n[[Category:Git synced pages]]\n"
    got, outcome = m.transform(text)
    assert outcome == "no-japanese-content"
    assert got == text


@pytest.mark.parametrize("heading", ["== Japanese content ==", "==Japanese content==", "== Japanese content  =="])
def test_heading_variants_are_recognised(heading):
    text = f"Lead.\n\n{heading}\n== Body ==\nx\n"
    got, outcome = m.transform(text)
    assert outcome != "no-japanese-content"
    assert "Japanese content" not in got


def test_level4_heading_is_promoted_not_mangled():
    """`^===(.+?)===$` also matches `==== Sub ====` and yields `== = Sub = ==`.

    That corrupted 30 pages before it was caught. Levels go up by exactly one.
    """
    assert m.promote_heading("==== Sub ====") == "=== Sub ==="
    assert m.promote_heading("=== Overview ===") == "== Overview =="
    assert m.promote_heading("===== Deep =====") == "==== Deep ===="


def test_level2_heading_is_left_alone():
    """Promoting `== X ==` to `= X =` would wreck pages whose import used level 2."""
    assert m.promote_heading("== Overview ==") == "== Overview =="
    assert m.promote_heading("== Categories ==") == "== Categories =="


def test_promote_heading_ignores_non_headings():
    assert m.promote_heading("Some prose === not a heading") == "Some prose === not a heading"
    assert m.promote_heading("") == ""
    assert m.promote_heading("=== ===") == "=== ==="  # empty body: leave alone
    assert m.promote_heading("=== Unbalanced ====") == "=== Unbalanced ===="


def test_no_page_gains_a_mangled_heading():
    text = (
        "{{nihongo|'''X Shrine'''|X神社}} is a [[shinto shrine]] in the "
        "[[Engishiki Jinmyōchō]]. It is located in [[Ise Province]].\n"
        "\n== Japanese content ==\n"
        "'''X Shrine''' (えっくす) is a shrine.\n"
        "=== History ===\nBody.\n==== Early ====\nMore.\n"
    )
    got, _ = m.transform(text)
    assert "== History ==" in got and "=== History ===" not in got
    assert "=== Early ===" in got and "==== Early ====" not in got
    assert "== = " not in got


def test_every_japanese_content_heading_is_removed():
    """Mifune Shrine (Taki) is two autogenerated pages concatenated."""
    text = "Lead.\n== Japanese content ==\nA\n== Japanese content ==\nB\n"
    got, _ = m.transform(text)
    assert "Japanese content" not in got
