#!/usr/bin/env python3
"""
generate_inochi_shrine.py
=========================
Inochi Shrine (Q141677508) and its deity, as ordinary generator output.

Emma, 2026-10-08. She created the shrine by hand as Q141677508 ("Yes I fucking know
it is a slightly wrong name"), and asked for two things to happen through the normal
batch, not by hand:

1. **The deity is created in the next QuickStatements batch "as a part of the
   logic".** A CREATE block for 命之命 / "Inochi no Mikoto", P31 kami (Q524158),
   P21 male (Q6581097), plus `Q141677508|P825|LAST` so the shrine is dedicated to
   it. Written to `inochi_creates.txt`, which is registered in
   `create_items.GATES`, so `site/build_qs_home.py` puts the block on the batch
   page. The block is emitted ONLY while the shrine has no P825: the hand-run batch
   never writes a create `.state`, so without this check every round would create
   another deity.

2. **"github actions should in two weeks set Len Inochi Shrine and Lja 命神社."**
   From LABELS_FROM (2026-10-22) on, `inochi_labels.txt` (an ATOMIC_FILES drip file)
   carries `Q141677508|Len|"Inochi Shrine"` and `Q141677508|Lja|"命神社"`, each only
   while the live label differs. Before that date the file is empty.

One SPARQL query per run. GENERATOR ONLY: writes `.txt` files, never edits Wikidata.
"""

import os as _uos, sys as _usys
_uar = _uos.path.dirname(_uos.path.abspath(__file__))
while _uar != _uos.path.dirname(_uar) and not _uos.path.isdir(_uos.path.join(_uar, "shinto_miraheze")):
    _uar = _uos.path.dirname(_uar)
if _uar not in _usys.path:
    _usys.path.insert(0, _uar)

import datetime
import io
import os
import sys

import wdqs_transport

HERE = os.path.dirname(os.path.abspath(__file__))
CREATES = os.path.join(HERE, "inochi_creates.txt")
LABELS = os.path.join(HERE, "inochi_labels.txt")

SHRINE = "Q141677508"
LABELS_FROM = datetime.date(2026, 10, 22)
WANT_LABELS = {"en": "Inochi Shrine", "ja": "命神社"}

DEITY_BLOCK = [
    "CREATE",
    'LAST|Lja|"命之命"',
    'LAST|Len|"Inochi no Mikoto"',
    "LAST|P31|Q524158",
    "LAST|P21|Q6581097",
    f"{SHRINE}|P825|LAST",
]

QUERY = f"""SELECT ?lang ?label (BOUND(?d) AS ?hasDeity) WHERE {{
  OPTIONAL {{ wd:{SHRINE} rdfs:label ?label . BIND(LANG(?label) AS ?lang)
             FILTER(LANG(?label) IN ("en", "ja")) }}
  OPTIONAL {{ wd:{SHRINE} p:P825 ?d }}
}}"""


def read_state(rows):
    """({lang: label}, has_deity) from the query rows."""
    labels, has_deity = {}, False
    for b in rows:
        if "lang" in b and "label" in b:
            labels[b["lang"]["value"]] = b["label"]["value"]
        if b.get("hasDeity", {}).get("value") == "true":
            has_deity = True
    return labels, has_deity


def build(labels, has_deity, today):
    creates = [] if has_deity else list(DEITY_BLOCK)
    label_lines = []
    if today >= LABELS_FROM:
        for lang, want in WANT_LABELS.items():
            if labels.get(lang) != want:
                label_lines.append(f'{SHRINE}|L{lang}|"{want}"')
    return creates, label_lines


def main():
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    labels, has_deity = read_state(wdqs_transport.query(QUERY))
    creates, label_lines = build(labels, has_deity, datetime.date.today())
    with io.open(CREATES, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# Inochi Shrine's deity (Emma 2026-10-08). Generated by generate_inochi_shrine.py;\n"
                 "# empty once Q141677508 has a P825.\n")
        if creates:
            fh.write("\n".join(creates) + "\n")
    with io.open(LABELS, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(label_lines) + ("\n" if label_lines else ""))
    print(f"shrine labels now: {labels}; has P825: {has_deity}")
    print(f"wrote {CREATES}: {'1 CREATE block' if creates else 'no block'}")
    print(f"wrote {LABELS}: {len(label_lines)} label line(s) (date-gated from {LABELS_FROM})")


if __name__ == "__main__":
    main()
