"""Every atomic file is either regenerated by CI or a declared one-shot batch.

`direct_daily_edits.ATOMIC_FILES` is the whole list of things the daily drip may
sample from. A file on it that nothing regenerates is a **frozen snapshot**: it
keeps re-offering lines that have already landed, and it never picks up new work.

That has happened twice in a week. `generate_invalid_p825_removals.py` and
`generate_ronsha_role_qualifiers.py` were both written, both registered here, and
neither was wired into `generate-quickstatements.yml` for several commits —
`test_invalid_p825.py` catches exactly those two, by name, which does nothing for
the next one. This asks the question of all 82.

**Deliberately narrow.** It checks WIRING, not yield. Both real defects found on
2026-09-13 were inside generators that run every day and were producing nothing
(a `^\\+(\\d{4})-` parse against a WDQS literal that has no plus; a backup list
that could not see the index) — no wiring check can see either, and pretending
otherwise would make this test a comfort rather than a guard. What it does catch
is a generator that exists and is never invoked.

The two one-shot batches below are not a defect and are not "unwired": they are
parses of a fixed source, done once. They are listed rather than inferred so that
adding a third is a decision someone makes on purpose.
"""

import glob
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MQ = os.path.dirname(HERE)
ROOT = os.path.dirname(MQ)

# Not generated, and correctly so. Each is a one-shot parse of a fixed source.
ONE_SHOT = {
    "bunrei_onkamui.txt":
        "parse_onkamui_bunrei.py — one parse of the onkamui bunrei list, like its "
        "five bunrei_* siblings. The source does not change, so neither does the file.",
    "recreation_relations.txt":
        "recreate-deleted-wikidata/. The referenced deleted items were recreated "
        "2026-07-06 and Emma ruled the ~213 unreferenced ones are NOT to be "
        "recreated. Emptied by aa10dd93 once every line had landed; stays empty.",
    "durability_backlinks.txt":
        "28 hand-written P3373/P40 reciprocal backlinks for orphaned 2026-created "
        "items, checked by hand before dripping. Emptied by aa10dd93 alongside "
        "recreation_relations once every line had landed. Nothing generates it "
        "because nothing was ever meant to — it was one audit's output.",
}

# Filenames built by string concatenation rather than written literally. The
# ranking generator does `base = output_file.rsplit(".", 1)[0]` and then
# f"{base}_remove.txt" / f"{base}_underspecified_remove.txt", so grepping for the
# full name finds nothing even though the file is regenerated daily.
CONCAT_SUFFIXES = ("_remove.txt", "_underspecified_remove.txt")


def _atomic_files():
    sys.path.insert(0, MQ)
    spec = importlib.util.spec_from_file_location(
        "_dde_atomic", os.path.join(MQ, "direct_daily_edits.py"))
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except SystemExit:  # the lockout guard, if it ever runs at import time
        pass
    return sorted(mod.ATOMIC_FILES)


def _sources():
    """{basename: source} for every .py in the repo that could write a batch."""
    out = {}
    for pattern in ("*.py", "*/*.py"):
        for path in glob.glob(os.path.join(ROOT, pattern)):
            rel = os.path.relpath(path, ROOT).replace("\\", "/")
            if "/tests/" in rel or rel.startswith("tests/"):
                continue
            base = os.path.basename(path)
            if base in ("direct_daily_edits.py", "submit_daily_batch.py"):
                continue  # these READ the list; they do not produce it
            with open(path, encoding="utf-8", errors="replace") as fh:
                out[base] = fh.read()
    return out


def _workflow_text():
    return "\n".join(
        open(p, encoding="utf-8", errors="replace").read()
        for p in glob.glob(os.path.join(ROOT, ".github", "workflows", "*.yml")))


def _writers(filename, sources):
    """Scripts that name this file, directly or through the concat pattern."""
    named = {n for n, src in sources.items() if filename in src}
    if named:
        return named
    for suffix in CONCAT_SUFFIXES:
        if filename.endswith(suffix):
            stem = filename[: -len(suffix)] + ".txt"
            hits = {n for n, src in sources.items()
                    if stem in src and f'_remove.txt"' in src}
            if hits:
                return hits
    return set()


def _is_wired(script, workflows):
    """A workflow may invoke it as `foo.py` or as a bare stem in a shell loop —
    `for c in collect_name_in_kana collect_beppyo_p612; do python3 "…/$c.py"`.
    Matching only the filename reports five healthy collectors as unwired.

    ⚠ The lookbehind must NOT exclude `/`. Most steps invoke a generator by path —
    `python shinto_miraheze/generate_french_elision_fixes.py` — and a first draft
    that rejected a preceding slash reported two daily-running generators as
    dead."""
    stem = script[:-3]
    return bool(re.search(r"(?<![\w-])" + re.escape(stem) + r"(?![\w-])", workflows))


def test_every_atomic_file_has_a_writer_ci_runs():
    sources, workflows = _sources(), _workflow_text()
    orphaned, unwired = [], []
    for filename in _atomic_files():
        if filename in ONE_SHOT:
            continue
        writers = _writers(filename, sources)
        if not writers:
            orphaned.append(filename)
        elif not any(_is_wired(w, workflows) for w in writers):
            unwired.append(f"{filename} (writers: {sorted(writers)})")

    assert not orphaned, (
        "these are on ATOMIC_FILES and no script writes them, so the drip is "
        f"sampling a file nothing maintains: {orphaned}. If one is a deliberate "
        "one-shot batch, add it to ONE_SHOT with the reason.")
    assert not unwired, (
        "these have a generator that no workflow invokes, so their content is a "
        f"frozen snapshot — the file re-offers landed lines forever: {unwired}")


def test_the_one_shot_list_does_not_outlive_its_files():
    """A stale exemption is worse than none: it silently excuses whatever takes
    the name next."""
    atomic = set(_atomic_files())
    stale = sorted(set(ONE_SHOT) - atomic)
    assert not stale, (
        f"ONE_SHOT exempts files that are no longer atomic at all: {stale}")


def test_the_exemption_is_a_short_list_with_reasons():
    """It is an exemption from being regenerated. If it grows, the rule has
    stopped meaning anything and the growth is the thing to look at."""
    assert len(ONE_SHOT) <= 4, (
        f"{len(ONE_SHOT)} one-shot batches now; that is enough of them to be a "
        "pattern rather than an exception — decide whether they should be "
        "generated before adding more")
    for name, why in ONE_SHOT.items():
        assert len(why) > 40, f"{name} is exempted without a real reason"
