#!/usr/bin/env python3
"""
create_categories_evolutionism.py
=================================
Creates wanted categories on evolutionism.miraheze.org.
Each category page will contain only: [[Category:Early January autogenerated wanted categories]]
"""

import mwclient
import sys
import time

# Fix Unicode encoding issues on Windows
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Configuration
WIKI_URL = 'evolutionism.miraheze.org'
WIKI_PATH = '/w/'
USERNAME = 'Immanuelle'
PASSWORD = '[REDACTED_SECRET_2]'
SLEEP = 1.5  # seconds between edits

CATEGORY_CONTENT = "[[Category:Early January autogenerated wanted categories]]"

CATEGORIES = [
    "Pages with script errors",
    "Wikipedia template categories",
    "Stubs",
    "20th century",
    "21st century",
    "19th century",
    "18th century",
    "11th century",
    "12th century",
    "15th century",
    "16th century",
    "13th century",
    "14th century",
    "17th century",
    "10th century",
    "3rd century",
    "2nd century",
    "6th century",
    "4th century",
    "5th century",
    "7th century",
    "8th century",
    "9th century",
    "Categories created on Nov 28 2025",
    "1st century",
    "Pages with reference errors",
    "Infobox templates",
    "Use dmy dates",
    "11380s",
    "11410s",
    "11420s",
    "11440s",
    "11450s",
    "11460s",
    "11480s",
    "11490s",
    "11500s",
    "11520s",
    "11530s",
    "11540s",
    "11560s",
    "11570s",
    "11590s",
    "11600s",
    "11620s",
    "11630s",
    "11640s",
    "11660s",
    "11670s",
    "11680s",
    "11710s",
    "11720s",
    "11740s",
    "11750s",
    "11770s",
    "11780s",
    "11810s",
    "11820s",
    "11840s",
    "11850s",
    "11860s",
    "11880s",
    "11890s",
    "11900s",
    "11920s",
    "11930s",
    "11940s",
    "11960s",
    "11970s",
    "11990s",
    "12000s",
    "12020s",
    "12030s",
    "12040s",
    "12060s",
    "12070s",
    "12080s",
    "Sagittarius Hanukkah",
    "All accuracy disputes",
    "2022",
    "All stub articles",
    "All pages needing cleanup",
    "Navigational box metatemplates",
    "Redirects connected to a Evolutionism Wiki item",
    "Articles with unsourced statements from August 2022",
    "Articles with unsourced statements from February 2022",
    "Articles with unsourced statements from September 2022",
    "Lonely Pages 2025-12-06",
    "Not real year types",
    "Sidebar templates",
    "Under Review",
    "Wikipedia navigation templates",
    "-1s",
    "-2s",
    "-3s",
    "-4s",
    "-5s",
    "-6s",
    "-7s",
    "-8s",
    "-9s",
    "11",
    "12100s",
    "17th-century BC pharaohs",
    "1s",
    "2017",
    "240s births",
    "2s",
    "320s deaths",
    "3rd-century Greek philosophers",
    "3rd-century Romans",
    "3rd-century mathematicians",
    "4s",
    "4th-century Greek philosophers",
    "4th-century Romans",
    "4th-century mathematicians",
    "4th-century philosophers",
    "5s",
    "Accuracy disputes",
    "Actual Terms",
    "American people of Czech descent",
    "American people of English descent",
    "American people of Lebanese descent",
    "American people of Polish descent",
    "American people of Scottish descent",
    "American people of Ukrainian descent",
    "Ancient slaves",
    "Apamea, Syria",
    "Articles lacking in-text citations from November 2021",
    "Articles needing additional references from January 2024",
    "Articles with disputed statements from November 2023",
    "Articles with unsourced statements from November 2024",
    "Category series navigation isolated",
    "Category series navigation year and decade",
    "Children of Jacob",
    "Common Terms",
    "Contains Content Warning",
    "Dfa gateways",
    "Disorder-Related Terms",
    "Dissociation-Related Terms",
    "Five Dragon Boat Festivals'",
    "Founders of biblical tribes",
    "Greek-language commentators on Plato",
    "Hebrew Bible prophets of the Quran",
    "Historical period subtemplates",
    "History of magic",
    "Intercalary months",
    "Joseph (Genesis)",
    "Neo-Pythagoreans",
    "Neoplatonists",
    "Not Plural Exclusive",
    "Occult writers",
    "Pagan anti-Gnosticism",
    "Pages using navbox columns without the first column",
    "Pages where template include size is exceeded",
    "Pages with no translate target",
    "Pages with numeric Bible version references",
    "People from Avaris",
    "People from Roman Syria",
    "Pharaohs of the Fifteenth Dynasty of Egypt",
    "Polycyclic aromatic hydrocarbons",
    "Psychiatric Terms",
    "Q",
    "Short description is different from Wikidata",
    "Short description matches Wikidata",
    "Syrian philosophers",
    "System Function Terms",
    "TED speaker template missing ID and not in Wikidata",
    "Template Category TOC without CatAutoTOC on category with 601–900 pages",
    "Terms",
    "Terms that may be used as nouns",
    "Terms with a known coiner",
    "Terms with synonyms or alternate forms",
    "Theurgy",
    "Use dmy dates from January 2019",
    "Wikipedia-internal sidebar templates",
    "Wikipedia articles needing clarification from March 2023",
    "Wisdom literature",
    "Year of death uncertain",
]

def main():
    print(f"Total categories to create: {len(CATEGORIES)}\n")

    print(f"Connecting to {WIKI_URL}...")
    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent='ShintoWikiBot/1.0 (immanuelle@shinto.miraheze.org)')
    site.login(USERNAME, PASSWORD)
    print("Logged in successfully\n")

    total = len(CATEGORIES)
    success = 0
    failed = 0
    skipped = 0

    for i, cat_name in enumerate(CATEGORIES, 1):
        page_title = f"Category:{cat_name}"
        print(f"[{i}/{total}] {page_title}", end=" ... ", flush=True)

        try:
            page = site.pages[page_title]
            if page.exists:
                print("SKIPPED (already exists)")
                skipped += 1
            else:
                page.save(CATEGORY_CONTENT, summary="Bot: Create wanted category")
                print("OK")
                success += 1
        except Exception as e:
            print(f"FAILED: {e}")
            failed += 1

        time.sleep(SLEEP)

    print(f"\n{'='*50}")
    print(f"Summary: {success} created, {skipped} skipped, {failed} failed out of {total}")

if __name__ == "__main__":
    main()
