#!/usr/bin/env python3
"""Process duplicated_content/*.wiki files to merge duplicated sections."""
import os
import re
import sys
from pathlib import Path

DUPL_CAT = '[[Category:Pages with duplicated content]]'
MAX_SIZE = 100_000  # skip files > 100KB

MERGE_MARKERS = [
    '== Japanese Wikipedia content ==',
    '== AUTOGENERATED CONTENT FROM WIKIDATA ==',
    '==Merged second translation==',
    '==merged content==',
    '== Accidentally Overwritten Content ==',
]

def extract_categories(text):
    """Return unique category strings (by name, ignoring sort key), preserving first-seen order."""
    cats_ordered = []
    seen_names = set()
    for m in re.finditer(r'\[\[Category:([^\|\]]+)(?:\|[^\]]+)?\]\]', text):
        cat_name = m.group(1).strip()
        full_tag = m.group(0)
        if cat_name not in seen_names:
            seen_names.add(cat_name)
            cats_ordered.append(full_tag)
    return cats_ordered

def strip_category_lines(lines):
    """Remove lines whose non-whitespace content consists only of [[Category:...]] tags."""
    result = []
    for line in lines:
        remaining = re.sub(r'\[\[Category:[^\]]+\]\]', '', line).strip()
        if remaining:
            result.append(line)
        # else: line is only categories - drop it
    return result

def find_shikinaisha_table(text):
    """Return the full == Shikinaisha ... == section text, or None."""
    m = re.search(r'(== Shikinaisha[^\n]*==\n(?:.*\n)*?\|\})', text)
    if m:
        return m.group(0)
    return None

def has_shikinaisha(text):
    return bool(re.search(r'== Shikinaisha', text, re.IGNORECASE))

def trim_trailing_blank(lines):
    while lines and not lines[-1].strip():
        lines.pop()
    return lines

def process_file(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"  ERROR reading {filepath}: {e}", file=sys.stderr)
        return 'error'

    if DUPL_CAT not in content:
        return 'skip'  # already processed

    if len(content) > MAX_SIZE:
        return 'large'  # leave for another run

    lines = content.split('\n')

    # Find first merge marker
    marker_idx = None
    marker_type = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        for marker in MERGE_MARKERS:
            if stripped == marker:
                marker_idx = i
                marker_type = marker
                break
        if marker_idx is not None:
            break

    # Collect ALL categories from the whole file, deduplicated, minus dupl-content
    all_cats = [c for c in extract_categories(content)
                if 'Pages with duplicated content' not in c]

    if marker_idx is None:
        # No merge marker: just dedup categories
        clean = strip_category_lines(lines)
        trim_trailing_blank(clean)
        result_lines = clean + [''] + all_cats
        result = '\n'.join(result_lines) + '\n'
        if result == content:
            return 'unchanged'
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(result)
        return 'merged'

    primary_lines = lines[:marker_idx]
    secondary_lines = lines[marker_idx + 1:]  # skip marker line itself

    if marker_type == '== Accidentally Overwritten Content ==':
        # Secondary IS the translated article; primary is the Wikidata stub.
        # Keep secondary, but integrate Shikinaisha table from primary stub.
        # If secondary has ANOTHER marker, take only up to it.
        next_marker_idx = None
        for i, ln in enumerate(secondary_lines):
            if ln.strip() in MERGE_MARKERS:
                next_marker_idx = i
                break
        if next_marker_idx is not None:
            secondary_lines = secondary_lines[:next_marker_idx]

        body_lines = strip_category_lines(secondary_lines)
        trim_trailing_blank(body_lines)

        # Integrate Shikinaisha table from primary if body lacks it
        primary_text = '\n'.join(primary_lines)
        body_text = '\n'.join(body_lines)
        if not has_shikinaisha(body_text):
            ski = find_shikinaisha_table(primary_text)
            if ski:
                # Insert before == References or {{translated page}}, whichever comes first
                insert_at = len(body_lines)
                for i, ln in enumerate(body_lines):
                    if re.match(r'== References', ln.strip()) or ln.strip().startswith('{{translated page'):
                        insert_at = i
                        break
                body_lines = body_lines[:insert_at] + ['', ski, ''] + body_lines[insert_at:]

        result_lines = body_lines

    else:
        # Keep primary, discard secondary
        body_lines = strip_category_lines(primary_lines)
        trim_trailing_blank(body_lines)

        # For AUTOGENERATED: integrate Shikinaisha table from secondary if primary lacks it
        if marker_type == '== AUTOGENERATED CONTENT FROM WIKIDATA ==':
            body_text = '\n'.join(body_lines)
            if not has_shikinaisha(body_text):
                secondary_text = '\n'.join(secondary_lines)
                ski = find_shikinaisha_table(secondary_text)
                if ski:
                    # Insert before {{translated page}} or before end
                    insert_at = len(body_lines)
                    for i, ln in enumerate(body_lines):
                        if ln.strip().startswith('{{translated page'):
                            insert_at = i
                            break
                    body_lines = body_lines[:insert_at] + ['', ski, ''] + body_lines[insert_at:]

        result_lines = body_lines

    # Assemble final content
    trim_trailing_blank(result_lines)
    result_lines.append('')
    result_lines.extend(all_cats)
    result = '\n'.join(result_lines) + '\n'

    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(result)
    except Exception as e:
        print(f"  ERROR writing {filepath}: {e}", file=sys.stderr)
        return 'error'

    return 'merged'


def main():
    dc = Path('duplicated_content')
    files = sorted(dc.glob('*.wiki'))

    counts = {'merged': 0, 'skip': 0, 'large': 0, 'unchanged': 0, 'error': 0}
    for fp in files:
        result = process_file(fp)
        counts[result] += 1
        if result == 'merged':
            print(f"  merged: {fp.name}")
        elif result == 'large':
            print(f"  LARGE (skipped): {fp.name}")
        elif result == 'error':
            print(f"  ERROR: {fp.name}")

    print(f"\nDone: {counts}")
    print(f"  Merged (category removed): {counts['merged']}")
    print(f"  Large (skipped):           {counts['large']}")
    print(f"  Already done:              {counts['skip']}")
    print(f"  Unchanged (no-op):         {counts['unchanged']}")
    print(f"  Errors:                    {counts['error']}")

if __name__ == '__main__':
    main()
