#!/usr/bin/env python3
"""
find_duplicate_page_qids.py
============================
Renders the [[Duplicate page QIDs]] wiki report from the shared dict
maintained by ``orchestrators.ops.duplicate_qids``. Each orchestrator
(mainspace, category, template, miscellaneous) visits every page in its
namespace once per cycle and the collector op records ``title -> QID``
in ``shinto_miraheze/orchestrators/duplicate_qids.state`` (JSON). This
renderer groups that dict by QID and writes any QID claimed by more
than one title to the report page.

Before rendering, every title in a duplicate group is re-verified
against the live wiki — entries that are now redirects, deleted, or
no longer carry ``{{wikidata link|Q...}}`` are pruned from the state.
Without this, the orchestrators' slow per-namespace sweep (capped at
1000 pages/run) leaves stale entries on the report for many cycles
after a merge or deletion, and deleted pages NEVER get cleaned up by
the orchestrator (the per-page op is skipped for non-existent pages).

Standard flags: ``--apply`` (default dry-run), ``--max-edits`` (always
1 — there is one write, to the report page), ``--run-tag``.
"""

import os as _uos, sys as _usys
_uar = _uos.path.dirname(_uos.path.abspath(__file__))
while _uar != _uos.path.dirname(_uar) and not _uos.path.isdir(_uos.path.join(_uar, "shinto_miraheze")):
    _uar = _uos.path.dirname(_uar)
if _uar not in _usys.path:
    _usys.path.insert(0, _uar)
from shinto_miraheze.user_agent import USER_AGENT
import argparse
import io
import json
import os
import re
import sys
import time
from collections import defaultdict

import mwclient
from wiki_login import login_with_retry

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

WDLINK_RE = re.compile(r"\{\{\s*wikidata\s*link\s*\|\s*(Q\d+)", re.IGNORECASE)
# Light read throttle for the verification pass — dozens to a few
# hundred titles in batches of 50 is small compared to the per-page
# orchestrator walks, but we still pace API queries.
READ_THROTTLE = 0.3
# Max titles per `query&titles=...` API call. MediaWiki accepts up to
# 50 for normal users, 500 for bots. EmmaBot has the bot flag.
QUERY_BATCH = 50

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL = "shinto.miraheze.org"
WIKI_PATH = "/w/"
USERNAME = os.getenv("WIKI_USERNAME", "EmmaBot")
PASSWORD = os.getenv("WIKI_PASSWORD", "")
THROTTLE = 2.5


REPORT_TITLE = "Duplicate page QIDs"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STATE_FILE = os.path.join(SCRIPT_DIR, "orchestrators", "duplicate_qids.state")


# ─── MAIN ──────────────────────────────────────────────────

def build_report(duplicates, total_tracked, unique_qids):
    lines = [
        "{{DISPLAYTITLE:Duplicate page QIDs}}",
        "Pages that share a Wikidata QID with at least one other page. "
        "Auto-generated by [[User:EmmaBot]] — do not edit manually. "
        "Source: the ``duplicate_qids`` op running on every page visited "
        "by the four namespace orchestrators.",
        "",
        f"* Pages tracked: '''{total_tracked}'''",
        f"* Distinct QIDs: '''{unique_qids}'''",
        f"* Duplicated QIDs: '''{len(duplicates)}'''",
        "",
    ]
    if duplicates:
        lines.append("== Duplicates ==")
        lines.append("")
        for qid in sorted(duplicates, key=lambda q: (-len(duplicates[q]), q)):
            pages = sorted(duplicates[qid])
            lines.append(f"=== [[d:{qid}|{qid}]] ({len(pages)} pages) ===")
            for p in pages:
                lines.append(f"* [[{p}]]")
            lines.append("")
    else:
        lines.append("''No duplicates found.''")
        lines.append("")

    lines.append("[[Category:Maintenance reports]]")
    return "\n".join(lines) + "\n"


def verify_duplicate_groups(site, state: dict) -> tuple[dict, dict]:
    """Re-check every title that's part of a duplicate group against the
    live wiki. Mutates and returns (cleaned_state, stats).

    For each suspect title we ask: does the page exist, is it a hard
    redirect, and what QID (if any) does its current ``{{wikidata
    link|...}}`` template carry? Then:

      - missing/deleted page  → drop entry
      - hard redirect         → drop entry (it isn't a real duplicate any
                                 more — the merge succeeded)
      - no wikidata link      → drop entry
      - different QID         → update entry to the current QID
      - same QID, real page   → keep

    Done in batches of QUERY_BATCH titles per API call, with a small
    READ_THROTTLE between calls so this stays well under the wiki's
    read budget.
    """
    qid_to_pages: dict[str, list[str]] = defaultdict(list)
    for title, qid in state.items():
        qid_to_pages[qid].append(title)
    suspect_titles = sorted(
        {t for ts in qid_to_pages.values() if len(ts) > 1 for t in ts}
    )
    stats = {"checked": len(suspect_titles), "removed_missing": 0,
             "removed_redirect": 0, "removed_no_link": 0,
             "updated_qid": 0, "kept": 0}
    if not suspect_titles:
        return state, stats

    print(f"Verifying {len(suspect_titles)} titles across "
          f"{sum(1 for ts in qid_to_pages.values() if len(ts) > 1)} "
          f"duplicate groups against live wiki")

    for i in range(0, len(suspect_titles), QUERY_BATCH):
        batch = suspect_titles[i:i + QUERY_BATCH]
        try:
            result = site.api(
                "query",
                titles="|".join(batch),
                prop="info|revisions",
                rvprop="content",
                rvslots="main",
                # NOTE: do NOT set redirects=1. We want to see the redirect
                # page itself (so we can detect "this title is now a
                # redirect"), not silently follow to the target.
                formatversion="2",
            )
        except Exception as e:
            print(f"  API error on batch {i // QUERY_BATCH}: {e}; "
                  f"skipping {len(batch)} titles this run")
            time.sleep(READ_THROTTLE)
            continue

        seen_titles: set[str] = set()
        for page in result.get("query", {}).get("pages", []):
            title = page.get("title", "")
            seen_titles.add(title)
            if page.get("missing"):
                if title in state:
                    state.pop(title, None)
                    stats["removed_missing"] += 1
                continue
            if "redirect" in page:
                if title in state:
                    state.pop(title, None)
                    stats["removed_redirect"] += 1
                continue
            revs = page.get("revisions") or []
            content = ""
            if revs:
                slots = revs[0].get("slots") or {}
                main = slots.get("main") or {}
                content = main.get("content", "") or revs[0].get("content", "") or ""
            m = WDLINK_RE.search(content)
            if not m:
                if title in state:
                    state.pop(title, None)
                    stats["removed_no_link"] += 1
                continue
            current_qid = m.group(1).upper()
            if state.get(title) != current_qid:
                state[title] = current_qid
                stats["updated_qid"] += 1
            else:
                stats["kept"] += 1

        # Titles the API didn't return at all (rare — usually a
        # normalization mismatch). Treat as missing so they don't
        # linger forever.
        for t in batch:
            if t not in seen_titles and t in state:
                state.pop(t, None)
                stats["removed_missing"] += 1

        time.sleep(READ_THROTTLE)

    return state, stats


def save_state(path: str, state: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2, sort_keys=True)


def load_state(path: str) -> dict:
    if not os.path.exists(path):
        print(f"State file not found: {path}")
        print("No orchestrator has populated it yet. Nothing to render.")
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"Could not read state file {path}: {e}")
        return {}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="Actually save the report (default: dry-run).")
    parser.add_argument("--max-edits", type=int, default=1,
                        help="Report page count cap (default 1 — there is only "
                             "ever one write).")
    parser.add_argument("--run-tag", required=True,
                        help="Run tag appended to the edit summary for auditing.")
    args = parser.parse_args()

    state = load_state(STATE_FILE)
    print(f"Loaded state: {len(state)} tracked titles before verification")

    # Login before verification — the verification pass needs API
    # access, and we want the same Site for the eventual report save.
    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent=USER_AGENT)
    site.connection.timeout = 120
    login_with_retry(site, USERNAME, PASSWORD)
    print(f"Logged in as {USERNAME}")

    # Re-verify every title in any duplicate group against the live
    # wiki and prune stale entries. Without this, redirects/deletions
    # from completed merges linger on the report for many cycles
    # (deletions never resolve, since the orchestrator's per-page op
    # is skipped for non-existent pages).
    state, verify_stats = verify_duplicate_groups(site, state)
    print(f"Verification: checked={verify_stats['checked']} "
          f"removed_missing={verify_stats['removed_missing']} "
          f"removed_redirect={verify_stats['removed_redirect']} "
          f"removed_no_link={verify_stats['removed_no_link']} "
          f"updated_qid={verify_stats['updated_qid']} "
          f"kept={verify_stats['kept']}")
    if any(verify_stats[k] for k in
           ("removed_missing", "removed_redirect",
            "removed_no_link", "updated_qid")):
        if args.apply:
            save_state(STATE_FILE, state)
            print(f"Saved cleaned state: {len(state)} tracked titles")
        else:
            print(f"[DRY] would save cleaned state: {len(state)} tracked titles")

    total_tracked = len(state)
    qid_to_pages: dict[str, list[str]] = defaultdict(list)
    for title, qid in state.items():
        qid_to_pages[qid].append(title)
    duplicates = {q: ps for q, ps in qid_to_pages.items() if len(ps) > 1}
    unique_qids = len(qid_to_pages)

    print(f"Tracked titles:  {total_tracked}")
    print(f"Distinct QIDs:   {unique_qids}")
    print(f"Duplicated QIDs: {len(duplicates)}")

    report = build_report(duplicates, total_tracked, unique_qids)

    if not args.apply:
        print(f"[DRY] would write {len(duplicates)} dupe entries to [[{REPORT_TITLE}]]")
        return

    page = site.pages[REPORT_TITLE]
    summary = (f"Bot: refresh duplicate page QID report "
               f"({len(duplicates)} dupes across {total_tracked} tracked pages) "
               f"{args.run_tag}")
    page.save(report, summary=summary)
    time.sleep(THROTTLE)
    print(f"Saved [[{REPORT_TITLE}]]")


if __name__ == "__main__":
    main()
