#!/usr/bin/env python3
"""
find_duplicate_page_qids.py
============================
Renders the [[Duplicate page QIDs]] wiki report from the shared dict
maintained by ``orchestrators.ops.duplicate_qids``. Each orchestrator
(mainspace, category, template, miscellaneous) visits every page in its
namespace once per cycle and the collector op records ``title -> QID``
in ``shinto_miraheze/orchestrators/duplicate_qids.state`` (JSON). This
renderer groups that dict by QID and writes any QID claimed by more
than one title to the report page.

No wiki scan happens here — everything is read from the state file
accumulated by the four orchestrators. Runs ONCE per cleanup-loop
cycle, after the last orchestrator (miscellaneous) finishes.

Standard flags: ``--apply`` (default dry-run), ``--max-edits`` (always
1 — there is one write, to the report page), ``--run-tag``.
"""

import argparse
import io
import json
import os
import sys
import time
from collections import defaultdict

import mwclient

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL = "shinto.miraheze.org"
WIKI_PATH = "/w/"
USERNAME = os.getenv("WIKI_USERNAME", "EmmaBot")
PASSWORD = os.getenv("WIKI_PASSWORD", "")
THROTTLE = 2.5

USER_AGENT = "EmmaBot/1.0 (https://shinto.miraheze.org/wiki/User:EmmaBot) shintowiki-scripts"

REPORT_TITLE = "Duplicate page QIDs"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STATE_FILE = os.path.join(SCRIPT_DIR, "orchestrators", "duplicate_qids.state")


# ─── MAIN ──────────────────────────────────────────────────

def build_report(duplicates, total_tracked, unique_qids):
    lines = [
        "{{DISPLAYTITLE:Duplicate page QIDs}}",
        "Pages that share a Wikidata QID with at least one other page. "
        "Auto-generated by [[User:EmmaBot]] — do not edit manually. "
        "Source: the ``duplicate_qids`` op running on every page visited "
        "by the four namespace orchestrators.",
        "",
        f"* Pages tracked: '''{total_tracked}'''",
        f"* Distinct QIDs: '''{unique_qids}'''",
        f"* Duplicated QIDs: '''{len(duplicates)}'''",
        "",
    ]
    if duplicates:
        lines.append("== Duplicates ==")
        lines.append("")
        for qid in sorted(duplicates, key=lambda q: (-len(duplicates[q]), q)):
            pages = sorted(duplicates[qid])
            lines.append(f"=== [[d:{qid}|{qid}]] ({len(pages)} pages) ===")
            for p in pages:
                lines.append(f"* [[{p}]]")
            lines.append("")
    else:
        lines.append("''No duplicates found.''")
        lines.append("")

    lines.append("[[Category:Maintenance reports]]")
    return "\n".join(lines) + "\n"


def load_state(path: str) -> dict:
    if not os.path.exists(path):
        print(f"State file not found: {path}")
        print("No orchestrator has populated it yet. Nothing to render.")
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"Could not read state file {path}: {e}")
        return {}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="Actually save the report (default: dry-run).")
    parser.add_argument("--max-edits", type=int, default=1,
                        help="Report page count cap (default 1 — there is only "
                             "ever one write).")
    parser.add_argument("--run-tag", required=True,
                        help="Run tag appended to the edit summary for auditing.")
    args = parser.parse_args()

    state = load_state(STATE_FILE)
    total_tracked = len(state)

    qid_to_pages: dict[str, list[str]] = defaultdict(list)
    for title, qid in state.items():
        qid_to_pages[qid].append(title)

    duplicates = {q: ps for q, ps in qid_to_pages.items() if len(ps) > 1}
    unique_qids = len(qid_to_pages)

    print(f"Tracked titles:  {total_tracked}")
    print(f"Distinct QIDs:   {unique_qids}")
    print(f"Duplicated QIDs: {len(duplicates)}")

    report = build_report(duplicates, total_tracked, unique_qids)

    if not args.apply:
        print(f"[DRY] would write {len(duplicates)} dupe entries to [[{REPORT_TITLE}]]")
        return

    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent=USER_AGENT)
    site.connection.timeout = 120
    site.login(USERNAME, PASSWORD)
    print(f"Logged in as {USERNAME}")

    page = site.pages[REPORT_TITLE]
    summary = (f"Bot: refresh duplicate page QID report "
               f"({len(duplicates)} dupes across {total_tracked} tracked pages) "
               f"{args.run_tag}")
    page.save(report, summary=summary)
    time.sleep(THROTTLE)
    print(f"Saved [[{REPORT_TITLE}]]")


if __name__ == "__main__":
    main()
