#!/usr/bin/env python3
"""
find_duplicate_page_qids.py
============================
Walks every page in [[Category:Pages linked to Wikidata]] (across all
namespaces — mainspace, Template, Category, and every other namespace
where {{wikidata link|...}} is transcluded), reads the QID out of the
template, and writes a maintenance report to [[Duplicate page QIDs]]
listing every QID that is claimed by more than one wiki page.

The report is rewritten from scratch on each run (single page, one write),
so there is no per-entry state file. The scan is read-only against every
page in the category; the THROTTLE sleep is only applied around the one
write at the end.

Standard flags: ``--apply`` (default dry-run), ``--max-edits`` (only the
report page is written, so default is 1), ``--run-tag``.
"""

import argparse
import io
import os
import re
import sys
import time
from collections import defaultdict

import mwclient

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL = "shinto.miraheze.org"
WIKI_PATH = "/w/"
USERNAME = os.getenv("WIKI_USERNAME", "EmmaBot")
PASSWORD = os.getenv("WIKI_PASSWORD", "")
THROTTLE = 2.5

USER_AGENT = "EmmaBot/1.0 (https://shinto.miraheze.org/wiki/User:EmmaBot) shintowiki-scripts"

SOURCE_CATEGORY = "Pages linked to Wikidata"
REPORT_TITLE = "Duplicate page QIDs"

# {{wikidata link|Qxxx ...}}
WDLINK_RE = re.compile(r"\{\{\s*wikidata\s*link\s*\|\s*(Q\d+)", re.IGNORECASE)


# ─── MAIN ──────────────────────────────────────────────────

def build_report(duplicates, scanned, no_qid):
    lines = [
        "{{DISPLAYTITLE:Duplicate page QIDs}}",
        "Pages that share a Wikidata QID with at least one other page. "
        "Auto-generated by [[User:EmmaBot]] — do not edit manually.",
        "",
        f"* Pages scanned: '''{scanned}'''",
        f"* Pages with no QID extractable: '''{no_qid}'''",
        f"* Duplicated QIDs: '''{len(duplicates)}'''",
        "",
    ]
    if duplicates:
        lines.append("== Duplicates ==")
        lines.append("")
        # Sort by (page-count desc, qid asc) so the worst offenders rise to the top.
        for qid in sorted(duplicates, key=lambda q: (-len(duplicates[q]), q)):
            pages = sorted(duplicates[qid])
            lines.append(f"=== [[d:{qid}|{qid}]] ({len(pages)} pages) ===")
            for p in pages:
                lines.append(f"* [[{p}]]")
            lines.append("")
    else:
        lines.append("''No duplicates found.''")
        lines.append("")

    lines.append("[[Category:Maintenance reports]]")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="Actually save the report (default: dry-run).")
    parser.add_argument("--max-edits", type=int, default=1,
                        help="Report page count cap (default 1 — there is only "
                             "ever one write).")
    parser.add_argument("--run-tag", required=True,
                        help="Run tag appended to the edit summary for auditing.")
    args = parser.parse_args()

    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent=USER_AGENT)
    site.connection.timeout = 120
    site.login(USERNAME, PASSWORD)
    print(f"Logged in as {USERNAME}")

    cat = site.categories[SOURCE_CATEGORY]

    qid_to_pages = defaultdict(list)
    scanned = 0
    no_qid = 0
    for page in cat:
        try:
            text = page.text()
        except Exception as e:
            print(f"  [warn] could not read {page.name}: {e}")
            continue
        m = WDLINK_RE.search(text)
        if m:
            qid_to_pages[m.group(1)].append(page.name)
        else:
            no_qid += 1
        scanned += 1
        if scanned % 200 == 0:
            print(f"  scanned {scanned} pages ({len(qid_to_pages)} distinct QIDs so far)")

    duplicates = {q: ps for q, ps in qid_to_pages.items() if len(ps) > 1}
    print(f"\nScan complete: {scanned} pages, "
          f"{len(qid_to_pages)} distinct QIDs, "
          f"{len(duplicates)} duplicated, "
          f"{no_qid} with no QID extractable.")

    report = build_report(duplicates, scanned, no_qid)

    if not args.apply:
        print(f"[DRY] would write {len(duplicates)} dupe entries to [[{REPORT_TITLE}]]")
        return

    page = site.pages[REPORT_TITLE]
    summary = (f"Bot: refresh duplicate page QID report "
               f"({len(duplicates)} dupes across {scanned} pages) {args.run_tag}")
    page.save(report, summary=summary)
    time.sleep(THROTTLE)
    print(f"Saved [[{REPORT_TITLE}]]")


if __name__ == "__main__":
    main()
