#!/usr/bin/env python3
"""
finish_japanese_content_merge.py
================================
Finish the cleanup that `git_sync_strip_property_dumps.py` only half-did.

Emma 2026-07-09:

    "As per this page [[Tamatsukuri Shrine (Q134930396)]] I noticed that a large
    amount of the pages that were supposed to be corrected because they were giant
    property lists but had Japanese language content in them were just kind of not
    corrected enough. I corrected this one enough, so you can look at the history
    to see my last two edits that I did that actually changed it to the desired
    form."

    "Headings go up so === -> == and categories heading goes away."

    "These ones will have the category [[Category:Formerly autogenerated pages]] —
    the category does not exist, add it anyway."

The property-dump stripper deliberately stops at `== Japanese content ==`, so it
removed the `== … (Pxxx) ==` dump and left the rest: the autogenerated stub lead
sitting above a duplicate imported lead, the `== Japanese content ==` wrapper, its
subsections still at `===` depth, and a `== Categories ==` heading.

THE SPEC IS EMMA'S OWN EDIT. `tests/fixtures/tamatsukuri_{before,after}.wiki` are
revisions 3825479 and 3828659 of that page, and `test_finish_japanese_content_merge`
requires `transform()` to reproduce the "after" byte for byte. If a rule here is
wrong, that test fails.

WHAT IS ALWAYS SAFE (applied to every page)
-------------------------------------------
* drop the `== Japanese content ==` heading — its section is now the article
* drop an `{{Otheruses|…}}` hatnote *immediately* under that heading
* promote `=== X ===` to `== X ==`
* drop the `== Categories ==` heading and the blank line before it
* add `[[Category:Formerly autogenerated pages]]`

WHAT IS NOT ALWAYS SAFE (applied only where unambiguous)
--------------------------------------------------------
Merging the stub lead into the imported lead. That needs exactly one stub lead
above the heading and exactly one imported `'''Name''' (kana) is …` lead below it.
745 of the 905 pages qualify; 152 have no imported lead in that form (they open
straight into `{{Shinto shrine}}` or a maintenance template) and 8 have two
candidates. On those the leads are LEFT ALONE and counted — never blanked, because
blanking a stub lead with nothing to merge it into destroys the article's lead.

    python finish_japanese_content_merge.py [--apply] [--max N]

Read-only on the wiki: it rewrites `git_synced/*.wiki`, and the existing repo-wins
`sync_git_synced_pages.py` pushes them.
"""
import argparse
import collections
import glob
import io
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
GIT_SYNCED = os.path.join(REPO_ROOT, "git_synced")

NEW_CATEGORY = "[[Category:Formerly autogenerated pages]]"
GIT_SYNCED_CAT = "[[Category:Git synced pages]]"

JC_HEADING = re.compile(r"^\s*==+\s*Japanese content\s*==+\s*$")
CATEGORIES_HEADING = re.compile(r"^\s*==+\s*Categories\s*==+\s*$")
ANY_HEADING = re.compile(r"^==+.*==+\s*$")
OTHERUSES = re.compile(r"^\s*\{\{Otheruses\|.*\}\}\s*$")


def promote_heading(line):
    """`=== X ===` -> `== X ==`, `==== X ====` -> `=== X ===`. Level 2 untouched.

    Emma: "Headings go up so === -> ==". Everything under the removed
    `== Japanese content ==` wrapper moves up exactly one level, `====` included.

    Counting the `=` runs rather than matching `^===(.+?)===$`: that pattern also
    matches `==== Sub ====` (its lazy group happily captures `= Sub =`) and turns
    it into `== = Sub = ==`. That mangled 30 pages before this was caught.
    """
    s = line.rstrip()
    lead = len(s) - len(s.lstrip("="))
    trail = len(s) - len(s.rstrip("="))
    if lead < 3 or lead != trail or len(s) <= lead + trail:
        return line
    body = s[lead:len(s) - trail]
    if not body.strip():
        return line
    return "=" * (lead - 1) + body + "=" * (trail - 1)

# The autogenerated stub lead, e.g.
#   {{nihongo|'''Tamatsukuri Shrine'''|玉作神社}} is a [[shinto shrine]] in the
#   [[Engishiki Jinmyōchō]]. It is located in [[Izu Province]].
STUB_LEAD = re.compile(
    r"^\{\{nihongo\|'''(?P<name>.+?)'''\|(?P<kanji>.+?)\}\} "
    r"is a \[\[shinto shrine\]\] in the \[\[Engishiki Jinmyōchō\]\]\."
)
# The imported jawiki lead, e.g.
#   '''Tamatsukuri Shrine''' (たまつくりじんじゃ) is a {{ill|Shinto shrine|…}} located in …
IMPORTED_LEAD = re.compile(r"^'''(?P<name>.+?)''' \((?P<kana>[^)]*)\)\s+(?P<rest>is .*)$")


def transform(text):
    """Returns (new_text, outcome) where outcome describes the lead handling."""
    lines = text.split("\n")

    jc = [i for i, ln in enumerate(lines) if JC_HEADING.match(ln)]
    if not jc:
        return text, "no-japanese-content"
    jc = jc[0]

    stubs = [i for i, ln in enumerate(lines) if i < jc and STUB_LEAD.match(ln)]

    # The imported lead must be in LEAD POSITION — after the Japanese-content
    # heading and before the article's first subheading. Without that bound the
    # pattern also matches bolded sentences deeper in the article that open a
    # subsection about something else entirely: a deity ("'''Ashiinaba-no-Kami'''
    # (…) is enshrined…"), a festival, a sub-shrine, a mountain. Those are not
    # leads and must never be rewritten as one.
    end = next((i for i in range(jc + 1, len(lines)) if ANY_HEADING.match(lines[i])), len(lines))
    leads = [i for i in range(jc + 1, end) if IMPORTED_LEAD.match(lines[i])]

    outcome = "merged"
    if len(stubs) == 1 and len(leads) == 1:
        s, l = stubs[0], leads[0]
        stub_line = lines[s]
        m = STUB_LEAD.match(stub_line)
        rest = IMPORTED_LEAD.match(lines[l]).group("rest")
        # The stub's {{nihongo}} becomes the article's opening; its sentence is
        # kept verbatim at the end of the paragraph, as Emma did.
        lines[l] = (
            "{{nihongo|'''%s'''|%s}} %s %s" % (m.group("name"), m.group("kanji"), rest, stub_line)
        )
        lines[s] = ""
    else:
        outcome = "lead-untouched(%d stub,%d lead)" % (len(stubs), len(leads))

    # Drop an Otheruses hatnote directly under the heading.
    if jc + 1 < len(lines) and OTHERUSES.match(lines[jc + 1]):
        del lines[jc + 1]

    out = []
    for ln in lines:
        # Every Japanese-content heading, not just the first: two pages are two
        # autogenerated articles concatenated and carry the heading twice.
        if JC_HEADING.match(ln):
            continue
        if CATEGORIES_HEADING.match(ln):
            while out and out[-1].strip() == "":
                out.pop()
            continue
        out.append(promote_heading(ln))

    text = "\n".join(out)
    if NEW_CATEGORY not in text:
        if GIT_SYNCED_CAT in text:
            text = text.replace(GIT_SYNCED_CAT, NEW_CATEGORY + "\n" + GIT_SYNCED_CAT, 1)
        else:
            text = text.rstrip("\n") + "\n" + NEW_CATEGORY + "\n"
    return text, outcome


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write the files (default: dry run)")
    ap.add_argument("--max", type=int, default=0, help="cap pages this run (0 = no cap)")
    args = ap.parse_args()
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

    stats = collections.Counter()
    untouched = []
    changed = 0
    for path in sorted(glob.glob(os.path.join(GIT_SYNCED, "*.wiki"))):
        text = io.open(path, encoding="utf-8").read()
        new, outcome = transform(text)
        if outcome == "no-japanese-content":
            continue
        stats[outcome.split("(")[0]] += 1
        if outcome.startswith("lead-untouched"):
            untouched.append((os.path.basename(path), outcome))
        if new != text:
            changed += 1
            if args.apply:
                io.open(path, "w", encoding="utf-8", newline="\n").write(new)
        if args.max and changed >= args.max:
            break

    print(f"pages with a Japanese-content heading: {sum(stats.values())}")
    for k, v in stats.most_common():
        print(f"  {k:22s} {v}")
    print(f"\n{changed} page(s) {'rewritten' if args.apply else 'would change'}")
    if untouched:
        print(f"\nleads left alone ({len(untouched)}) — first 10:")
        for name, why in untouched[:10]:
            print(f"  {name[:50]:52s} {why}")
    if not args.apply:
        print("\n(dry run — pass --apply to write)")


if __name__ == "__main__":
    main()
