#!/usr/bin/env python3
"""
report_multiple_wikidata_links.py
=================================
Render-once standalone (like ``find_duplicate_page_qids.py``) that surfaces
backlog item 4 — pages carrying two or more ``{{wikidata link|Q…}}`` templates.
A page should map to exactly one Wikidata item; 2+ links almost always means a
Wikidata disambiguation issue (the page maps to several items, usually one is
correct, or the page should be split).

Source of truth is the live category ``[[Category:Pages with multiple wikidata
links]]``, populated by the ``multiple_wikidata_links`` orchestrator op as it
sweeps. For each member page this renderer extracts the QIDs from every
``{{wikidata link|Q…}}`` call, fetches each item's English label + description
from Wikidata, and writes them side by side to a wiki review page so a human can
pick the correct QID (delete the others) or decide the page needs splitting.

Read-only on content pages — the ONLY write is to the report page
``[[Multiple wikidata links]]``. The op self-heals each page out of the category
once it's back down to one link, so the report maintains itself.

Standard flags: ``--apply`` (default dry-run), ``--max-edits`` (always 1 — one
write, to the report page), ``--run-tag``.
"""

import argparse
import io
import os
import re
import sys
import time

import mwclient
import requests

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL = "shinto.miraheze.org"
WIKI_PATH = "/w/"
USERNAME = os.getenv("WIKI_USERNAME", "EmmaBot")
PASSWORD = os.getenv("WIKI_PASSWORD", "")
THROTTLE = 2.5

USER_AGENT = "EmmaBot/1.0 (https://shinto.miraheze.org/wiki/User:EmmaBot) shintowiki-scripts"

SOURCE_CATEGORY = "Pages with multiple wikidata links"
REPORT_TITLE = "Multiple wikidata links"

_WD_API = "https://www.wikidata.org/w/api.php"
READ_THROTTLE = 0.3

# Captures the QID from "{{wikidata link|Q123|...}}" (the first positional
# slot is the QID). A blank "{{wikidata link}}" yields no match here, which is
# correct — a blank template is not a competing QID.
WD_LINK_QID_RE = re.compile(
    r"\{\{\s*wikidata\s*link\s*\|\s*(Q\d+)", re.IGNORECASE
)


def fetch_labels(qids: list[str]) -> dict[str, dict[str, str]]:
    """Return {qid: {'label': str, 'description': str, 'missing': bool}} for the
    given QIDs, English. Batches of 50; on API error the batch is marked
    unknown (label/description empty) rather than dropped."""
    out: dict[str, dict[str, str]] = {}
    uniq = sorted(set(qids))
    for i in range(0, len(uniq), 50):
        batch = uniq[i : i + 50]
        try:
            resp = requests.get(
                _WD_API,
                params={
                    "action": "wbgetentities",
                    "ids": "|".join(batch),
                    "props": "labels|descriptions",
                    "languages": "en",
                    "format": "json",
                },
                headers={"User-Agent": USER_AGENT},
                timeout=30,
            )
            resp.raise_for_status()
            entities = resp.json().get("entities", {})
        except Exception as e:
            print(f"  WD API error on batch {i // 50}: {e}")
            for q in batch:
                out[q] = {"label": "", "description": "", "missing": False}
            time.sleep(READ_THROTTLE)
            continue
        for q in batch:
            ent = entities.get(q, {})
            if "missing" in ent:
                out[q] = {"label": "", "description": "(deleted/missing item)",
                          "missing": True}
                continue
            label = (ent.get("labels", {}).get("en", {}) or {}).get("value", "")
            desc = (ent.get("descriptions", {}).get("en", {}) or {}).get("value", "")
            out[q] = {"label": label, "description": desc, "missing": False}
        time.sleep(READ_THROTTLE)
    return out


def get_category_members(site) -> list[str]:
    cat = site.categories[SOURCE_CATEGORY]
    return sorted(p.name for p in cat if p.namespace in (0, 14))


def build_report(page_qids: dict[str, list[str]],
                 labels: dict[str, dict[str, str]]) -> str:
    n = len(page_qids)
    lines = [
        "{{DISPLAYTITLE:Multiple wikidata links}}",
        "Pages carrying two or more {{tl|wikidata link}} templates — almost "
        "always a Wikidata disambiguation issue (the page maps to several items; "
        "usually one is correct, or the page should be split). "
        "Auto-generated by [[User:EmmaBot]] from "
        f"[[:Category:{SOURCE_CATEGORY}]] — do not edit manually. "
        "To resolve: keep the one correct {{tl|wikidata link}} and delete the "
        "others (the page self-heals out of the category on the next sweep), or "
        "split the page.",
        "",
        f"* Pages with multiple links: '''{n}'''",
        "",
    ]
    if not page_qids:
        lines.append("''No pages currently carry multiple wikidata links.''")
        lines.append("")
        lines.append("[[Category:Maintenance reports]]")
        return "\n".join(lines) + "\n"

    for title in sorted(page_qids):
        qids = page_qids[title]
        lines.append(f"=== [[{title}]] ({len(qids)} links) ===")
        for q in qids:
            info = labels.get(q, {"label": "", "description": ""})
            label = info.get("label") or "''(no English label)''"
            desc = info.get("description") or ""
            suffix = f" — {desc}" if desc else ""
            lines.append(f"* [[d:{q}|{q}]]: {label}{suffix}")
        lines.append("")

    lines.append("[[Category:Maintenance reports]]")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true",
                        help="Actually save the report (default: dry-run).")
    parser.add_argument("--max-edits", type=int, default=1,
                        help="Report page count cap (default 1).")
    parser.add_argument("--run-tag", required=True,
                        help="Run tag appended to the edit summary for auditing.")
    args = parser.parse_args()

    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent=USER_AGENT)
    site.connection.timeout = 120
    site.login(USERNAME, PASSWORD)
    print(f"Logged in as {USERNAME}")

    members = get_category_members(site)
    print(f"{len(members)} member(s) in [[Category:{SOURCE_CATEGORY}]]")

    page_qids: dict[str, list[str]] = {}
    all_qids: list[str] = []
    for title in members:
        try:
            text = site.pages[title].text()
        except Exception as e:
            print(f"  read error {title}: {e}")
            continue
        qids = []
        for m in WD_LINK_QID_RE.finditer(text):
            q = m.group(1).upper()
            if q not in qids:
                qids.append(q)
        # Only report when 2+ DISTINCT QIDs are actually present (the op tags on
        # 2+ templates; two blank templates, or two identical QIDs, are not a
        # real disambiguation issue and shouldn't clutter the report).
        if len(qids) >= 2:
            page_qids[title] = qids
            all_qids.extend(qids)
        time.sleep(READ_THROTTLE)

    print(f"{len(page_qids)} page(s) with 2+ distinct QIDs")
    labels = fetch_labels(all_qids) if all_qids else {}
    report = build_report(page_qids, labels)

    if not args.apply:
        print(f"[DRY] would write report for {len(page_qids)} pages to "
              f"[[{REPORT_TITLE}]]")
        print("--- report preview (first 1500 chars) ---")
        print(report[:1500])
        return

    page = site.pages[REPORT_TITLE]
    summary = (f"Bot: refresh multiple-wikidata-link report "
               f"({len(page_qids)} pages) {args.run_tag}")
    page.save(report, summary=summary)
    time.sleep(THROTTLE)
    print(f"Saved [[{REPORT_TITLE}]]")


if __name__ == "__main__":
    main()
