#!/usr/bin/env python3
"""
report_double_qid_tail.py
=========================
Render-once standalone (like ``find_duplicate_page_qids.py``) that surfaces
backlog item 3 — the residual tail of ``[[Category:Double category qids]]``.

These are disambiguation pages (titled ``Qxxxx``) created when two categories
were found to share a single Wikidata QID. ``resolve_double_category_qids.py``
auto-handles the easy cases in the cleanup loop: when only one of the two listed
categories still exists, the dab page becomes a redirect; same-target cases
collapse. What's left in the category is the genuinely-hard remnant — two (or
more) DISTINCT, still-existing category targets where a human has to decide
which is canonical (or merge them).

This renderer reads each dab page, extracts the competing ``[[:Category:…]]``
targets it lists, and for each target reports: whether it exists, its member
count, and the QID its ``{{wikidata link}}`` carries (if any). The dab page's
own title is the shared QID. Output goes to a wiki review page
(``[[Double category QID tail]]``) so a human can pick the winner — the decision
then feeds ``move_categories.py`` (recategorize losers → winner) or a manual
``#REDIRECT``.

Read-only on content pages — the ONLY write is to the report page. Standard
flags: ``--apply`` (default dry-run), ``--max-edits`` (always 1), ``--run-tag``.
"""

import os as _uos, sys as _usys
_uar = _uos.path.dirname(_uos.path.abspath(__file__))
while _uar != _uos.path.dirname(_uar) and not _uos.path.isdir(_uos.path.join(_uar, "shinto_miraheze")):
    _uar = _uos.path.dirname(_uar)
if _uar not in _usys.path:
    _usys.path.insert(0, _uar)
from shinto_miraheze.user_agent import USER_AGENT
import argparse
import io
import os
import re
import sys
import time

import mwclient

from wiki_login import login_with_retry

# ─── CONFIG ─────────────────────────────────────────────────
WIKI_URL = "shinto.miraheze.org"
WIKI_PATH = "/w/"
USERNAME = os.getenv("WIKI_USERNAME", "EmmaBot")
PASSWORD = os.getenv("WIKI_PASSWORD", "")
THROTTLE = 2.5


SOURCE_CATEGORY = "Double category qids"
REPORT_TITLE = "Double category QID tail"
READ_THROTTLE = 0.3

# A listed target on a dab page: "# [[:Category:Foo]]" or "* [[:Category:Foo]]"
# (the leading colon escapes the category link). Also accept a bare
# "[[Category:Foo]]" line, but EXCLUDE the page's own maintenance categories.
TARGET_RE = re.compile(
    r"\[\[\s*:?\s*Category\s*:\s*([^\]|]+?)\s*(?:\|[^\]]*)?\]\]",
    re.IGNORECASE,
)
WDLINK_RE = re.compile(r"\{\{\s*wikidata\s*link\s*\|\s*(Q\d+)", re.IGNORECASE)

# The dab page tags itself with these — they are NOT competing targets.
_SELF_TAGS = {
    "double category qids",
    "pages without wikidata",
    "duplicated qid category redirects",
    "currently double category qids",
}


def get_category_members(site) -> list[str]:
    cat = site.categories[SOURCE_CATEGORY]
    return sorted(p.name for p in cat)


def category_info(site, cat_name: str) -> dict:
    """Return {'exists': bool, 'count': int, 'qid': str|None} for a category."""
    page = site.pages["Category:" + cat_name]
    info = {"exists": False, "count": 0, "qid": None}
    try:
        if not page.exists:
            return info
        info["exists"] = True
        text = page.text()
        m = WDLINK_RE.search(text)
        if m:
            info["qid"] = m.group(1).upper()
        # Member count via the category object (subcats + pages).
        info["count"] = sum(1 for _ in site.categories[cat_name])
    except Exception as e:
        print(f"    info error for Category:{cat_name}: {e}")
    return info


def extract_targets(dab_text: str) -> list[str]:
    targets: list[str] = []
    for m in TARGET_RE.finditer(dab_text):
        name = m.group(1).strip()
        if name.lower() in _SELF_TAGS:
            continue
        if name not in targets:
            targets.append(name)
    return targets


def build_report(entries: list[dict]) -> str:
    lines = [
        "{{DISPLAYTITLE:Double category QID tail}}",
        "Residual disambiguation pages in "
        f"[[:Category:{SOURCE_CATEGORY}]] where two or more DISTINCT, still-"
        "existing categories share one Wikidata QID — the cases "
        "{{tl|resolve_double_category_qids}} deliberately leaves for a human "
        "(the single-existing-target cases auto-redirect). "
        "Auto-generated by [[User:EmmaBot]] — do not edit manually. "
        "To resolve: pick the canonical category, then recategorize the "
        "loser(s) into it (feed {{tl|move categories}}) or redirect.",
        "",
        f"* Dab pages in tail: '''{len(entries)}'''",
        "",
    ]
    if not entries:
        lines.append("''Tail is empty — nothing left for human review.''")
        lines.append("")
        lines.append("[[Category:Maintenance reports]]")
        return "\n".join(lines) + "\n"

    for e in entries:
        lines.append(f"=== [[{e['title']}]] ([[d:{e['title']}|{e['title']}]]) ===")
        if not e["targets"]:
            lines.append("* ''(no category targets parsed from the dab page — "
                         "may be malformed or already resolved)''")
            lines.append("")
            continue
        for t in e["targets"]:
            info = t["info"]
            if not info["exists"]:
                lines.append(f"* [[:Category:{t['name']}]] — '''does not exist''' "
                             "(auto-resolver should redirect this dab page)")
            else:
                qid = info["qid"] or "no {{wikidata link}}"
                lines.append(
                    f"* [[:Category:{t['name']}]] — {info['count']} member(s), "
                    f"QID: {qid}")
        lines.append("")

    lines.append("[[Category:Maintenance reports]]")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true",
                        help="Actually save the report (default: dry-run).")
    parser.add_argument("--max-edits", type=int, default=1,
                        help="Report page count cap (default 1).")
    parser.add_argument("--run-tag", required=True,
                        help="Run tag appended to the edit summary for auditing.")
    args = parser.parse_args()

    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

    site = mwclient.Site(WIKI_URL, path=WIKI_PATH, clients_useragent=USER_AGENT)
    site.connection.timeout = 120
    login_with_retry(site, USERNAME, PASSWORD)
    print(f"Logged in as {USERNAME}")

    members = get_category_members(site)
    print(f"{len(members)} dab page(s) in [[Category:{SOURCE_CATEGORY}]]")

    entries = []
    for title in members:
        try:
            text = site.pages[title].text()
        except Exception as e:
            print(f"  read error {title}: {e}")
            continue
        target_names = extract_targets(text)
        targets = []
        for name in target_names:
            targets.append({"name": name, "info": category_info(site, name)})
            time.sleep(READ_THROTTLE)
        entries.append({"title": title, "targets": targets})
        print(f"  {title}: {len(targets)} target(s)")
        time.sleep(READ_THROTTLE)

    report = build_report(entries)

    if not args.apply:
        print(f"[DRY] would write tail report for {len(entries)} dab pages to "
              f"[[{REPORT_TITLE}]]")
        print("--- report preview ---")
        print(report)
        return

    page = site.pages[REPORT_TITLE]
    summary = (f"Bot: refresh double-category-QID tail report "
               f"({len(entries)} dab pages) {args.run_tag}")
    page.save(report, summary=summary)
    time.sleep(THROTTLE)
    print(f"Saved [[{REPORT_TITLE}]]")


if __name__ == "__main__":
    main()
